### ISSUE TITLE
Default database in SQLFLOW_DATASOURCE

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#1007]
**Description**
Even has defined environment parameter `SQLFLOW_DATASOURCE` at client side, the `TRAIN` clause cannot fetch access to right database when creating temporary table for train and validation dataset.

The same problem also occurred at `predict` clause.

**Screenshots**
<img width="1437" alt="46294C2B-9CC8-4B39-B326-56FF30A450C0" src="https://user-images.githubusercontent.com/4661989/66803654-d3b93d80-ef52-11e9-89ee-78a44089dd58.png">

![20191015141602](https://user-images.githubusercontent.com/4661989/66805028-8dfe7400-ef56-11e9-8227-0e377d51b640.jpg)

**Comment by weiguoz** [comment]
Thanks for your feedback. It contains 2 issues:
- Lack of permissions for the database(`default`) while running `TRAIN` clause
It's already discussed here: https://github.com/sql-machine-learning/sqlflow/issues/674#issuecomment-539959874 and SQLFlow team will fix this ASAP.
- `predict` clause
I think you want to write the result into table `iris_dnn_predict` under the database `datamap_test`.

**Comment by BlackPoint-CX** [comment]
> * `predict` clause
>   I think you want to write the result into table `iris_dnn_predict` under the database `datamap_test`, but it looks the table is put under database `sqlflow`?

Yes, it should be write into database `datamap_test`.

**Comment by typhoonzero** [comment]
@BlackPoint-CX did you tried creating the HDFS directory `/sqlflow` using:  `hdfs dfs -mkdir -p hdfs://localhost:8020/sqlflow`, or just add environment variable `SQLFLOW_HIVE_LOCATION_ROOT_PATH=/your/sqlflow/predict/result/tmp/dir` on the SQLFlow server before starting the SQLFlow server?

**Comment by BlackPoint-CX** [comment]
> @BlackPoint-CX did you tried creating the HDFS directory `/sqlflow` using: `hdfs dfs -mkdir -p hdfs://localhost:8020/sqlflow`, or just add environment variable `SQLFLOW_HIVE_LOCATION_ROOT_PATH=/your/sqlflow/predict/result/tmp/dir` on the SQLFlow server before starting the SQLFlow server?

Tried, still not working.

**Comment by typhoonzero** [comment]
The error is related to creating a managed table using the `LOCATION` clause. Seems using `create external table` is fine.
