### ISSUE TITLE
The docker image is enormous, and the download is slow.

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#1008]
Why are there 1.9GB in the [dockerhub](https://hub.docker.com/r/sqlflow/sqlflow/tags) SQLFlow image?
![image](https://user-images.githubusercontent.com/1908992/66808388-b50c7400-ef5d-11e9-86cd-50b99a75d938.png)

But docker pull  it has 4.63GB.
```
> docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
sqlflow/sqlflow         latest              d7d7aae05173        3 hours ago         4.63GB
```

**Comment by typhoonzero** [comment]
The uploaded image layers are compressed to save the bandwidth.

**Comment by tonyyang-svail** [comment]
@llxxxll I don't know how we can make our Dockerfile smaller at the moment. Python libraries make up most of the space increase from our ubuntu base image.

```
/# du -sh * | sort -hr | head -n 5
1.9G	miniconda
1.6G	usr
429M	root
399M	opt
226M	go
```

Python Packages:
```
398M	./tensorflow
143M	./xgboost
88M	./scipy
70M	./numpy
```

**Comment by typhoonzero** [comment]
I tried to use `python:slim` to reduce python installation size, but installing other dependencies like MySQL would be hard since it's based on Debian.
