### ISSUE TITLE
Jupyter Notebook output style error

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#1017]
**Description**
Jupyter Notebook 输出结果中，数据表格修饰线条不见了，导致输出结果的视觉效果不整齐；

**Reproduction Steps**
- `docker run -it -p 8888:8888 sqlflow/sqlflow:didi`
- run `http://localhost:8888/notebooks/titanic_dnn.ipynb`

**Expected Behavior**
![image](https://user-images.githubusercontent.com/1908992/66893389-8c997e00-f020-11e9-834a-d4f1248cc0d6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1908992/66893238-27458d00-f020-11e9-95db-155dcd97ee6a.png)

**Environment (Please complete the following information):**
 - OS:macOS Mojave 10.14.6
 - Browser: Chrome 版本 77.0.3865.90（正式版本） （64 位）
 - Version:

**Additional Notes**
这个镜像`sqlflow/sqlflow:didi`在运行时，有两处`.ipynb`文件链接失效。均为描述预处理文件` preprocess`的链接`/doc/tutorial/aspara2019/carprice_xgboost/carprice_preprocessing.py`，用户在当前镜像下无法直接跳转到该文件，建议修改为绝对路径。
/notebooks/activepower_clustering.ipynb
/notebooks/carprice_xgboost.ipynb

**Comment by llxxxll** [comment]
sqlflow/sqlflow:latest 已生效
sqlflow/sqlflow:didi 未更新

**Comment by shendiaomo** [comment]
@llxxxll <img width="1482" alt="屏幕快照 2019-10-24 上午11 13 13" src="https://user-images.githubusercontent.com/4180295/67450265-62af0f80-f64f-11e9-999b-431a82d67cf1.png">
sqlflow/sqlflow:didi is out of date, it was updated 1 month ago, I would like to help. May I learn how to build the image and update it?

**Comment by shendiaomo** [comment]
> sqlflow/sqlflow:latest 已生效
> sqlflow/sqlflow:didi 未更新
@llxxxll 
I fixed it in shendiaomo/sqlflow:didi that you can try immediately.  I will push it to the sqlflow repository asap when I have access to the resource.

**Comment by shendiaomo** [comment]
> > sqlflow/sqlflow:latest 已生效
> > sqlflow/sqlflow:didi 未更新
> > @llxxxll
> > I fixed it in shendiaomo/sqlflow:didi that you can try immediately.  I will push it to the sqlflow repository asap when I have access to the resource.
sqlflow/sqlflow:didi is updated
