### ISSUE TITLE
Support pass HDFS temporary directory from client by put this config in session

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#1019]
Related: https://github.com/sql-machine-learning/sqlflow/issues/1007

When storing predict results to Hive, we intend to put the temporary result in a CSV file and upload it into some HDFS directory and then load it into the Hive table. This is faster than running `INSERT` statements.

The HDFS directory that stores the temporary CSV file is set by an environment variable `SQLFLOW_HIVE_LOCATION_ROOT_PATH` on the server side: https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/sql/executor.go#L586. For cases that Hive users that have restricted access to only part of the tables and HDFS directories, this may cause an error.

The solution is to pass an HDFS directory setting from the client, which the user have access to.

**Comment by typhoonzero** [comment]
Also, need to run `CREATE EXTERNAL TABLE ...` when creating the predict result table since it may not under `/usr/hive/warehouse`

**Comment by typhoonzero** [comment]
See: https://acadgild.com/blog/managed-and-external-tables-in-hive

**Comment by tonyyang-svail** [comment]
Agree to have HDFS directory settings in the client. Shall we support this setting in the data source string?

**Comment by typhoonzero** [comment]
Already implemented by adding `session.hive_location`.
