### ISSUE TITLE
SQLflow supports machine learning algorithms in spark

### ISSUE THREAD

**Issue by zwqjsj0404** [sql-machine-learning/sqlflow#1020]
**Is your feature request related to a problem? Please describe.**
A clear description of the problem

**Describe the solution you'd like**
A clear description of what you want to happen

**Describe alternatives (optional)**
A clear description of any alternative solutions or features

**Additional Notes**

**Comment by typhoonzero** [comment]
Close due to inactivity, we'll consider this feature if there are more use cases.
