### ISSUE TITLE
Continuous Integration with ElasticDL

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1038]
ElasticDL is under active development and shouldn't be cached in our Docker image build. The cache may cause our CI running with the older version of ElasticDL, which makes our CI hard to catch bugs.

However, SQLFlow CI should not build on the latest develop branch of ElasticDL because any API change in EDL will break the SQLFlow CI. So I suggest using one of the following techniques.

1. Add versioning to ElasticDL, and SQLFlow installs a specific version of ElasticDL.
1. SQLFlow still install the latest develop branch of ElasticDL, while ElasticDL repo has some unit tests with SQLFlow.

@terrytangyuan What do you think?

**Comment by terrytangyuan** [comment]
@tonyyang-svail Thanks for the suggestions! I prefer to the first suggestion. The second suggestion would require us adding SQLFlow as dependency in the ElasticDL CI which is not ideal given how large SQLFlow docker image is. We can `git checkout` a particular commit of ElasticDL after cloning the ElasticDL repo: https://github.com/sql-machine-learning/sqlflow/blob/e60790ffb9188042e93e78eb818b0552c0d91f8c/scripts/build_docker_image.sh#L114
and then every time when we need an upgrade, we can just update that commit hash and relevant code. Note that @ywskycn also started to release ElasticDL following semantic versioning so it would be much easier to upgrade once we get used to the release schedule.

**Comment by tonyyang-svail** [comment]
> We can git checkout a particular commit of ElasticDL after cloning the ElasticDL repo.

Sounds good. I will file a PR to implement this.
