### ISSUE TITLE
Rethinking changing from TRAIN to TO TRAIN

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1045]
SQLFlow syntax should be compatible with the standard SQL syntax. During our earlier experiments, we found using `TRAIN` along to denote the SQL extension is not enough. In the cases like
1. `select * from mytable train dnn ...`, the SQL syntax will treat `train` as an alias of `mytable`.
1. `select * from mytable train` where we eliminate the model name because of the automatic model selection.

These cases lead us to the motivation of changing `train` to `to train`.

All MySQL, MaxCompute, and Hive consider `TO` as a reversed keyword.
1. [MaxCompute reserved keyword list](https://www.alibabacloud.com/help/doc-detail/27872.htm?spm=a2c63.p38356.879954.6.631c5095hrjubf#concept-zxk-v5f-vdb)
1. [Hive reserved keyword list](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL)
1. [MySQL reserved keyword list](https://dev.mysql.com/doc/refman/5.5/en/keywords.html)

Usage of `TO` in each database:
1. In Hive, the only usage of `TO` is `ALTER TABLE table_name RENAME TO new_table_name;`.
1. In MySQL, `TO` is used in [`GRANT`](https://dev.mysql.com/doc/refman/8.0/en/grant.html) and [`RENAME`](https://dev.mysql.com/doc/refman/8.0/en/rename-table.html).
1. In MaxCompute, [`ALTER TABLE table_name RENAME TO new_table_name;`](https://www.alibabacloud.com/help/doc-detail/73768.html?spm=a2c5t.11065259.1996646101.searchclickresult.5afd4bd7qECSMQ) and [`alter table table_name changeowner to 'ALIYUN$xxx@aliyun.com';`](https://www.alibabacloud.com/help/doc-detail/73768.html?spm=a2c5t.11065259.1996646101.searchclickresult.5afd4bd7qECSMQ)

So Given a SQL statement `SELECT ... TO TRAIN`, a good SQL parser should raise error exactly at the position of `TO`.

**Comment by tonyyang-svail** [comment]
I will continue the experiment at [tidb_parser_test.go](https://github.com/sql-machine-learning/sqlflow/blob/e5d52a68c4e7ffbe3110ae6d046858115f6b2c06/parser/tidb/tidb_parser_test.go.txt), and come up with a design doc describing how SQLFlow translate an SQL program (a list of SQL statements) to an intermediate representation.

**Comment by typhoonzero** [comment]
~~I would suggest writing our own parser inheriting from TiDB's parser.~~

Update: The advantage of inheriting TiDB's parser is we can use `TRAIN` instead of `TO TRAIN`. However, as commented [here](https://github.com/sql-machine-learning/sqlflow/issues/998#issuecomment-545233399), making `TRAIN` a keyword hurts the user experience.

**Comment by tonyyang-svail** [comment]
Paring the SQL program using a third party parser has the following

Pros:

1. Distinguishing a SQL statement between standard SQL and extended SQL becomes trivial (i.e. if the third party parser can't parse the statement alone, then it is an extended SQL statement).

1. Splitting a SQL program into multiple SQL statements becomes trivial.


Cons:

1. We need to check the statement is starting by a select. Consider the case `describe table to train dnn`, the third party parser split the SQL into `describe table` and `to train dnn`, both statements are acceptable by each parser, however, `describe table` is not a select statement. Solution: check the AST node type like [here](https://github.com/sql-machine-learning/sqlflow/blob/36e3d6a8daa1f270792c2e5ed45c4769270a1b47/parser/tidb/tidb_parser.go#L75-L80).

1. We need to support split multiple SQL statements. Solution: TiDB parser supports parsing multiple statements to multiple AST nodes at once. We can recover the SQL statement by [`node.Text()`](https://github.com/sql-machine-learning/sqlflow/blob/36e3d6a8daa1f270792c2e5ed45c4769270a1b47/parser/tidb/tidb_parser.go#L84).

**Comment by tonyyang-svail** [comment]
Splitting the SQL program using a Lexer by finding `TO TRAIN` tokens has the following

Pros:

1. Easy to implement.

Cons:

1. Needs to deal with special cases like `ALTER TABLE table_name RENAME TO train`.
