### ISSUE TITLE
Experiment on Using Third Party Parser to Parse SQL Program

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1065]
This issue is used to bookkeep the progress of the experiment.

Motivation: #998 and #1045 
Design: https://github.com/sql-machine-learning/sqlflow/blob/develop/parser/README.md

The experiment want to prove: by changing `TRAIN` to `TO TRAIN`, leveraging the third party parser can

1. Splitting the SQL program into multiple SQL statements.
1. Splitting the standard SQL and the extended SQL.

Current progress:

1. TiDB parser: https://github.com/sql-machine-learning/sqlflow/pull/1046
1. HiveQL parser: TBD
1. Calcite parser: TBD

**Comment by typhoonzero** [comment]
We already have third-party parsers to implement "collaborative parsing".
