### ISSUE TITLE
Need a better way to pass arbitrary client environment variables to SQLFlow server

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#1068]
We pass some configurations from client environment variables now:  https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/server/proto/sqlflow.proto#L27, need a better way to pass several config fields using one protobuf field, instead of adding them one by one.

**Comment by Yancey0623** [comment]
How about sending all the env with prefix `SQLFLOW_` to the server?

**Comment by typhoonzero** [comment]
@Yancey1989  that's a viable solution.

**Comment by typhoonzero** [comment]
This is done in previous commits.
