### ISSUE TITLE
Is enableSession config for SQLFlow server redundant

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1076]
@Yancey1989 @typhoonzero @weiguoz Is there a use case that we set enableSession to false? If not, then should we remove `enableSession` field in the server struct?

https://github.com/sql-machine-learning/sqlflow/blob/a673f1b1e29f149988eb7d22fb6227040a35c6e1/pkg/server/sqlflowserver.go#L41-L46

I understanding is that the client uses a session message to pass the database connection information to the server, which is necessary since SQLFlow server needs to serve multiple clients.

If we always enable session, then the `db` field can also be removed. Having a stateful database makes our server stateful.

**Comment by typhoonzero** [comment]
I think we can remove `enableSession` now.

**Comment by Yancey0623** [comment]
I also think can remove it now, and for a mention, the server can not keep the `DB` object if `enableSession = ture` for the current implementation, the following case would be failed:

``` sql
cell1:
    use sqlflow_db;
cell2:
    select * from table limit 10; // sqlflow_db.table
```

The cell2 would be failed, the SQLFlow server can not keep the default database for  `use sqlflow_db`, using a full path: `sqlflow_db.table` can fix this problem.
