### ISSUE TITLE
Non-standard function API on xgboost.Pred

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1083]
`codegen.PredictIR` should be the **only** argument for `xgboost.Pred`, otherwise, `PredictIR` is no longer an IR.

Please change 

https://github.com/sql-machine-learning/sqlflow/blob/10e756372cb55d584d9d89e28bd92c85794525d9/pkg/sql/codegen/xgboost/codegen.go#L154

To `func Pred(ir *codegen.PredictIR) (string, error)`.

We can either add a field in PredictIR or encode the session info in the data source string.

**Comment by tonyyang-svail** [comment]
This non-standard API has caused our CI to fail. https://github.com/sql-machine-learning/sqlflow/pull/1082

**Comment by typhoonzero** [comment]
`IR` seems used to define parsed SQL statements, but the session is related to the client environment, maybe it's not suitable to put session in IR?

**Comment by tonyyang-svail** [comment]
> `IR` seems used to define parsed SQL statements, but the session is related to the client environment, maybe it's not suitable to put session in IR?

Sounds good.
