### ISSUE TITLE
An easier way to debug SQLFlow server

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#1101]
**Is your feature request related to a problem? Please describe.**

We need a way to debug on the SQLFlow server, e.g., print the generated code, print the stack trace if the program exit code is not 0 ...

**Comment by BlackPoint-CX** [comment]
1. When user `A` using  model to make predictions, SQLFlow will write result into one temporary local file at first. Then upload this local file into one HDFS directory (Let's say `/user/A/hdp` ) to which `A` has access to write. Finally   HIVE table will be created by loading data from this HDFS directory. It causes the problem that other users who has no access to write data into `/user/A/hdp` cannot use the same prediction clause. It will throw exception when copying data like following.
![image](https://user-images.githubusercontent.com/4661989/67827437-f890e180-fb0a-11e9-9786-936235225e8a.png)
