### ISSUE TITLE
Start to jupyter iris-dnn examples, then encounter this problem

### ISSUE THREAD

**Issue by HarryUlysses** [sql-machine-learning/sqlflow#1107]
**Description**
When I start to open a web browser, open iris-dnn.ipynb file and run the code...
`%%sqlflow
describe iris.train;`

But I encounter this problem:
/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/grpc/_channel.py in _next(self)
    363                 raise StopIteration()
    364             else:
--> 365                 raise self
    366 
    367             def _response_ready():

_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1572500632.931119638","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1572500571.009073496","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"

Who can help me? Thanks reaaaally much!

**Comment by typhoonzero** [comment]
Which tutorial did you follow to run start the notebook in docker container? Did you start your `sqlflowserver` somewhere and connect to it from your notebook?

**Comment by HarryUlysses** [comment]
I follow this tutorial.
[https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run/docker.md](url)
I think I still have not started my `sqlflowserver` somewhere else.
And this tutorial is too brief for me.

**Comment by typhoonzero** [comment]
For a quick start, you can check out https://sql-machine-learning.github.io/sqlflow/doc/quick_start/ here. Please continue to comment on this issue if you still got problems following the quick start document.

**Comment by HarryUlysses** [comment]
Thanks, but this tutorial you gave to is also being tried and does not work.
There is a question confused me a lot that should I load the iris datasets to mysql database in this docker container by myself or this process has been done well originally?
Should I do anything else, for example, starting mysql service in this docker container then loading the iris datasets to mysql before run `%%sqlflow describe iris.train` on iris-dnn.ipynb.
This quickstart only has 4 steps.
`1. Install Docker Community Edition.`
`2. Run SQLflow by typing the command docker run -it -p 8888:8888 sqlflow/sqlflow.`
`3. Access localhost:8888 in your Web browser.`
`4. Open the notebook iris-dnn.ipynb.`
Can I do anything else?

**Comment by typhoonzero** [comment]
The quick start docker image has sample ipython notebooks, mysql service, mysql sample datas installed. Just follow those 4 steps, you can see there are several sample iPython notebooks available, just open one of them like `iris-dnn.ipynb` and run the SQL statements and follow the tutorials.

**Comment by HarryUlysses** [comment]
OK! But this mistake still happens. I can not find some solutions to solve it.  The way you told me before does not work.
I only did those 4 steps.
Here is the full mistake information:
_Rendezvous                               Traceback (most recent call last)
<ipython-input-2-34512291d371> in <module>
----> 1 get_ipython().run_cell_magic('sqlflow', '', 'describe iris.train;\n')

/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2357             with self.builtin_trap:
   2358                 args = (magic_arg_s, cell)
-> 2359                 result = fn(*args, **kwargs)
   2360             return result
   2361 

</miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/decorator.py:decorator-gen-126> in execute(self, line, cell)

/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/sqlflow/magic.py in execute(self, line, cell)
     43 
     44         """
---> 45         return self.client.execute('\n'.join([line, cell]))
     46 
     47 def load_ipython_extension(ipython):

/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/sqlflow/client.py in execute(self, operation)
    106             # NOTE: raise exception to interrupt notebook execution. Or
    107             # the notebook will continue execute the next block.
--> 108             raise e
    109         except EnvExpanderError as e:
    110             raise e

/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/sqlflow/client.py in execute(self, operation)
    102         try:
    103             stream_response = self._stub.Run(self.sql_request(operation), timeout=DEFAULT_TIMEOUT)
--> 104             return self.display(stream_response)
    105         except grpc.RpcError as e:
    106             # NOTE: raise exception to interrupt notebook execution. Or

/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/sqlflow/client.py in display(cls, stream_response)
    116         while True:
    117             try:
--> 118                 first = next(stream_response)
    119             except StopIteration:
    120                 break

/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/grpc/_channel.py in __next__(self)
    386 
    387     def __next__(self):
--> 388         return self._next()
    389 
    390     def next(self):

/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages/grpc/_channel.py in _next(self)
    380                     raise StopIteration()
    381                 elif self._state.code is not None:
--> 382                     raise self
    383 
    384     def __iter__(self):

_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1572589712.328555590","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1572589712.328538405","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"

**Comment by typhoonzero** [comment]
I'm sorry but I can not reproduce the error you've encountered. This is in my execution result:

![image](https://user-images.githubusercontent.com/13348433/68006965-36316e00-fcb5-11e9-9b55-6b757a73c8a9.png)

Make sure you run `docker run -it -p 8888:8888 sqlflow/sqlflow:latest` and open your web browser and access `localhost:8888`. The `sqlflowserver` will start automatically inside the docker container.

**Comment by HarryUlysses** [comment]
Thanks very much for your time!!!
Look at my background log information, maybe it is the authentication identification problem?

[I 06:28:04.864 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 06:28:05.058 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 06:28:05.061 NotebookApp] Serving notebooks from local directory: /workspace
[I 06:28:05.062 NotebookApp] The Jupyter Notebook is running at:
[I 06:28:05.062 NotebookApp] `http://a62e95e5f22a:8888/`
[I 06:28:05.062 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 06:28:05.066 NotebookApp] No web browser found: could not locate runnable browser.
[I 06:28:20.070 NotebookApp] 302 GET / 1.81ms
[W 06:28:20.074 NotebookApp] Clearing invalid/expired login cookie username-localhost-8888
[E 06:28:20.271 NotebookApp] Could not open static file ''
[W 06:28:20.381 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js  11.76ms referer=`http://localhost:8888/tree?`
[W 06:28:20.592 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js  4.40ms referer=`http://localhost:8888/tree?`
[W 06:28:23.352 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (10.0.63.139) 5.48ms referer=`http://localhost:8888/notebooks/iris-dnn.ipynb`
[W 06:28:23.446 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (10.0.63.139) 4.23ms referer=`http://localhost:8888/notebooks/iris-dnn.ipynb`
[I 06:28:23.859 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 06:28:23.860 NotebookApp] Notebook iris-dnn.ipynb is not trusted
[I 06:28:24.507 NotebookApp] Kernel started: 9d6610af-933c-428f-be0e-cec404012721

**Comment by typhoonzero** [comment]
My overall running log is:
```
setup all-in-one
 * Starting MySQL database server mysqld                                                                                        No directory, logging in with HOME=/
                                                                                                                         [ OK ]
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
Connect to the datasource mysql://root:root@tcp(127.0.0.1:3306)/?maxAllowedPacket=0
mysql: [Warning] Using a password on the command line interface can be insecure.
2019/11/01 06:36:29 Launch server with insecure mode.
2019/11/01 06:36:29 Server Started at :50051
[I 06:36:30.696 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 06:36:31.104 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 06:36:31.117 NotebookApp] Serving notebooks from local directory: /workspace
[I 06:36:31.117 NotebookApp] The Jupyter Notebook is running at:
[I 06:36:31.117 NotebookApp] http://522d87e07ff1:8888/
[I 06:36:31.117 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 06:36:31.130 NotebookApp] No web browser found: could not locate runnable browser.
[I 06:36:33.749 NotebookApp] 302 GET / (172.17.0.1) 1.15ms
[E 06:36:33.861 NotebookApp] Could not open static file ''
[W 06:36:33.975 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (172.17.0.1) 21.09ms referer=http://localhost:8888/tree?
[W 06:36:34.139 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (172.17.0.1) 1.37ms referer=http://localhost:8888/tree?
[W 06:36:37.124 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (172.17.0.1) 4.99ms referer=http://localhost:8888/notebooks/iris-dnn.ipynb
[W 06:36:37.191 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (172.17.0.1) 3.02ms referer=http://localhost:8888/notebooks/iris-dnn.ipynb
[I 06:36:37.405 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 06:36:37.408 NotebookApp] Notebook iris-dnn.ipynb is not trusted
[I 06:36:37.735 NotebookApp] Kernel started: a2a2477b-224f-41bb-9d52-56be5124e72c
^C[I 06:36:57.007 NotebookApp] interrupted
Serving notebooks from local directory: /workspace
1 active kernel
The Jupyter Notebook is running at:
http://522d87e07ff1:8888/
Shutdown this notebook server (y/[n])? y
[C 06:36:58.390 NotebookApp] Shutdown confirmed
[I 06:36:58.392 NotebookApp] Shutting down 1 kernel
[I 06:36:58.797 NotebookApp] Kernel shutdown: a2a2477b-224f-41bb-9d52-56be5124e72c
```

If you can see:

```
2019/11/01 06:36:29 Launch server with insecure mode.
2019/11/01 06:36:29 Server Started at :50051
```

that means the sqlflowserver is started if this log does not apears, there must be some problem.

By the way, you can try to run `docker pull sqlflow/sqlflow:latest` to update to the latest docker image and try again.

**Comment by HarryUlysses** [comment]
You did it!!! Thanks very much!
Here is the main problem location:
```..
Connect to the datasource mysql://root:root@tcp(127.0.0.1:3306)/?maxAllowedPacket=0
flag provided but not defined: -datasource
Usage of sqlflowserver:
  -ca-crt string
        CA certificate file.
```
I can not start my sqlflow server.
After I run `docker pull sqlflow/sqlflow:latest`, then start it and it solved.

**Comment by typhoonzero** [comment]
That seems to be a recently fixed issue. Thanks for reporting!
