### ISSUE TITLE
Question about Model Zoo design

### ISSUE THREAD

**Issue by mhaoli** [sql-machine-learning/sqlflow#1141]
**Description**
In my understanding, when we want to release a version of model zoo, we need to run `Docker build` to get a Docker image. However, the design doc states that we need to run `Docker run`. Is there a mistake in my understanding or in the document?

Please refer to
https://github.com/sql-machine-learning/sqlflow/blame/develop/doc/design/model_zoo.md#L69

**Reproduction Steps**
None

**Expected Behavior**
None

**Screenshots**

**Environment (Please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional Notes**

**Comment by typhoonzero** [comment]
You are right, should be `docker build` I'll update the doc.
