### ISSUE TITLE
Feature derivation don't work well on MaxCompute

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#1201]
**Description**
ERRO[0055] runSQLProgram error:column not found or inferred: petal_length  package=sql
ERROR: column not found or inferred: petal_length
**Reproduction Steps**
Train a standard iris model without specifying the `COLUMN` clause.

**Expected Behavior**
Behave the same on both MySQL and MaxCompute.

**Screenshots**
![image](https://user-images.githubusercontent.com/4180295/69065812-45593f80-0a5b-11ea-8500-c5a3c66c3d9a.png)
![image](https://user-images.githubusercontent.com/4180295/69065850-543ff200-0a5b-11ea-96c5-ea7529b393dd.png)

**Comment by tonyyang-svail** [comment]
The error message is the same as #1195, so I am closing this issue and will fix #1195.
