### ISSUE TITLE
Add keywords ‘EXCLUDE’ during training

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1213]
Since there has been a simplification before, the mechanism for listing the columns is omitted during training. 
Therefore, all non-label fields are selected. However, in the actual modeling process, users often have their own willingness to customize columns, so adding the keyword 'EXCLUDE' is necessary during training.

**Comment by tonyyang-svail** [comment]
Hi @Echo9573, thanks for providing this feedback. Surely we can propose a design if the user finds this feature useful.

I am wondering what is the syntax of `EXCLUDE` in your mind. Is it like the following?

```SQL
SELECT * FROM some_table  -- select tens of columns
TO TRAIN some_model
COLUMN EXCLUDE(some_column_i_dont_need)
LABEL class
...
```

What is the benefit of adding this keyword than other workarounds like
1. [Creating a temporary table and drop one column](https://stackoverflow.com/a/1712243).
1. Listing all columns in the select clause.

**Comment by shendiaomo** [comment]
> Since there has been a simplification before, the mechanism for listing the columns is omitted during training.
> Therefore, all non-label fields are selected. However, in the actual modeling process, users often have their own willingness to customize columns, so adding the keyword 'EXCLUDE' is necessary during training.

Hive supports regular expressions, you can try https://stackoverflow.com/questions/54800500/hiveselect-all-column-exclude-two instead of the `exclude` clause.
