### ISSUE TITLE
Connect Mysql with sqlflow failed

### ISSUE THREAD

**Issue by YishuiLi** [sql-machine-learning/sqlflow#1220]
**Description**
running the following command:
```
docker run --rm -p 8888:8888 sqlflow/sqlflow bash -c \
"sqlflowserver --datasource='mysql://root:root@tcp(127.0.0.1:3306)/iris?maxAllowedPacket=0' &
SQLFLOW_SERVER=localhost:50051 jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''"
```
It reminds me "flag provided but not defined: -datasource"

![image](https://user-images.githubusercontent.com/16732930/69316068-f980e300-0c72-11ea-9389-51ef799f0a08.png)

**Environment:**
 - OS: CentOS 7
 - Docker image Info: 
![image](https://user-images.githubusercontent.com/16732930/69316211-4b296d80-0c73-11ea-8a75-2c660d6c7984.png)

**Comment by YishuiLi** [comment]
running the following command:
```
docker run --rm -p 8888:8888 -p 50051:50051 sqlflow/sqlflow bash -c \
"sqlflowserver & SQLFLOW_DATASOURCE='mysql://root:root@tcp(127.0.0.1:3306)/iris?maxAllowedPacket=0' &
SQLFLOW_SERVER=localhost:50051 jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''"
```

Then use python to connect sqlflow:
```
client = sqlflow.Client(server_url='localhost:50051')
rowset = client.run('SELECT * FROM iris.train')
```
![image](https://user-images.githubusercontent.com/16732930/69318726-c17c9e80-0c78-11ea-8bc7-ce0b27824dff.png)

**Comment by typhoonzero** [comment]
Please try the solution at https://github.com/sql-machine-learning/sqlflow/issues/1221#issuecomment-556970113.

Dup: https://github.com/sql-machine-learning/sqlflow/issues/1221

**Comment by YishuiLi** [comment]
> Please try the solution at [#1221 (comment)](https://github.com/sql-machine-learning/sqlflow/issues/1221#issuecomment-556970113).
> 
> Dup: #1221

use python to connect sqlflow:
client = sqlflow.Client(server_url='localhost:50051')
rowset = client.execute('SELECT * FROM iris.train')
![image](https://user-images.githubusercontent.com/16732930/69319885-030e4900-0c7b-11ea-886a-16434800f02b.png)

**Comment by typhoonzero** [comment]
Did you tried running `export SQLFLOW_DATASOURCE=mysql://.....` before running the client?

**Comment by YishuiLi** [comment]
> Did you tried running `export SQLFLOW_DATASOURCE=mysql://.....` before running the client?

It works. Thank you!
