### ISSUE TITLE
flag provided but not defined: -datasource

### ISSUE THREAD

**Issue by JBjumper** [sql-machine-learning/sqlflow#1221]
**Description**
have an error in running sqlflow with docker to connect hive 
error:flag provided but not defined: -datasource

**Reproduction Steps**
my command:
docker run --rm -p 8888:8888 sqlflow/sqlflow bash -c \
"sqlflowserver --datasource='hive://root:root@xxxx:10000/default' &
SQLFLOW_SERVER=localhost:50051 jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''"

**Expected Behavior**

**Screenshots**

**Environment (Please complete the following information):**
 - OS:ubuntu 16.4
 - Browser:chrome
 - Version:

**Additional Notes**

**Comment by typhoonzero** [comment]
Seems the documentation need to be updated: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run_with_mysql.md

In current latest version, we've removed the argument `-datasource`, please start sqlflowserver and do not pass the `-datasource` argument.  Then you can specify the datasource by setting the environment variable `SQLFLOW_DATASOURCE=hive://.....` in the jupyter notebook or on the machine that runs the sqlflow client.
