### ISSUE TITLE
Model table are loaded twice for prediction/explain job

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1240]
The first time loading model table is at `generatePredictIR` to generate `PredIR.TrainIR`.
 
https://github.com/sql-machine-learning/sqlflow/blob/e907cada17489c650802884dafc233b1ed039a21/pkg/sql/ir_generator.go#L105

The second time loading model table is at `runPredIR` to recover the model directory.

https://github.com/sql-machine-learning/sqlflow/blob/e907cada17489c650802884dafc233b1ed039a21/pkg/sql/executor_ir.go#L264

It would be great to only load model table once. @typhoonzero What do you think?

The same situation also applies to explain jobs.

**Comment by typhoonzero** [comment]
Thanks for reporting this, I will find a solution.

**Comment by typhoonzero** [comment]
A possible solution is to implement a `Request` struct containing:

1. Server-side configurations
1. SQL to be ran
1. parsed IR
1. current working directory
1. session

we can pass the `Request` around until the request is properly processed, that's called the "life-cycle" of one request. After this change, for an example, current function arguments will be much simpler:

```go
func runSQLProgram(wr *PipeWriter, sqlProgram string, db *database.DB, modelDir string, session *pb.Session) error
```

To 

```go
func runSQLProgram(wr *PipeWriter, request *Request) error
```

A possible `Request` may look like:

```go
type Request struct {
    SQLProgram string
    IR ir.SQLProgram // parsed 
    Conn db.DB // connection to database for current request
    Cwd string // current working directory, will generate python code, save model, load model to this path
    IsModelLoaded bool // true if model is loaded into Cwd
    Session *pb.Session
    ModelSaveDir string // directory for save/load model, empty if we are going to save model to db
}
```

**Comment by tonyyang-svail** [comment]
> A possible solution is to implement a Request struct containing:

Is this request struct the same message for the client? If so, why should the client care about IR?

**Comment by typhoonzero** [comment]
After some discussion, we can try to implement request struct under current `sql` package.

**Comment by typhoonzero** [comment]
Related: https://github.com/sql-machine-learning/sqlflow/issues/1536
