### ISSUE TITLE
lowercase keywords 'limit' report an error when training model

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1263]
There is an error reported when I use the lowercase keyword 'limit', shown as follows:
![image](https://user-images.githubusercontent.com/24820352/69638922-9b029d00-1096-11ea-810c-8f993fff0e2f.png)
![image](https://user-images.githubusercontent.com/24820352/69638942-a229ab00-1096-11ea-8eec-3f2d10dd95ef.png)

**Comment by tonyyang-svail** [comment]
Hi @Echo9573, thanks for submitting this issue. I will take a look at it. For the time being, please use `LIMIT` in capital cases.
