### ISSUE TITLE
train successfully, but no data in hive table

### ISSUE THREAD

**Issue by lavystord** [sql-machine-learning/sqlflow#1277]
**Description**
train successfully, but no data in hive table

**Reproduction Steps**
```shell
#!/usr/bin/env bash

INPUT_SQL="select * from pre.sqlflow_test_data to TRAIN sqlflow_models.DNNClassifier WITH model.n_classes = 3,model.hidden_units = [10,20] COLUMN sepal_length,sepal_width,petal_length,petal_width LABEL class INTO pre.iris_dnn_model22;"
HADOOP_USER_NAME="xxx"
HADOOP_USER_PASSWORD="xxxx"
MR_QUEUE_NAME="xxxx"
DEFAULT_DATABASE="pre"
#hive server
DATA_STUDIO_HIVESERVER2_IP="xxxx"
DATA_STUDIO_HIVESERVER2_PORT="xxxx"
SQL_FILE="/tmp/flow.sql"

DATASOURCE="hive://${HADOOP_USER_NAME}:${HADOOP_USER_PASSWORD}@${DATA_STUDIO_HIVESERVER2_IP}:${DATA_STUDIO_HIVESERVER2_PORT}/${DEFAULT_DATABASE}?auth=PLAIN&session.mapreduce.job.queuename=${MR_QUEUE_NAME}&session.hive.exec.compress.intermediate=true&session.hive.auto.convert.join=true&session.hive.exec.parallel=true"
echo "datasource is ${DATASOURCE}"

echo "${INPUT_SQL}" > ${SQL_FILE}

~/go/bin/repl -f "${SQL_FILE}" --datasource="${DATASOURCE}"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16117095/69803770-fd36db80-1217-11ea-80fe-1e3277b8925a.png)
![image](https://user-images.githubusercontent.com/16117095/69803786-0627ad00-1218-11ea-81b3-b9b0070d2d15.png)

**Environment (Please complete the following information):**
DiDi SQLFlow_snapshot_20191128_v0.5

**Comment by Yancey0623** [comment]
Hi @lavystord , thanks for the issue, I have reproduced your case, and I believe this is a bug, I will fix it ASAP.

**Comment by Yancey0623** [comment]
Hi @lavystord , Can you show the result of `SELECT * FROM pre.iris_dnn_model22  limit 1;`, and does the path `/user/prod_pre/pre/hive` is the default hive table location?
