### ISSUE TITLE
Determine the ordering of records for a SELECT statement in MySQL

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#133]
[In SQL, a select statement does not guarantee consistent ordering between runs](https://dba.stackexchange.com/a/6053). 

Say a user uses

```SQL
SELECT *
FROM iris.iris
PREDICT iris.predict.class
USING my_dnn_model;
```

to predict `class` and store the prediction into table `iris.predict`, he/she can not directly compare it with ground truth `iris.iris.class` because the row ordering can be different.

So in order to produce useful prediction, we need to figure out a way to solve the correspondence.

ref: [SQL doesn't guarantee ordering](https://dba.stackexchange.com/a/6053)

**Comment by typhoonzero** [comment]
We can output the `ID` column together with features and predict results to the result table now. See the example here:

https://github.com/sql-machine-learning/sqlflow/blob/39a9701d99aa1e989cccc7dc3d17056f6848f85f/go/cmd/sqlflowserver/e2e_pai_maxcompute_test.go#L126
