### ISSUE TITLE
How to make minikube reuse local Docker image

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1330]
During the development, we submit a workflow to the local Minikube cluster. The execute of workflow involves pulling `sqlflow/sqlflow` image. Since we may modify the `sqlflow/sqlflow` image locally, we need to make sure the `sqlflow/sqlflow` is pulled from the local image registry, instead of `sqlflow/sqflow` in our DockerHub.

**Comment by tonyyang-svail** [comment]
[This solution](https://stackoverflow.com/questions/42564058/how-to-use-local-docker-images-with-minikube) seems only works on Linux.

**Comment by Yancey0623** [comment]
Can use minikube's built-in Docker daemon by executing `eval $(minikube docker-env)`, ref: https://gist.github.com/kevin-smets/b91a34cea662d0c523968472a81788f7#use-minikubes-built-in-docker-daemon

**Comment by tonyyang-svail** [comment]
@Yancey1989 thanks for the solution. We have enabled `eval $(minikube docker-env)` in our CI.

https://github.com/sql-machine-learning/sqlflow/blob/9af12c284414ee18eca9ce097f91d22789269805/.travis.yml#L68-L73
