### ISSUE TITLE
sqlfs/writer.go and sqlfs/hive_writer.go

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1352]
These two files contain duplicated code.  For example,

<img width="1211" alt="Screen Shot 2019-12-05 at 6 50 08 PM" src="https://user-images.githubusercontent.com/1548775/70291550-58287f80-1790-11ea-9e24-85d43415a2e7.png">

and

<img width="1207" alt="Screen Shot 2019-12-05 at 6 51 11 PM" src="https://user-images.githubusercontent.com/1548775/70291559-5c549d00-1790-11ea-844e-85ab99f0aebb.png">

This intrigues me to decompose them and reassemble the fine-grained components in a less duplicated way.

It seems that both of them have a Write method. And both Write methods accumulate an internal buffer, until overflow, then flushes.  However, `Writer.flush` writes the buffer to a SQL table as a new row/cell; whereas `HIveWriter.flush` writes the buffer into a CSV file as a new row/cell.

This observation inspired me to have a flushWriter type, which takes a function flush in its constructor.  Then, we can replace Writer by flushWriter with a flush-to-table function, and replace HiveWriter by flushWriter with a flush-to-CSV-file function.

The Close method of flushWriter calls the flush function, and then, optionally a postprocessing function.  For Writer, the postprocessor does nothing; for HiveWriter, it uploads the CSV file to HDFS.

**Comment by Yancey0623** [comment]
> This observation inspired me to have a flushWriter type, which takes a function flush in its constructor. 

I believe that's a good idea, It can reduce much code!
