### ISSUE TITLE
An bug reported when the objective="binary:logistic" in xgboost

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1380]
When using xgboost for binary classification, set in the with parameter: when objective is "binary: logistic", an error will be reported as following:
![image](https://user-images.githubusercontent.com/24820352/70519454-ea58cb00-1b76-11ea-8ac0-63657ede14ae.png)

**Comment by tonyyang-svail** [comment]
Hi @Echo9573, could you also post the example SQL so that we can try to reproduce it?

**Comment by Echo9573** [comment]
Hi @tonyyang-svail , you can reproduce this in this way:
![image](https://user-images.githubusercontent.com/24820352/71430684-40497900-2708-11ea-8f4e-1953ad8ec741.png)

**Comment by tonyyang-svail** [comment]
Ah, it should be "binary" instead of "binaray". :)

I will add a field checker that produces more meaningful messages on errors like this.
