### ISSUE TITLE
Rename pacakge tpp into parser

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1386]
I know tpp shorts for third-party parser; however, it is not a commonly known abbreviation and we need a renaming.

It looks to me that this directory can hold the clients to call third-party parsers, and, more than that, it can contain the `sql/parse.go` as well.  In this way, this directory doesn't have to be named `third-party-parsers`, but could be `parsers`.

Currently, there are two source files in this directory:

- `parser.go`, which contins the definitions of `tiDBParseAndSplit` and `javaParseAndSplit`. We could split these definitions into two files: `tidb_parser.go` and `java_parser.go`.
- `tpp.go`, which contains `ParseAndSplit` that calls either `tiDBParseAndSplit` or `javaParseAndSplit` depending on parameter `driver`. It seems that we could rename it into `third_party_parser.go`.

After the above changes, we can bring `sql/parser.go` into the directory `sql/parser`.

**Comment by tonyyang-svail** [comment]
> After the above changes, we can bring sql/parser.go into the directory sql/parser.

If we move `sql/parse.go` to directory `sql/parser`, we need to export `statementParseResult` and `extendedSelect` since there are used by `sql/parse.go::parse`.
