### ISSUE TITLE
Incorrect evaluation results when training model.

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1397]
Default metrics evaluation results are incorrect when using tf.estimator.DNNClassifer for binary classification prediction.
I have reproduced this problem on the iris dataset，is shown in the following zip file.
[iris-dnn.html.zip](https://github.com/sql-machine-learning/sqlflow/files/3950119/iris-dnn.html.zip)

**Comment by Yancey0623** [comment]
Hi @Echo9573 , thanks for your issue, I will try to reproduce it on my laptop.
