### ISSUE TITLE
A bug reported "runQuery failed: Error 1046: No database selected".

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1406]
There is a bug reported during my test which is shown as follows:
![image](https://user-images.githubusercontent.com/24820352/70698354-413edb80-1d02-11ea-8b51-19e786a30952.png)
![image](https://user-images.githubusercontent.com/24820352/70698383-53b91500-1d02-11ea-9207-a32dcca800a3.png)

**Comment by Yancey0623** [comment]
Hi @Echo9573 , please avoid using the `USE` statement because SQLFlow does not save the context between two Notebook Cells. A feasible and temporary way is to reset the default database by 
``` bash
env SQLFLOW_DATASOURCE="mysql://root:root@tcp(127.0.0.1:3306)/iris?maxAllowedPacket=0"
```
and then execute `show tables` in the Cell.

**Comment by Yancey0623** [comment]
![image](https://user-images.githubusercontent.com/1426912/71431541-658cb600-270d-11ea-8d70-261e65c50daa.png)

**Comment by Yancey0623** [comment]
Another way is that type in the following code in a Cell:

``` text
%%sqlflow
use iris;
show tables;
```

but the returned message is invalid,  I think it's a bug:

```text
0 row affected
```

**Comment by tonyyang-svail** [comment]
Hi @Echo9573 , as discussed #1562, SQLFlow doesn't preserve states across statements, meaning that `use iris;` won't affect `show tables;`. One workaround is expressing the purpose in one statement like
```sql
SHOW TABLES FROM iris;
```
