### ISSUE TITLE
FetchResponse maybe not need Phase field

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#1410]
https://github.com/sql-machine-learning/sqlflow/blob/91dd4d09a59c95f78df0473866af2d4979cafee2/pkg/proto/sqlflow.proto#L60-L75

It seems when `no_more_log==true`, the job is completed by sure, so maybe we don't need to return `Phase` to the client?

and the client code may looks like:
```
job = c.run(request).job
token = fetch_token(job=job)
while True:
    r = c.fetch(token)
    print(r.logs.content)
    if r.logs.no_more_log:
        break
    token = r.token
```

**Comment by Yancey0623** [comment]
Hi @typhoonzero  I think you're right, we don't need the Phase in the protobuf definition. Will polish the `pkg/argo` package after #1464 merged.

**Comment by Yancey0623** [comment]
the latest [sqlflow.proto](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/proto/sqlflow.proto) removed the `Phase` filed, so I closed this issue, thanks @typhoonzero .
