### ISSUE TITLE
Need design doc for pkg/argo

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1423]
I guess we are going to have two APIs to (1) submit workflows to Argo for executions, and (2) to retrieve the log by each execution ID.

But by reading the current source code, I am not sure if it is what we need.  For example, I don't understand why would we need two functions with very similar names `isCompletedPhaseWF` and `isCompletedPhasePB`. Indeed, I don't get what does it mean `WF` or `PB`.  In particular, there is a function `translatePhase` which seems translating the input type of `isCompletedPhaseWF` into that of `isCompletedPhasePB`.

Another confusion is that I'd expect `func Fetch(token pb.FetchToken) (*pb.FetchResponse, error)` to be an asynchronous operation using Goroutine and Go channels.  It doesn't. And there is a comment there saying `// FIXME(tony): no need to wait for the whole workflow`.

I think we need to follow our convention -- to write the design before the code.  Let's list the API functions we need and how they are supposed to be used.

**Comment by tonyyang-svail** [comment]
Thank @wangkuiyi for reminding writing a design doc before updating the develop branch. I will do it today.
