### ISSUE TITLE
Can we remove pkg/sql/sql_splitter.go now?

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1430]
It seems that after the introduction of the new general parser, we are no longer relying on `splitExtendedSQL`. Can we remove it?

```
$ git grep splitExtendedSQL
pkg/sql/sql_splitter.go:// splitExtendedSQL splits an extended select statement into
pkg/sql/sql_splitter.go:func splitExtendedSQL(slct string) ([]string, error) {
pkg/sql/sql_splitter_test.go:   s, err := splitExtendedSQL(`select a train b with c;`)
pkg/sql/sql_splitter_test.go:   s, err = splitExtendedSQL(`  select a predict b using c;`)
pkg/sql/sql_splitter_test.go:   s, err = splitExtendedSQL(` select a from b;`)
pkg/sql/sql_splitter_test.go:   s, err = splitExtendedSQL(`train a with b;`)
```

**Comment by wangkuiyi** [comment]
It seems that parse.go and sqlflowserver.go rely on SplitMultipleSQL defined in sql_splitter.go. I'd thought that we have changed to use the new parse to separate SQL statements in a program, haven't we?

<img width="744" alt="Screen Shot 2019-12-15 at 10 45 06 AM" src="https://user-images.githubusercontent.com/1548775/70867233-25b51a00-1f28-11ea-980b-c9282b04761f.png">

**Comment by tonyyang-svail** [comment]
You are right. We should reimplement `SplitMultipleSQL` using the third party parser and extended SQL parser.

**Comment by tonyyang-svail** [comment]
I will take a look at this issue in the next couple of days.
