### ISSUE TITLE
Rename ir.FieldMeta into ir.FieldDesc

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1432]
The name [`ir.FieldMeta`](https://github.com/sql-machine-learning/sqlflow/blob/ad20c897b4dc26a428c53065286944c50c6fd5db/pkg/sql/ir/ir.go#L43) uses the English word "meta".  According to Google Translate, meta is short for meta key, and meta key is usually the Alt key on the keyboard.

There is an English word "metadata", which, according to Wikipedia, means "data that provides information about other data".  In the field of database management systems, according to https://dataedo.com/kb/databases/all/metadata, metadata is the data schema. And the field is itself part of the data schema.

Let us rename FieldMeta into a plain name like FieldDesc or FieldDescription.

**Comment by typhoonzero** [comment]
I read about https://en.wikipedia.org/wiki/Meta  section "Epistemology",  "meta-" can be used in many cases, and I think `FieldMeta` is short for `FieldMetaData` describing the table's metadata.

**Comment by typhoonzero** [comment]
I think we can polish the comments of `FieldMeta` to describe this information?

**Comment by wangkuiyi** [comment]
Thank you for the Wikipedia link. I read it and as it tells "meta" is a prefix, but not a word, I think we'd have to name FieldMeta into FieldMetadata.

> Meta (from the Greek meta- μετά- meaning "after" or "beyond") is a prefix meaning more comprehensive or transcending.[1]

However, the fields are themselves part of the database metadata. That is why I think it would be easier to rename the Go type into FieldDesc.
