### ISSUE TITLE
Define intermediate representation sorely in protobuf

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1433]
I noticed that we have a file named [`ir_to_proto.go`](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/sql/ir/ir_to_proto.go), which converts Go types in [`ir.go`](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/sql/ir/ir.go) into protobuf messages in [`intermediate_representation`](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/proto/intermediate_representation.proto).

I think we need either `ir.go` or `intermediate_representation.proto`, but not both, right?

**Comment by typhoonzero** [comment]
@tonyyang-svail and @shendiaomo both have this question last week, and my explanation was:

1. We use `type SQLStatement interface {}` in `ir.go` currently for Polymorphism, so that we can pass the `SQLStatement` to an executor function to execute a statement of any type. Yet protobuf types do not have such a feature.
2. We use protobuf `oneof` field in many places, to use it, we may encounter many calls to get a filed like: https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/sql/ir/ir_to_proto_test.go#L49

**Comment by shendiaomo** [comment]
> I noticed that we have a file named [`ir_to_proto.go`](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/sql/ir/ir_to_proto.go), which converts Go types in [`ir.go`](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/sql/ir/ir.go) into protobuf messages in [`intermediate_representation`](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/proto/intermediate_representation.proto).
> 
> I think we need either `ir.go` or `intermediate_representation.proto`, but not both, right?

I think it's viable. For the problems mentioned by @typhoonzero , I've investigated a bit:

> 1. We use `type SQLStatement interface {}` in `ir.go` currently for Polymorphism, so that we can pass the `SQLStatement` to an executor function to execute a statement of any type. Yet protobuf types do not have such a feature.

Using a type alias like
```go
// ir.go
import "sqlflow.org/sqlflow/pkg/proto"
type TrainStmt proto.TrainStmt
```
or a struct embedding like
```go
// ir.go
import "sqlflow.org/sqlflow/pkg/proto"
type TrainStmt struct {
	proto.TrainStmt
	OriginalSQL string
}
```
makes it possible to implement the interfaces without code duplication.
> 2. We use protobuf `oneof` field in many places, to use it, we may encounter many calls to get a filed like: https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/sql/ir/ir_to_proto_test.go#L49

This is sort of nasty. What we can only do is to encapsulate these use cases into functions, e. g.
```golang
// ir.go
import "sqlflow.org/sqlflow/pkg/proto"
func(TrainStmt*) GetFieldDesc(featureColumn string, index int) *proto.FieldDesc {
	// Use a type switch to return `oneof` fields.
}
```
We have to define several such methods.

### There‘s also another possible direction
We can try using some tools to convert the original Go structs into protobuf messages, thus attain the advantages of both native structs and protobuf messages, while don't need to afford the maintenance burden of duplicated code. For example, [proteus](https://github.com/src-d/proteus) can convert the following structure:
```go
//proteus:generate
type User struct {
        Model
        Username string
}

type Model struct {
        ID int
        CreatedAt time.Time
}
``` 
into the protobuf message:
```protobuf
message User {
        int32 id = 1;
        google.protobuf.Timestamp created_at = 2;
        string username = 3;
}
```

**Comment by shendiaomo** [comment]
For more discussion see #1444
