### ISSUE TITLE
Tutorial of imdb-stackedbilstm has missed database files

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1516]
The tutorial of imdb-stackedbilstm misses the database file.
![image](https://user-images.githubusercontent.com/24820352/71350597-87225c00-25ac-11ea-83c4-9eecf29c92ef.png)

**Comment by typhoonzero** [comment]
Please checkout the tutorial: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/tutorial/imdb-stackedbilstm.md#steps-to-process-and-train-with-imdb-dataset

There is a link in this chapter refers to a Python script which will download and load the IMDB data into the database.

https://gist.github.com/typhoonzero/8ba94e204a1a0fb7a3348e7f5cc4c204
