### ISSUE TITLE
inconsistencies about shap interpretation

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1549]
During my testing, I found that in the latest image, the shap interpretation and the local interpretation show inconsistencies.
![image](https://user-images.githubusercontent.com/24820352/71468786-2ee49780-2802-11ea-8c80-f2d1a1171741.png)

`the detail  file show in this zip file:`
[housing-analyze-test-1226.html.zip](https://github.com/sql-machine-learning/sqlflow/files/4002021/housing-analyze-test-1226.html.zip)

**Comment by shendiaomo** [comment]
It seems the model is underfitting or overfitting, can you paste the result metrics?

**Comment by Echo9573** [comment]
Hi @shendiaomo , please download the zip file `housing-analyze-test-1226.html.zip`, you can see the detail reproduced process.

**Comment by shendiaomo** [comment]
I navigated the recent commit log and found out it is #1469 that caused the change. @Yancey1989 Plz check out which figure is right.

**Comment by Yancey0623** [comment]
I'll follow up this issue.
