### ISSUE TITLE
Some problem about DNN 

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1550]
When I tested the latest version of SQLFlow, I found that there are many problems with DNN prediction, as shown below：
1、When performing a binary classification task, an error is reported when the class value is 1, 2.  
and the error info is "
_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received RST_STREAM with error code 2"
	debug_error_string = "{"created":"@1577256107.434626800","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}"
>
"
![image](https://user-images.githubusercontent.com/24820352/71469052-f5605c00-2802-11ea-8af7-69c76c61d962.png)
![image](https://user-images.githubusercontent.com/24820352/71469121-22ad0a00-2803-11ea-9c39-c79d24e70242.png)

2、when In the binary classification task, when the class value is 0, 1, manually set verbose = 1, an error is reported. The error info is "
“_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received RST_STREAM with error code 2"
	debug_error_string = "{"created":"@1577351866.970226900","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}"
>”

![image](https://user-images.githubusercontent.com/24820352/71469073-08732c00-2803-11ea-8b79-e4ba17d434a9.png)

**Comment by tonyyang-svail** [comment]
Thanks for submitting this issue.

For the first point, please be aware that `model.n_classes = 2` requires the class value to be either 0 or 1. However, the class column in `select * from iris.train where class >= 1` is of value 1 or 2. So TensorFlow complains
```
...  [Labels must be <= n_classes - 1] [Condition x <= y did not hold element-wise:x (head/losses/ToFloat:0) = ] [[2]] [y (head/losses/check_label_range/Const:0) = ] [1]
```

One workaround could be manually applying minus one in the select statement.

```
select sepal_length, sepal_width, petal_length, petal_width, class - 1 as class from iris.train where class >= 1 limit 10
to train ...
```

I am not sure if SQLFlow should be applying the minus one automatically.

**Comment by tonyyang-svail** [comment]
For the second point,
```
SELECT * FROM iris.train WHERE class <= 1
TO TRAIN DNNClassifier
WITH
    model.n_classes = 2,
    model.hidden_units = [10, 10],
    train.epoch = 10,
    validation.select = 'select * from iris.test where class <= 1;'
LABEL class
INTO sqlflow_models.my_dnn_model
```

Works fine, maybe the problem is due to `train.verbose=1`.

---
Update:

Indeed, the following SQL
```
SELECT * FROM iris.train WHERE class <= 1
TO TRAIN DNNClassifier
WITH
	model.n_classes = 2,
	model.hidden_units = [10, 10],
	train.epoch = 10,
	train.verbose = 1,
	validation.select = 'select * from iris.test where class <= 1;'
LABEL class
INTO sqlflow_models.my_dnn_model;
```

Failed with 
```
File "/root/go/src/sqlflow.org/sqlflow/python/sqlflow_submitter/tensorflow/hooks.py", line 34, in before_run
    fetch = {"loss": loss_vars[0], "step": step_vars[0]}
    IndexError: list index out of range
```

This is due to https://github.com/sql-machine-learning/sqlflow/blob/254a5e6fead88854f461c4981741107ae31770a6/python/sqlflow_submitter/tensorflow/hooks.py#L28 `loss_vars` is `[]`.

**Comment by tonyyang-svail** [comment]
Hi @typhoonzero, could you please take a look at this?
