### ISSUE TITLE
Cannot switch database with `USE` command.

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#1562]
![image](https://user-images.githubusercontent.com/4180295/71519782-de4d6700-28f3-11ea-9897-775b2759bd30.png)
```bash
sqlflow> use iris;

0 row affected
+
+
sqlflow> show tables;

2019/12/27 13:56:50 runSQLProgram error: runQuery failed: Error 1046: No database selected
+
+
sqlflow>
```

This is a known problem as described in https://github.com/go-sql-driver/mysql/issues/173, we may consider to fix this using a transaction to improve user experience.

**Comment by tonyyang-svail** [comment]
Maybe it is not a good idea to support `use iris;` since it introduces states between SQL statements, while our design tends to keep the server stateless.

**Comment by Yancey0623** [comment]
Can keep the context in one sql program like:
``` sql
use iris;
show tables;
```

**Comment by tonyyang-svail** [comment]
@Yancey1989 I don't think this works. Since different SQL statements run in separate workflow steps, and separate steps are not sharing states.

**Comment by Yancey0623** [comment]
> @Yancey1989 I don't think this works. Since different SQL statements run in separate workflow steps, and separate steps are not sharing states.

@tonyyang-svail you're right, it does not work with argo mode, but works well on local mode in the all-in-one Docker image.

https://github.com/sql-machine-learning/sqlflow/blob/254a5e6fead88854f461c4981741107ae31770a6/pkg/sql/executor_ir.go#L58-L64

**Comment by Yancey0623** [comment]
Maybe **share db context between workflow steps** can be the next feature in argo mode.

**Comment by shendiaomo** [comment]
> Maybe it is not a good idea to support `use iris;` since it introduces states between SQL statements, while our design tends to keep the server stateless.

I think it doesn't have to be a state in the server, we can process this in the client, for example, we can parse the database name and pass it to every connection and workflow step. Let's see how many people need this feature before we decide whether to do it or not。
