### ISSUE TITLE
Rename env variables with prefix MAXCOMPUTE_ 

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1575]
If we search for `MAXCOMPUTE_ASK`, we would see [many environment variables](https://github.com/sql-machine-learning/sqlflow/search?q=MAXCOMPUTE_AK&unscoped_q=MAXCOMPUTE_AK), which are all for testing purpose.

To prevent users from the misunderstanding that these environment variables are for passing in MaxCompute production settings to SQLFlow, I think it should add them the prefix `SQLFLOW_TEST_DB_`.

**Comment by shendiaomo** [comment]
It seems the environment variables about MAXCOMPUTE are overused: some are for testing only while others are not.
