### ISSUE TITLE
Duplicated ir.mockTrainStmt

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1583]
https://github.com/sql-machine-learning/sqlflow/blob/f3c631e27e520310e1817300799967589a908c32/pkg/featurederivation/feature_derivation_test.go#L56

https://github.com/sql-machine-learning/sqlflow/blob/f3c631e27e520310e1817300799967589a908c32/pkg/sql/ir/mock_ir.go#L17

**Comment by tonyyang-svail** [comment]
I believe this issue has been fixed since there is only one `MockTrainStmt` in `pkg/ir/mock_ir.go`.
