### ISSUE TITLE
FeatureDerivationCaseSQLHive doesn't use INSERT INTO TABLE

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1594]
I noticed that the [FeatureDerivationCaseSQLHive](https://github.com/sql-machine-learning/sqlflow/blob/f3c631e27e520310e1817300799967589a908c32/pkg/sql/testdata/feature_derivation_case.go#L35
) SQL program uses `INSERT INTO` other than `INSERT INTO TABLE`.

https://github.com/sql-machine-learning/sqlflow/blob/f3c631e27e520310e1817300799967589a908c32/pkg/sql/testdata/feature_derivation_case.go#L45

Whereas other HiveQL programs use `INSERT INTO TABLE`.  For example

https://github.com/sql-machine-learning/sqlflow/blob/f3c631e27e520310e1817300799967589a908c32/pkg/sql/testdata/iris_sql.go#L187

https://github.com/sql-machine-learning/sqlflow/blob/f3c631e27e520310e1817300799967589a908c32/pkg/sql/testdata/iris_sql.go#L306

https://github.com/sql-machine-learning/sqlflow/blob/f3c631e27e520310e1817300799967589a908c32/pkg/sql/testdata/churn_sql.go#L188

I noticed that https://github.com/sql-machine-learning/sqlflow/pull/1247/files#diff-55c6e51a3df3139780b8d2a289b85a03R45 adds FeatureDerivationCaseSQLHive.

@typhoonzero Should we change FeatureDerivationCaseSQLHive? Or, we don't have to because of HiveQL tolerant with the lack of keyword `TABLE`?

**Comment by wangkuiyi** [comment]
I Googled around and noticed that all results I found use `INSERT INTO TABLE`.

- https://stackoverflow.com/a/31656434/724872
- https://dwgeek.com/hive-insert-from-select-statement-and-examples.html
- https://www.dummies.com/programming/big-data/hadoop/hive-insert-command-examples/

**Comment by typhoonzero** [comment]
> @typhoonzero Should we change FeatureDerivationCaseSQLHive? Or, we don't have to because of HiveQL tolerant with the lack of keyword TABLE?

I think it's better to keep all Hive SQL's all use `INSERT INTO TABLE`.

**Comment by wangkuiyi** [comment]
Done in #1595
