### ISSUE TITLE
Support write model explain values into a result table

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#1612]
The current `SELECT * from pred_table TO EXPLAIN some_model` will generate an image showing the feature importance. For cases that in a full-text terminal or distributed platform (explanation data will be generated on different nodes), we can not generate the image directly and display it. In that case, we may need to write the explanation data to a table, and use tools to display the image:

```
SELECT * from pred_table
TO EXPLAIN some_model
WITH attribute=value
USING explainer
INTO some_result_table;
```

Note that the `INTO` clause is optional, if not specified `INTO` we will try directly display the image, if `INTO` is specified, we will write the explanation data into that table.

**Comment by wangkuiyi** [comment]
I see. I think the destination doesn't have to be a table, but also could be a file, say, `/hdfs/home/user/explaination.json`. A Web browser might render the file or table content for interactive exploring.
