### ISSUE TITLE
Rename TestVerify_1 and TestVerify_2 with more meaningful names

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1617]
We have

https://github.com/sql-machine-learning/sqlflow/blob/35f5f89197e78f57d27114524f8073791f82b6d6/pkg/verifier/verifier_test.go#L25

and

https://github.com/sql-machine-learning/sqlflow/blob/35f5f89197e78f57d27114524f8073791f82b6d6/pkg/verifier/verifier_test.go#L56

@tonyyang-svail  Should we rename these test cases introduced in https://github.com/sql-machine-learning/sqlflow/pull/622 to more meaningful names?  I tried to make new names, but I don't get the meaning from the code.

**Comment by tonyyang-svail** [comment]
`TestVerify_2` is a duplication of of `TestVerify_1`. The body of the `TestVerify_1` is used to test the function `describeTable`. Since `describleTable` has been removed in #622, its test should also be removed.
