### ISSUE TITLE
Data needs to be normalized before data construction in time series models

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1643]
In the time series model, the data needs to be normalized before the data is constructed, and then the sequence is constructed. 
So that after SQLFlow training and prediction, the predicted data will also be in the range of 0 ~ 1; 
Therefore, the data cannot be mapped to the original dimension (because the mean / std of the data preprocessing is not recorded)

**Comment by typhoonzero** [comment]
Update: we discussed some solutions and agree with using SQL to pre-process the time series data to get mean/variance to do normalization on the original data, and construct time windows as the input of training:
![94BD2131-1960-4345-B20B-B7B19C0713C6](https://user-images.githubusercontent.com/13348433/72416833-84351880-37b2-11ea-9b95-d103e7ea07fe.png)
