### ISSUE TITLE
java_parser.go includes unnecessary file operations

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1663]
We don't need to create a file as the input to a Java program written by us.  The following code snippet

https://github.com/sql-machine-learning/sqlflow/blob/5e2a4cb8cf059f3f3fa46b78d24b3253c12a669a/pkg/parser/external/java_parser.go#L55-L69

can be simplified

```go
        cmd := exec.Command("java",
		"-cp", "/opt/sqlflow/parser/parser-1.0-SNAPSHOT-jar-with-dependencies.jar",
		"org.sqlflow.parser.ParserAdaptorCmd",
		"-p", p.typ,
		"-o", outputFile)
        cmd.Stdin = strings.NewReader(program)
 ```

Similarly, we can capture the output with an in-memory buffer.

```go
        var out byts.Buffer
        cmd.Stdout = &out
```

So we don't need to retrieve the output from a file; instead, we can change the Java program to print the JSON to its stdout.

**Comment by wangkuiyi** [comment]
I just note a possible improvement by using Go standard libraries in the idiom way. Anyway, as explained in https://github.com/sql-machine-learning/sqlflow/issues/1389, it is too expensive to start a Java process for each SQL program we are going to parse.  We should change the Java program into a gRPC server.

**Comment by tonyyang-svail** [comment]
For the record, I haven't found a way to turn off the log message of the Java parser and the log message will pollute the stdout. So I use a file to store the output.

Sure, I will change the Java program into a gPRC server.

**Comment by tonyyang-svail** [comment]
All Java parsers are now called through a gRPC interface. So this issue no longer exists.
