### ISSUE TITLE
Notes about trying out using antlr to generate full go code parsers

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#1669]
Currently, MySQL, Hive, MaxCompute grammar files written in `g4` format (antlr) are available already, and antlr supports generate Go code. We may have a better solution if we can generate Go parsers using antlr.

Using antlr with Go: https://github.com/antlr/antlr4/blob/master/doc/go-target.md. I write tests to test out the parser according to this tutorial.

1. MySQL grammar: https://github.com/antlr/grammars-v4/tree/master/mysql/Positive-Technologies
    1. generating Go code without error (one warning)
    1. will raise error when compiling: `_lt redeclared ...` , simple modify the generated Go file to avoid variable redeclare, then it will compile and run.
    1. seems the identifier only accept quoted string like `SELECT * FROM `db.table`;` can be parsed
1. MySQL grammar: https://github.com/mysql/mysql-workbench/tree/8.0/library/parsers/grammars
    1. it's used by MySQL Workbench and have full language definition. It can be used to generate C++ parser only.
    1. `symbol type conflicts with generated code in target language or runtime` error will raise when generating Go code. Need to rename `type` to `r_type` in the `g4` file.
    1. generated code need to import a C++ file https://github.com/mysql/mysql-workbench/blob/8.0/library/parsers/mysql/MySQLBaseLexer.h to define `MySQLBaseLexer`. It's possible to rewrite it in Go so that we can make this parser work.
1. Hive(TBD): https://github.com/apache/hive/blob/master/hplsql/src/main/antlr4/org/apache/hive/hplsql/Hplsql.g4

**Comment by tonyyang-svail** [comment]
I have tried to generate MaxCompute parser in Go but failed. And I am writing down the obstacles along the way.

First, the MaxCompute grammar file uses symbol names that are reserved for Go, such as `range`, `var` and `len`, which will cause the following error. This error may be avoided by renaming the symbol.

```
...
OdpsParser.g4:2397:1: symbol range conflicts with generated code in target language or runtime
OdpsParser.g4:416:20: symbol len conflicts with generated code in target language or runtime
```

Second, the MaxCompute grammar file embedded some Java only type like `boolean`. To be specific, one line is written as `alterStatementSuffixAddPartitions[boolean table]`. This Java specific definition will cause the following error when compiling to Go. This error may be avoided by renaming `boolean` to `bool`, which is the type name in Go.

```
...
./odps_parser.go:53055:13: undefined: boolean
./odps_parser.go:53058:11: undefined: boolean
```

After using the workaround mentioned above, I was able to generate the Go code using `antlr4` command line. However, the generated Go code failed to compile. The error message is the following.

```
./odps_parser.go:5287:6: NewEmptyStatementContext redeclared in this block
	previous declaration at ./odps_parser.go:4855:34
./odps_parser.go:25201:6: NewExpressionContext redeclared in this block
	previous declaration at ./odps_parser.go:17132:6
./odps_parser.go:60970:6: method redeclared: ShowStatementContext.Identifier
	method(*ShowStatementContext) func() IIdentifierContext
	method(*ShowStatementContext) func() antlr.TerminalNode
./odps_parser.go:60970:32: (*ShowStatementContext).Identifier redeclared in this block
	previous declaration at ./odps_parser.go:60878:6
./odps_parser.go:61051:6: method redeclared: ShowStatementContext.StringLiteral
	method(*ShowStatementContext) func() antlr.TerminalNode
	method(*ShowStatementContext) func() IStringLiteralContext
./odps_parser.go:61051:32: (*ShowStatementContext).StringLiteral redeclared in this block
	previous declaration at ./odps_parser.go:60954:6
./odps_parser.go:70262:6: method redeclared: TableFileFormatContext.AllStringLiteral
	method(*TableFileFormatContext) func() []IStringLiteralContext
	method(*TableFileFormatContext) func() []antlr.TerminalNode
./odps_parser.go:70262:34: (*TableFileFormatContext).AllStringLiteral redeclared in this block
	previous declaration at ./odps_parser.go:70231:6
./odps_parser.go:70266:6: method redeclared: TableFileFormatContext.StringLiteral
	method(*TableFileFormatContext) func(int) IStringLiteralContext
	method(*TableFileFormatContext) func(int) antlr.TerminalNode
./odps_parser.go:70266:34: (*TableFileFormatContext).StringLiteral redeclared in this block
	previous declaration at ./odps_parser.go:70244:6
./odps_parser.go:70266:34: too many errors
```

ANTLR4 is mainly used for Java code generation. And in Java, we can define functions with the same name as long as their signatures are different. However, this is not the case for Go. I haven't found a workaround for this. The closest discussion thread is [this](https://github.com/antlr/antlr4/issues/1610), while it appears to be inactive.

**Comment by typhoonzero** [comment]
When the grammar file embeds Java code ( or some cases C++ code ), it's hard to generate the parser directly, we have to port those code into Go, and this will take a lot of time and effort.

**Comment by tonyyang-svail** [comment]
I am closing this issue since @typhoonzero and I have concluded that generating Go code parsers from ANTLR4 file requires a considerable amount of effort and is not worth trying.
