### ISSUE TITLE
Support omitting USING clause in explain statements

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#1695]
Generally, we can deduce the explainer type from the models, that is, the USING clause is not necessary in most cases.

**Comment by wangkuiyi** [comment]
Agreed.

The current grammar of the EXPLAIN clause is 

https://github.com/sql-machine-learning/sqlflow/blob/82e005e5259fca704fb4e04b3d38177177b73e29/pkg/parser/extended_syntax_parser.y#L216-L221

If we can remove the `USING explainer` clause easily, hopefully, the users could write less code.
