### ISSUE TITLE
[Need Discuss] Support simple functions on LABEL clause

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#1715]
Background: https://github.com/sql-machine-learning/sqlflow/issues/1643

We may have multiple target columns when training:

![20200115163720](https://user-images.githubusercontent.com/13348433/72418187-53a2ae00-37b5-11ea-825e-3c66217b2c24.jpg)

The task is to use `X1,X2,X3` to predict `Y1,Y2`.

The column `Y1` and `Y2` will be concatenated to a Tensor of shape [batch_size, 2] (note that typical classification jobs, the label is of shape [batchsize, 1] ). And the input features is of shape [batch_size, time_window_size, feature_size].

We can use the below approaches to achieve this:

1. write a concatenated CSV value in a single `Y` column using pure SQL before training.
1. use `LABEL CONCAT(Y1,Y2)` to do simple label transformations.

Note we don't use `LABEL Y1, Y2` since we might need to support cases using multiple training targets: https://towardsdatascience.com/regression-models-with-multiple-target-variables-8baa75aacd

**Comment by shendiaomo** [comment]
How about taking
```sql
SELECT X1, X2, X3, concat(Y1, Y2) as class TO TRAIN ...
```
as the recommended way to do this?

**Comment by typhoonzero** [comment]
@shendiaomo that's it. Yet we don't support using a CSV value as the label yet, need to implement, and add test case about this.

And, the statement for mysql should be like: `SELECT X1, X2, X3, concat(Y1, ",", Y2) as class TO TRAIN ...`
