### ISSUE TITLE
SQL Expression 'DESC {table_name}' executes failed in MaxCompute.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/sqlflow#1735]
**Description**
Execute describe expression in MaxCompute
`DESC table_xxx`, execution failed.

**Reproduction Steps**

**Expected Behavior**
The table schema is returned in the log.

**Screenshots**

**Environment (Please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional Notes**

**Comment by tonyyang-svail** [comment]
`DESC table_xxx` has been supported, so I am closing this issue.
