### ISSUE TITLE
Proposal: Add new binary cmd/step

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1746]
SQLFlow needs the capability of translating and executing each SQL statement, with or without the extending syntax.  This capability makes the Argo/Tekton workflow tracable; it also makes it possible to integrate SQLFlow with IDEs like Visual Studio Code to support step-by-step running.

Currently, we rely on the binary `cmd/repl` as the step runner.  However, `cmd/repl` also has other roles like a local debug mode of SQLFlow and runs a SQL program instead of a SQL statement.

I agree that we keep `cmd/repl` as a SQLFlow server client, just like the Jupyter Notebook client.  But to make its role as a client clear, we need a new tool to run each step in the Argo/Tekton workflow.

**Comment by Yancey0623** [comment]
Sorry for replying on this issue late, I agree with the new binary `cmd/step`, which can make the role of `step` and `repl` to be clearer. I think the input of `step` should be one SQL statement and call code generator to generate a submitter program to execute, am I right?

I will do this cleanup recently. Future more, we can continue to refactor `pkg/step` package to make the code more clearly according to #1585 .
