### ISSUE TITLE
Package codegen/couler does Argo related work

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1747]
By the name, the package `codgen/couler` should generate the Couler program.  However, it generates the Argo YAML file:

https://github.com/sql-machine-learning/sqlflow/blob/5ab490f740decbb8c3f293461c7920d5ef2f8979/pkg/sql/codegen/couler/codegen.go#L164

This doesn't make sense -- if we want a Argo codegen, it should be named `codegen/argo` instead of `codegen/couler`.

In particular, as we have a package named [`argo`](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/argo/), which, by the name, should be the one doing Argo related work.

**Comment by Yancey0623** [comment]
Maybe we can separate **generate Couler Program** and **Compile Couler Program** into two functions, that the snippet code would be like:

``` golang
func submitWorkflow() {
    coulerProgram, err := couler.Run(ir)
    argoYAML, err := couler.Compile(coulerProgram)
    return workflow.Submit(argoYAML)
}
```
