### ISSUE TITLE
column news_title is csv format sparse tensor, but got DENSE column or not specified

### ISSUE THREAD

**Issue by etjay** [sql-machine-learning/sqlflow#1753]
**Description**
run "Steps to Run Chinese Text Classification Dataset"  demo 
the step to train got this exception.

**Reproduction Steps**
every steps follow the  
https://sql-machine-learning.github.io/sqlflow/doc/tutorial/imdb-stackedbilstm/
"Steps to Run Chinese Text Classification Dataset" part.

**Expected Behavior**
"column news_title is csv format sparse tensor, but got DENSE column or not specified"

**Environment (Please complete the following information):**
 - OS:mac 10.14.6
 - Browser:chrome 
 - Version:79.0.3945.117
sqlflow/sqlflow        latest              595ea1294fd2        6 hours ago         5.21GB

**Additional Notes**

**Comment by typhoonzero** [comment]
Thanks for reporting this issue.

We have supported feature derivation and the documentation is not updated accordingly. You may try the below SQL statement:

```
%%sqlflow
    SELECT content, class FROM imdb.train
    TO TRAIN DNNClassifier
    WITH
    model.n_classes = 2,
    model.hidden_units = [128, 64]
    LABEL class
    INTO sqlflow_models.my_text_model_en;
```

Or

```sql
%%sqlflow
    SELECT content, class
    FROM imdb.train limit 100
    TO TRAIN sqlflow_models.StackedBiLSTMClassifier
    WITH
    model.n_classes = 2,
    model.stack_units = [64,32],
    model.hidden_size = 64,
    train.epoch = 10,
    train.batch_size = 64
    column EMBEDDING(SEQ_CATEGORY_ID(content, 16000), 128, sum)
    LABEL class
    INTO sqlflow_models.my_custom_model;
```
