### ISSUE TITLE
SQLFlow doesn't support comments without semicolon;

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#1757]
![image](https://user-images.githubusercontent.com/4180295/72682778-d015f380-3b0b-11ea-9b3f-dd8f5951ce83.png)
If we delete the `;`, REPL will concatenate the two lines.

**Comment by tonyyang-svail** [comment]
For the record, SQLFlow's extended syntax parser hasn't support `--` comment yet.
