### ISSUE TITLE
Minor code duplication

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1774]
Is 

https://github.com/sql-machine-learning/sqlflow/blob/796ee680007434a90d1cd5eb71465aef64439ee2/pkg/sql/codegen/couler/codegen.go#L44

duplicated with

https://github.com/sql-machine-learning/sqlflow/blob/796ee680007434a90d1cd5eb71465aef64439ee2/pkg/sql/codegen/couler/codegen.go#L59-L61

**Comment by Yancey0623** [comment]
May not, We can specify `SQLFLOW_submitter` can comes from the environment of `sqlflowserver` or  `pb.Session`, the second has a higher priority, I will add some comment here to explain it.

**Comment by wangkuiyi** [comment]
I see. I think it is alright.
