### ISSUE TITLE
The fraud detection notebook doesn't run

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1784]
The first SELECT * LIMIT 5 statement runs. But the rest statements with SQLFlow syntax extensions do not run. As shown in the following figure.

![捕获](https://user-images.githubusercontent.com/1548775/73130175-0dfd9680-3fa8-11ea-96a0-9bc944902698.PNG)

To reporduce this problem:

1. Follow the Quick Start guide in Windows to start a container.
1. Open a Chrome and direct to localhost:8888. This opens the list of notebooks. Select the fraud detection example.
1. Run cells one-by-one. The first runs and prints some sample data. The rest don't give any response.

Please be aware that I can run the Housing Explain example http://localhost:8888/notebooks/housing-explain.ipynb

**Comment by typhoonzero** [comment]
The mark `[*]` on the left of the SQL statements block means this block is currently still running. And, `[1]` means the first execution is completed. You may need to wait until the execution is finished.
