### ISSUE TITLE
Support validation.metrics in xgboost

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1801]
Suggest to support `validation.metrics` in xgboost model.
![image](https://user-images.githubusercontent.com/24820352/73711585-4fc5d400-4742-11ea-88df-21e08cfcde93.png)

**Comment by tonyyang-svail** [comment]
Hi @Echo9573, we have just supported the eval metrics for XGBoost. You can find the example at

https://github.com/sql-machine-learning/sqlflow/blob/a033b42926e4d0ccf63c044e414aa99eb9dfcfaf/cmd/sqlflowserver/main_test.go#L383-L386
