### ISSUE TITLE
Predicting is rather slow

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#1813]
```sql
SELECT * FROM titanic.train TO TRAIN DNNClassifier 
  WITH model.hidden_units=[200, 200，200],optimizer.learning_rate=0.01
  LABEL survived
  INTO sqlflow_models.titanic_model;
```
```sql
SELECT * FROM titanic.test TO PREDICT titanic.predict.survived 
  USING sqlflow_models.titanic_model;
```
On my MacBook Pro, The `PREDICT` statement spent about ten minutes, which is too slow because there're only 418 samples in the `titanic.test` dataset.

**Comment by typhoonzero** [comment]
The former `FastPredict` class is resolving this issue, yet previous fix https://github.com/sql-machine-learning/sqlflow/pull/1504 may changed it back which will cause loading the model every time when run `estimator.predict()`
