### ISSUE TITLE
More straight forward XGBoost API

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1829]
Instead of writting

``` sql
SELECT * FROM titanic.train
TO TRAIN xgboost.gbtree 
WITH objective="binary:logistic"
LABEL survived
INTO sqlflow_models.my_xgboost_model;
```

the following naming might be more straight forward
``` sql
SELECT * FROM titanic.train
TO TRAIN XGBOOST.BINARYCLASSIFIER
LABEL survived
INTO sqlflow_models.my_xgboost_model;
```

I feel `XGBOOST.BINARYCLASSIFIER` is a good fit for the first SQLFlow statement since it doesn't have the WITH clause. @llxxxll What do you think?

credit: This definition is original proposed by @sperlingxx at https://github.com/sql-machine-learning/sqlflow/blob/4f08b7cb8fc88269c8d0066cca8992a0b4658f7f/sql/codegen_ant_xgboost.go#L575

**Comment by shendiaomo** [comment]
Agreed. I have the same idea.
Moreover, the `xgboost.BinaryClassifier` and other python classes have a compatible interface with `tensorflow.Estimator`s

**Comment by llxxxll** [comment]
Explaining `hidden_units` to the user is not an easy thing to do, and without these parameters `model.n_classes = 3,model.hidden_units = [10, 10]`, the experience would be very good.
