### ISSUE TITLE
LSTMBasedTimeSeries model results on local and SQLFLow are inconsistent.

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1854]
LSTMBasedTimeSeries model results on local and SQLFLow are inconsistent. The  visualization of the predicted result is shown as follows:
** SQLFLow **
`Note`: The blue line is the y_true, the red line is the y_predict 
![image](https://user-images.githubusercontent.com/24820352/74501143-28ca8780-4f24-11ea-9532-afee3f70029d.png)

** Local **
`Note`: The blue line is the y_true, the red line is the y_predict 
![image](https://user-images.githubusercontent.com/24820352/74501168-3b44c100-4f24-11ea-9741-c75c65f32f12.png)

The  detail procedure of reproducing can see the file:

[LSTMBasedTS_compare_local&sqlflow.zip](https://github.com/sql-machine-learning/sqlflow/files/4202640/LSTMBasedTS_compare_local.sqlflow.zip)

**Comment by typhoonzero** [comment]
The cause was we need to set the same `model.stack_units = [500,500]` in both cases.
