### ISSUE TITLE
Add test on cmd.go

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#189]
When `cmd.Run()` starts a TF job inside a container, I suspect it won't return an error even if the job fails.

**Comment by wangkuiyi** [comment]
I suppose you observed something that made you this suspicion? If the TensorFlow program fails by invoking `exit(a_non_zero_value)`, I am pretty sure that `cmd.Run` would notice the failure.

**Comment by tonyyang-svail** [comment]
You are right; I am not able to reproduce the error.
