### ISSUE TITLE
Incorrect validation result of DNNclassifier

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1899]
The validation result of DNNclassifier is incorrect, is shown as follows:

1. When do not set the validation.select, the result accuracy is equal to 0.
![image](https://user-images.githubusercontent.com/24820352/75236874-69b27e00-57f9-11ea-99f0-a47af7235f02.png)

2. When setting the validation.select, the result of all validation function is equal to 0.
![image](https://user-images.githubusercontent.com/24820352/75237043-ac745600-57f9-11ea-9e37-eb73417b5ecc.png)

**Comment by Echo9573** [comment]
After talked with @typhoonzero , 
For 1, after altering the `accuracy` to  `BinaryAccuracy`. Then, the output is correct:
![image](https://user-images.githubusercontent.com/24820352/75253374-60d1a480-5819-11ea-9739-3ae631a09f92.png)
For 2, after altering the `accuracy` to  `BinaryAccuracy` and setting the validation.select, the result of `Precision Recall AUC` is equal to 0.0 ：
![image](https://user-images.githubusercontent.com/24820352/75253925-6da2c800-581a-11ea-8c87-e906f0464baf.png)

**Comment by typhoonzero** [comment]
![image](https://user-images.githubusercontent.com/13348433/75315149-db8fd380-589c-11ea-90ef-e07f791c8bf9.png)

Seems this is related to the validation data, when using part of the training data to do validation, the AUC metric can be correctly displayed.
