### ISSUE TITLE
thirdPartyParse failed: Encountered "time FROM"

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#1934]
**Description**
Encounter error `thirdPartyParse failed` running SQL likes: `SELECT time FROM {SOME_TABLE} LIMIT 1;`

Error:
```
UNKNOWN: thirdPartyParse failed: Encountered "time FROM" at line 1, column 8.
Was expecting one of:
    "UNION" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    "ORDER" ...
    "LIMIT" ...
    "OFFSET" ...
```

**Comment by tonyyang-svail** [comment]
Hi @weiguoz, thanks for submitting this issue. This issue will go away once we switch to ODPS parser in the internal repo.
