### ISSUE TITLE
Proposal: Add logs for tracking SQL job

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#1962]
Currently, we don't have enough logs to track the SQL job lifecycle, including:
- duration of each step
- the exception of a Job

Besides, we often need a statistics component to count the number of `train/predict/explain` tasks over a period of time. Generally, most of such statistics components are implemented through logs.

So, I propose to add more logs (categories and content) to enable such component work.

**Comment by tonyyang-svail** [comment]
Hi @weiguoz, could you please provide some implementation details on this proposal? For example
1. The choice of logging to a file or stdout. [ref](https://12factor.net/logs)
1. A list of information that we would like to log.
1. The choice of the logging format.
1. The method of parsing the logging format.
1. The choice of logging library ([log](https://golang.org/pkg/log), [glog](https://github.com/golang/glog), or [logrus](https://github.com/sirupsen/logrus)).

Some useful tutorial: https://www.scalyr.com/blog/getting-started-quickly-with-go-logging

**Comment by weiguoz** [comment]
I close this issue because of the [design](https://github.com/sql-machine-learning/sqlflow/pull/1972) has been implemented.
