### ISSUE TITLE
Bad substitution error on SQL statement contains ${}

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1966]
**Description**
If a SQL statement contains `${}`, for example
```
-- ${internal.config}
select 1;
```
In the workflow mode, the job will fail with the following error
```
bash: -- ${internal.config}
select 1;: bad substitution
```

**Reproduction Steps**
Execute the above example.

**Root Cause**
The workflow YAML produced by this SQL is 
```
container:
  command:
    - bash
    - '-c'
    - "repl -e \"-- ${internal.config}\nselect 1;\" "
```
And the workflow consider this as
```
bash -c repl -e "-- ${internal.config} select 1;"
```
So the bash command in the container tries to substitute `${internal.config}`. However, according to the bash man page
```
   name   A  word  consisting  only  of alphanumeric characters and under‐
          scores, and beginning with an alphabetic character or an  under‐
          score.  Also referred to as an identifier.
```
So the name `internal.config` with dot is illegal, then `bash` raises `bad substitution error`. [ref](https://unix.stackexchange.com/a/93533).

**Comment by weiguoz** [comment]
Does the `repl` need to do substituting?
If not, shall we change `"` to `'`(a single-quote)?

///
update:
```bash
~ ➜ bash -c 'echo ${a.b}' 
bash: ${a.b}: bad substitution
```
It looks like the single-quote does not fix the problem. Let's find another way out.

**Comment by Yancey0623** [comment]
Thanks @tonyyang-svail 's exhaustive analyze, it seems that **dot** is not the bash standard:
``` bash
➜  sqlflow (develop) ✗ bash -c "echo ${internal}"
➜  sqlflow (develop) ✗ bash -c "echo ${internal.aa}"
zsh: bad substitution
```

 how about update the workflow: remove `bash -c` ?

**Comment by shendiaomo** [comment]
> Thanks @tonyyang-svail 's exhaustive analyze, it seems that **dot** is not the bash standard:
> 
> ```shell
> ➜  sqlflow (develop) ✗ bash -c "echo ${internal}"
> ➜  sqlflow (develop) ✗ bash -c "echo ${internal.aa}"
> zsh: bad substitution
> ```
> 
> how about update the workflow: remove `bash -c` ?

Agreed. `repl` is a standalone program.
