### ISSUE TITLE
Should we remove scripts/teamcity_statistics.py ?

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#2007]
`git grep` reveals that it is not referred to in the repo.

**Comment by shendiaomo** [comment]
> `git grep` reveals that it is not referred to in the repo.

I think it's used in our internal codebase and can be moved there.

**Comment by Yancey0623** [comment]
It's used on the internal TeamCity CI, I will move it to the internal repo and then delete it from Github.
