### ISSUE TITLE
Explaining scripts/docker/js/custom.js and sqlflow.js

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#2008]
I am not an expert of customizing Jupyter Notebook. I `git-grep`ed the repo but found no clue who is calling custom.js and sqlflow.js.

Google show me https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/JavaScript%20Notebook%20Extensions.html#custom.js, which tells that custom.js is like a configuration file of Jupyter Notebook.  I am wondering should we add this URL to the file comment of custom.js.

Still, I have no idea how does sqfllow.js works?

**Comment by shendiaomo** [comment]
The `custom.js` and `sqlflow.js` is necessary to highlight SQL and SQLFlow keywords in ``%%sqlflow`` cells.
They're copied to the home directory and the `codemirror` directory of Jupyter in the Docker image to take effect.
See https://github.com/sql-machine-learning/sqlflow/pull/1470/ for details.
