### ISSUE TITLE
Allow users to query model meta information

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#2049]
**Is your feature request related to a problem? Please describe.**
There's no good method for a user to know how a model is trained. If a user is tuning an application and train several models, it's hard for her to remember those hyperparameters.
**Describe the solution you'd like**
Support something like `DESCRIBE table1` or `SHOW CREATE TABLE table1`. For example:
```sql
SHOW TRAIN iris.dnn;
```
SQLFlow can output the original training statement as 
```
+--------+-------------------------------------+-------------------------------------+
| Model  | TO TRAIN                            | stdout                              |
+--------+-------------------------------------+-------------------------------------+
|iris.dnn| SELECT * FROM iris.train            |=== Result for training set: ======  |
|        | TO TRAIN DNNCLASSIFIER WITH         | loss: 0.850680483341217             |
|        |     ......                          | accuracy: 0.73256                   |
|        | INTO iris.dnn;                      |......                               |
+--------+-------------------------------------+-------------------------------------+
```
**Describe alternatives (optional)**
Require the users to hand-coding the hyperparameters in the model name.
**Additional Notes**
This was one of the original design details of the Model Zoo.

**Comment by typhoonzero** [comment]
Is it used to get hyperparameters or get the training log? From the example above it seems it's getting the training log.
