### ISSUE TITLE
Add auto completion for xgboost's objective parameter

### ISSUE THREAD

**Issue by lhw362950217** [sql-machine-learning/sqlflow#2059]
**Is your feature request related to a problem? Please describe.**
I would appreciate if there is some kind of auto completion for xgboost's objective param, for it has too many options.

**Describe the solution you'd like**
<img width="703" alt="6F666910-8CBF-43A4-AA03-3D7E43E38A06" src="https://user-images.githubusercontent.com/5652016/77619402-186de980-6f73-11ea-99b2-65bb7052a3bf.png">

**Describe alternatives (optional)**
 refer to xgboost doc at https://xgboost.readthedocs.io/en/latest/parameter.html

**Additional Notes**

**Comment by shendiaomo** [comment]
The order of objectives is random, please fix this. 
A similar problem is fixed in https://github.com/sql-machine-learning/sqlflow/pull/1835
