### ISSUE TITLE
梳理 SQLFlow 官网文档

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#2090]
# 背景

1. sqlflow.org 缺少中文文档
2. 例子中没有侧重对场景的描述
3. Quick Start 不完善，用户无法按照 quick start 中的指引将 SQLFlow 跑起来。

这个 issue 尝试对文档结构重新梳理，以下是提纲，欢迎讨论：

# 提纲
1. 快速开始：描述用户如何使用 Docker 在本地使用 SQLFlow，包括 Jupyter 的使用截图等，文末包括指向“更多应用场景“
    1. 泰坦尼克号生存预测
    1. 信用卡欺诈检测
    1. 点击率预估
    1. 汽车价格预测及模型解释
1. 语法说明
    1. 训练
    1. 预测
    1. 可解释
1. 模型说明
    1. 有监督学习
        1. Tensorflow Estimator 模型
        1. Tensorflow Keras 模型
        1. XGBoost 模型
    1. 无监督模型
1. 部署
    1. Docker 部署
    1. K8s 部署
    1. Google Cloud 部署

## 原则
1. 先实现中文，再翻译成英文
1. 场景案例中简化数据清洗过程，重点描述模型输入的 column 字段类型

**Comment by typhoonzero** [comment]
可解释 -》 模型解释

模型说明-》模型手册

4. 部署
    1. 独立模式
    2. 工作流模式

**Comment by Echo9573** [comment]
“2、语法说明”是否可以考虑放在“3、模型说明”中？因为每个模型都有自己对应的语法WITH里面可选的参数不同。建议可以在“3、模型说明”也提到每个模型的可选参数，及常用调节参数等。

**Comment by llxxxll** [comment]
> “2、语法说明”是否可以考虑放在“3、模型说明”中？因为每个模型都有自己对应的语法WITH里面可选的参数不同。建议可以在“3、模型说明”也提到每个模型的可选参数，及常用调节参数等。

这里的语法说明应该是指 `TO TRAIN`、`TO PREDICT` 这样的SQLFlow 扩展语法，介绍`WITH`的时候提及参数和模型强关系，是否可行。

**Comment by llxxxll** [comment]
"快速开始"应由易到难，按照我们现有的例子，尝试重新排序如下：

- 泰坦尼克号生存预测
- 信用卡欺诈检测
- 汽车价格预测及模型解释
- 点击率预估

**Comment by weiguoz** [comment]
> 可解释 -》 模型解释
> 
> 模型说明-》模型手册
> 
> 1. 部署
>    
>    1. 独立模式
>    2. 工作流模式

赞同部署的这两种划分。
从含义上看，把“独立模式”改成“单机模式”是不是更明确？
