### ISSUE TITLE
The clahub checker is failing

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#2117]
**Description**
![image](https://user-images.githubusercontent.com/4180295/79332800-0834a300-7f50-11ea-8ef9-486386e5a36a.png)
All pull requests today stuck here.

**Comment by wangkuiyi** [comment]
https://www.clahub.com/  seems down.

**Comment by wangkuiyi** [comment]
Disabled CLAHub.com
