### ISSUE TITLE
when contribute model test, get error: NameError: name '***' is not defined

### ISSUE THREAD

**Issue by wangyinlong** [sql-machine-learning/sqlflow#2162]
I‘m testing distribute model to sqlflow in the docker on my mac, but I have some problem as follows.

![image](https://user-images.githubusercontent.com/5877234/80369762-61da8d00-88c1-11ea-9883-dcc472167afa.png)

but i get the following error

![image](https://user-images.githubusercontent.com/5877234/80369811-76b72080-88c1-11ea-8cae-967804456adb.png)

**Comment by typhoonzero** [comment]
Thanks for submitting this issue.

Are you following this document https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/contribute_models.md ? And, where did you put the python file containing `DNNClassifierNew`?

**Comment by wangyinlong** [comment]
> Thanks for submitting this issue.
> 
> Are you following this document https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/contribute_models.md ? And, where did you put the python file containing `DNNClassifierNew`?

Yes, I following the document https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/contribute_models.md 

I put the python file containing DNNClassifierNew on my own mac, and run docker like 
`docker run -p 8888:8888 -v $PWD/my_model_collection:/workspace/my_model_collection  sqlflow/sqlflow bash -c 'export PYTHONPATH=/workspace:$PYTHONPATH; bash /start.sh`

my own model file is copied into docker workspace as follow
![image](https://user-images.githubusercontent.com/5877234/80455647-c0a21400-895e-11ea-90f9-92efe2e40efe.png)

then I open my browser localhost:8888 and execute train magic sql and have the error above.

did i miss some step to setup my own model into somewhere or I put my model into the wrong places? pls help me ,thx :)

**Comment by typhoonzero** [comment]
I see. Seems like in SQLFlow we need to try import custom model names like:

```sql
SELECT * FROM iris.train TO TRAIN my_model_collection.DNNClassifierNew ...
```

where the Python package `my_model_collection` should be under the `PYTHONPATH`. Currently  the new model should work if you rename the folder to `sqlflow_models` and do the same, then use the statement: `SELECT * FROM iris.train TO TRAIN sqlflow_models.DNNClassifierNew ...`

I'll fix this in my next PR.

**Comment by wangyinlong** [comment]
> I see. Seems like in SQLFlow we need to try import custom model names like:
> 
> ```sql
> SELECT * FROM iris.train TO TRAIN my_model_collection.DNNClassifierNew ...
> ```
> 
> where the Python package `my_model_collection` should be under the `PYTHONPATH`. Currently the new model should work if you rename the folder to `sqlflow_models` and do the same, then use the statement: `SELECT * FROM iris.train TO TRAIN sqlflow_models.DNNClassifierNew ...`
> 
> I'll fix this in my next PR.

It works. Thank you  very much. expecting for ur next PR.

I have another question, the document( https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/tutorial/imdb-stackedbilstm.md) says:

> we only support custom model using keras subclass model.

this PR can **only support** custom model using keras? 
Can I make other custom model using not keras, is this in ur plan to support?

**Comment by typhoonzero** [comment]
We can support define any other models by writing the `sqlflow_train_loop`, please check out https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/contribute_models.md#write-models-other-than-keras for details. For example, the "deep embedding clustering" model is using Keras and kmeans to define a custom model: https://github.com/sql-machine-learning/models/blob/develop/sqlflow_models/deep_embedding_cluster.py

**Comment by wangyinlong** [comment]
> We can support define any other models by writing the `sqlflow_train_loop`, please check out https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/contribute_models.md#write-models-other-than-keras for details. For example, the "deep embedding clustering" model is using Keras and kmeans to define a custom model: https://github.com/sql-machine-learning/models/blob/develop/sqlflow_models/deep_embedding_cluster.py

thank you～
