### ISSUE TITLE
Can we choose either Couler/Argo or Fluid/Tekton

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#2195]
It seems that the SQLFlow server can generate Couler/Argo and Fluid/Tekton workflows.  To minimize the codebase, could we choose only one of them?

**Comment by Yancey0623** [comment]
I prefer Tekton which has the advantage over Argo:https://github.com/sql-machine-learning/sqlflow/issues/1980. But there is already some production environment deployed Argo backend, to minimize the codebase, maybe we can keep the Argo/Couler code on the develop branch and move `Tekton/Fluid` to fluid branch?
