### ISSUE TITLE
Some suggestions for REPL user experience

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#2221]
**1.**
When to `EXPLAIN` or `USING` <model name>, add a similar memory function to remember the name of the model that the user just trained.
**2.**
When using `TO TRAIN` <model name>, the current prompt model name is only the estimator model, it is recommended to support keras model
**3.**
When using shap to explain, it is recommended to add hints for relevant fields in shap, such as `summary.plot_type`.
**4.**
Currently, the model parameter explanation prompt is not displayed completely. It is recommended to add a model definition link or solve it in other ways.
**5.**
When there is a line break in the training sentence, `LABEL` cannot display the prompt message.

**Comment by lhw362950217** [comment]
We also need to add download links for the command-line tool too.
