### ISSUE TITLE
Add SQLFlow command-line tool build step to CI

### ISSUE THREAD

**Issue by lhw362950217** [sql-machine-learning/sqlflow#2226]
**Is your feature request related to a problem? Please describe.**
As described in [the command-line tool doc](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run/cli.md), we need a way to build our client daily and let users to download them using wget/curl.

**Describe the solution you'd like**
1. Add a build step in CI system to produce SQLFlow command-line binaries, including Linux, Windows, macOS versions
2. Provide a url for users to download these binaries
3. Update [corresponding docs](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run/cli.md) to provide a downloading tutorial

**Describe alternatives (optional)**

**Additional Notes**

**Comment by wangkuiyi** [comment]
https://docs.travis-ci.com/user/build-stages/#build-stages-and-deployments
