### ISSUE TITLE
EVALUATE clause support

### ISSUE THREAD

**Issue by sneaxiy** [sql-machine-learning/sqlflow#2290]
Do we support `TO EVALUATE` ? I see it in codes and unittests, but there is no doc on it.

https://github.com/sql-machine-learning/sqlflow/blob/94153c2b5c1133de7184b36df0663ad545d4ad09/pkg/parser/extended_syntax_parser.y#L257

https://github.com/sql-machine-learning/sqlflow/blob/32b5dc5cb5d34a4140aec7d4f4b329a3d55be27b/cmd/sqlflowserver/main_test.go#L1504

**Comment by typhoonzero** [comment]
This feature was added recently, I'll add documents for `TO EVALUATE` clause.
