### ISSUE TITLE
Not support decimal data type.

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#2303]
**Description**
When the type of data in hive is decimal, it throws converting exception as following.

**Reproduction Steps**
Detailed steps to reproduce

**Expected Behavior**
What you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/4661989/82299417-1317a300-99e8-11ea-96a5-d771c8631702.png)

![image](https://user-images.githubusercontent.com/4661989/82299229-d77cd900-99e7-11ea-9189-6ec9e517e1fd.png)
![image](https://user-images.githubusercontent.com/4661989/82299259-df3c7d80-99e7-11ea-9e2a-c9be5075e5b6.png)

**Environment (Please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional Notes**

**Comment by Yancey0623** [comment]
It seems `gohive` only support the limited types, https://github.com/sql-machine-learning/gohive/blob/a5791c2ac7fddcbfcaed7137f66b32839ae2ea78/rows.go#L112

I will add decimal type in `gohive`.
