### ISSUE TITLE
QiNiu qshell doesn't work stablly in CI/CD

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#2305]
The releasing of the sqlflow client to QiNiu's object storage often fail with various errors.  A typical one is:

```
Uploading C:/Users/travis/gopath/src/sqlflow.org/sqlflow/build/sqlflow.exe => sqlflow-release : latest/windows/sqlflow ...
[I] 2020/05/19 06:08:21 resumable.Put retrying ... 3 reason: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.30.0.11:50031->113.105.138.9:80: write tcp 10.30.0.11:50031->113.105.138.9:80: wsasend: An existing connection was forcibly closed by the remote host.
[I] 2020/05/19 06:13:21 resumable.Put retrying ... 3 reason: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.30.0.11:50050->113.105.138.9:80: write tcp 10.30.0.11:50050->113.105.138.9:80: use of closed network connection
[W] 2020/05/19 06:20:48 resumable.Put 3 failed: Post http://up-z2.qiniup.com/mkblk/4194304: readfrom tcp 10.30.0.11:50059->14.152.37.29:80: write tcp 10.30.0.11:50059->14.152.37.29:80: use of closed network connection
```

Let us consider a switch back to AWS S3.

**Comment by typhoonzero** [comment]
Maybe we can retry several times when uploading the file.

**Comment by wangkuiyi** [comment]
It seems that the retrials could all fail https://github.com/sql-machine-learning/sqlflow/pull/2327#issuecomment-633687827.

After @llxxxll register the domain name, we might bind it to a AWS China account.  Qiniu seems not stable enough.

**Comment by typhoonzero** [comment]
I see.

**Comment by wangkuiyi** [comment]
Qiniu uploading failure broke our CI of the develop branch again today. I will try to change the upload to AWS temporarily.

**Comment by typhoonzero** [comment]
We can use travis ci artifacts: https://docs.travis-ci.com/user/uploading-artifacts/ to upload build artifacts to AWS S3

**Comment by wangkuiyi** [comment]
Yes, we can. But Travis CI only uploads to AWS S3. Let me temporarily disable the upload till we have our download domain name registered and bound to AWS S3 China or Aliyun.
