### ISSUE TITLE
Support LibSVM data form in XGBoost  

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#2323]
Currently, column type in training table must be numerical, the libSVM data format like `k1:v1 k2:v2` is a  common data structure, we should support this column type in XGBoost training, prediction and model explanation.

**Comment by sneaxiy** [comment]
@brightcoder01 @typhoonzero There may be 2 methods to support LibSVM format:

- Method 1. Extend `NUMERIC` clause to support something like `NUMERIC(column_name, shape, delimiter, format)`, where `format` would be empty or `"libsvm"`.
- Method 2. Use a new COLUMN clause like `LIBSVM`, `KV`, `KV_NUMERIC`, etc.

I prefer method 1.

**Comment by typhoonzero** [comment]
We can derive whether the cell is libSVM format by checking the data, then we can have a `FieldDesc` struct for the field, adding a new member in the `FieldDesc`: `format`

**Comment by brightcoder01** [comment]
I think we can specify the format in NUMERIC expression obviously. 
If not, we can derive the format from the data.

Add a new COLUMN clause is heavy, and we didn't see the same requirement in TensorFlow and PyTorch at this time.
