### ISSUE TITLE
Data sharding problem in distributed XGBoost training using rabit

### ISSUE THREAD

**Issue by sneaxiy** [sql-machine-learning/sqlflow#2326]
I am not sure how XGBoost distributed training using rabit shards input data. Supposing that the whole dataset is D, there are 2 usually methods to shard input data in distributed training:

- Method 1: we shard dataset D beforehand into N pieces, where N is the number of workers. Then, we distribute each piece of dataset to each worker. In this way, each worker reads unique data.
- Method 2: all workers can read the whole dataset D, and the each worker only pick up 1/N data inside the whole dataset D, say, what [tf.data.Dataset.shard](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#shard) does.

In the doc of XGBoost and rabit, I have not found whether method 1 or 2 is used. But in the implementation of XGBoost, I found that maybe XGBoost uses method 2.

Link to my issue of XGBoost repo: https://github.com/dmlc/xgboost/issues/5694

**Comment by sneaxiy** [comment]
The evidence is listed as following:

- XGBoost loads csv or libsvm file as `DMatrix`. The constructor of `DMatrix` in Python calls C++ function `XGDMatrixCreateFromFile` .

https://github.com/dmlc/xgboost/blob/646def51e02d4017ac85065a10ca763e8941d62a/python-package/xgboost/core.py#L527

- C++ function `XGDMatrixCreateFromFile` calls `DMatrix::Load`, and `load_row_split=true` is parsed to `DMatrix::Load` if distributed mode is enabled.

https://github.com/dmlc/xgboost/blob/646def51e02d4017ac85065a10ca763e8941d62a/src/c_api/c_api.cc#L48-L60

- `DMatrix::Load` calls `rabit::GetRank()` and `rabit::GetWorldSize()`, and creates a file reader `dmlc::Parser<uint32_t>::Create(fname.c_str(), partid, npart, file_format.c_str())` which only reads part of the file data according to `rabit::GetRank()` and `rabit::GetWorldSize()` .

https://github.com/dmlc/xgboost/blob/646def51e02d4017ac85065a10ca763e8941d62a/src/data/data.cc#L404-L532

**Comment by sneaxiy** [comment]
If XGBoost would shard csv and libsvm file automatically, our implementation of XGBoost distributed training may be wrong in data reading. In the current implementation, we shard the data from database manually into each worker. It would make sharding twice, and some data would be lost.

**Comment by weiguoz** [comment]
Hi @sneaxiy, thanks for your exploration.
I followed [this sample](https://github.com/kubeflow/xgboost-operator/blob/34d49cc88a6130c99c8e36f8aa613ba8c6121513/config/samples/xgboost-dist/utils.py#L61) while developing the XGBoost distributed training. It looks like each worker reads part of `D`.

**Comment by sneaxiy** [comment]
@weiguoz It seems that [this sample](https://github.com/kubeflow/xgboost-operator/blob/34d49cc88a6130c99c8e36f8aa613ba8c6121513/config/samples/xgboost-dist/utils.py#L61) is a bit different. In this sample, the input data is `pandas.DataFrame`([see here](https://github.com/kubeflow/xgboost-operator/blob/34d49cc88a6130c99c8e36f8aa613ba8c6121513/config/samples/xgboost-dist/utils.py#L92)). Inside DMatrix, `pandas.DataFrame` would be converted to `numpy.ndarray` first([see here](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L320)), and the `numpy.ndarray` would be converted to DMatrix by calling C++ `XGDMatrixCreateFromMat_omp`([see here](https://github.com/dmlc/xgboost/blob/646def51e02d4017ac85065a10ca763e8941d62a/python-package/xgboost/core.py#L614)). `XGDMatrixCreateFromMat_omp` does not call `rabit::GetRank()` and `rank::GetWorldSize()` to build an adaptor([see here](https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L145)), which is quite different from `XGDMatrixCreateFromFile` ([see here](https://github.com/dmlc/xgboost/blob/646def51e02d4017ac85065a10ca763e8941d62a/src/data/data.cc#L473)). `XGDMatrixCreateFromFile` is the function when DMatrix is constructed from file, and it would call `rabit::GetRank()` and `rabit::GetWorldSize()` to create a file adapter.

In a word, creating DMatrix from file and from `pandas.DataFrame` may be quite different when distributed training is enabled.

Another proof I guess XGBoost uses method 2 is the official unittest [test_basic.py](https://github.com/dmlc/xgboost/blob/646def51e02d4017ac85065a10ca763e8941d62a/tests/distributed/test_basic.py#L1-L29). This distributed unittest does not split file first and the [comment](https://github.com/dmlc/xgboost/blob/646def51e02d4017ac85065a10ca763e8941d62a/tests/distributed/test_basic.py#L7) may indicate that XGBoost itself would shard the input data automatically.

**Comment by sneaxiy** [comment]
@typhoonzero @weiguoz I have tried to change C++ xgboost code to mock `npart`, so that `npart > 1` (number workers), and the output DMatrix from file is indeed splited into `npart` pieces (verified by calling `DMatrix.num_row()`).

**Comment by typhoonzero** [comment]
Thanks for @sneaxiy to discovering this issue. We need a fix immediately!

**Comment by sneaxiy** [comment]
I check DMatrix created by `numpy.ndarray` and `pandas.DataFrame` by changing rabit library to mock `rabit::GetWorldSize()`. And the results show that DMatrix would not be shared when constructing from `numpy.ndarray` or `pandas.DataFrame`.

Maybe there are 2 ways to fix our XGBoost python code:
- Dump the whole dataset into all workers.
- Dump part of the dataset into each worker, and load the data using `pandas.DataFrame`. I recommend this way for changing less code and dumping less data in each worker.
