### ISSUE TITLE
[Discussion] Rethink the semantics of TO RUN statement.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/sqlflow#2364]
### The Problem
In this PR #2355 , we propose to add `TO RUN` statement in SQLFlow.
```SQL
SELECT * FROM source_table
TO RUN a_data_scientist/functions:1.0/my_func.data_preprocessor.a_python_func
WITH param_a = value_a,
     param_b = value_b
```
The SQL statement above will be translated into a workflow of 2 steps. Each step will be executed in a container.
- The first step will retrieve the data `SELECT * FROM source_table` and store into a temporary table.
- The second step will execute a python function in the step container, or upload the python function (such as MaxCompute / Azure ML) to another platform and execute it in this platform.

But it has some limitation, the entity after `TO RUN` is a python function. If user implement the functionality using other languages such as `go` or `C++`, how can we leverage it in SQLFlow?

### Idea
we can make `TO RUN` statement a low level feature. It means invoke an executable implemented by any language. Executing a python function to do data computing can be a high level abstraction based on this low level feature.

##### Option 1

```SQL
SELECT * FROM source_table
TO RUN a_data_scientist/functions:1.0
WITH param_a = value_a, param_b = value_b
```

```BASH
docker run a_data_scientist/functions:1.0 --param_a value_a --param_b value_b
```

It has the limitation that the command parameters are `"--key value"` pattern.

##### Option 2

```SQL
SELECT * FROM source_table
TO RUN a_data_scientist/functions:1.0
CMD ["abc", "--param_a", "value_a", "--param_b", "value_b", "-switch_on"]
```

```BASH
docker run a_data_scientist/functions:1.0 abc, --param_a, value_a, --param_b, value_b, -switch_on
```

The parameters of `TO RUN` statement are exactly the same with the command line parameters. There is no limitation just like option 1. But it introduces a new keyword `CMD`.

#### High Level Abstraction

Let's consider the following user scenarios.

###### User develops a program (Go/Python/C++ ...) 

- Execute a program in the step image.
- Upload a program to another platform (MaxCompute, Azure ML), send a request to execute the executable in this platform.
  *From the perspective of user experience, the work of uploading the program and send requests will be done by a module (submitter?) provided from SQLFlow in the step container.*

###### User develops a function (script language - Python)

- Execute a python function `a_python_func` in the step image. The main function, the argument parsing and function invoke work will be done by a module provided by SQLFlow.
- Generate the main function and the code to invoke the `a_python_func`. Upload the generated code to another platform and execute the code on it.
  *The code generation and uploading work will be done by a SQLFlow module in the step container.*

#### Questions
- For each high level abstraction, do we need add a new syntax to support it? Or can we just customize the docker image? Or the entity after `TO RUN` is not only an image name, maybe {image_name} + {submit_type} + {program/function name}?

**Comment by shendiaomo** [comment]
> But it has some limitation, the entity after TO RUN is a python function. If user implement the functionality using other languages such as go or C++, how can we leverage it in SQLFlow?

There's no limitation in the Python function approach. Python is a general-purpose programming language that can do anything needed. For example, we can define a Python function that starts a process:
```python
def command(cmd:string, args:List[string]):
    subprocess.Popen([cmd] + args)
    ......
```
a user who wants to call command can do:
```sql
select * from table1 TO RUN image:v1/command WITH cmd="minecraft", args=["-l"] ......
```
in this approach, a user who only needs a python function doesn't have to implement a command

**Comment by wangkuiyi** [comment]
Record our phone discussion conclusions here:

```
SELECT ...
TO RUN minghong/model_zoo CMD a.py --param=10
```

```
SELECT ...
TO RUN sqlflow/python_starter CMD a_py_func, "param1=10", "param2=[1,2,4]"
```

**Comment by brightcoder01** [comment]
The entity after `INTO` clause can be one or more table names. 

```SQL
SELECT * FROM input_table
TO RUN a_data_scientist/functions:1.0
CMD abc, "--param_a", value_a, "--param_b", value_b, "-switch_on"
INTO out_table_1, out_table_2
```

The SQL statement above means that the executable in a_data_scientist/functions:1.0 has input and output, just like a function signature:
- input: The temporary table generated from `SELECT * FROM input_table`
- output: No `INTO` means no output. `INTO` means one or more output tables.

**Comment by brightcoder01** [comment]
Discussed with @shendiaomo , and add more notes here:
- `TO RUN` statement means execute a program or executable in this step container, or upload it to another platform (MaxCompute, Azure ML) and then execute it in this platform.
- User develops a program (such as python program with main function) or an executable (C++/go/...) in the function image.
- Let's take python program for example, for one deployment platform, there is only one way to execute it.
   Kubernetes: execute the python program in step image.
   MaxCompute: submit a PyODPS task to execute it using alisa.
- `SELECT * FROM table TO RUN a_data_scientist/functions:1.0 CMD param_a, param_b`, the 2nd step is `docker run a_data_scientist/functions:1.0 sqlflow.run.entry param_a, param_b`. We will share a unified entry point **sqlflow.run.entry**.

**Comment by brightcoder01** [comment]
**Add more thoughts (translate to English in the design doc)**

### 原则：简化用户使用，降低理解成本
- 对于用户，TO RUN Statement保持一种语义，参数设置保持一种语法
- 用户为TO RUN贡献（宾语），对于不同的语言，有统一的规范
- 用户在不同的部署平台上面，使用TO RUN，不用感知部署平台的底层细节（比如SQLFlow 和 MaxCompute之间的交互协议 - alisa）

### Details
##### 一种语义，一种参数设置方式 和 贡献规范
`TO RUN image_name`， 保持一种语义，即`docker run image_name command_line_parameters`，也就是在container内部执行一个executable.
1. 对于GO/C++ Module，用户提供的是一个完整，带有main函数的GO/C++代码编译出来的二进制文件；
2. 对于Python等Script Language，也希望用户提供一个完整的executable（并且可以接收参数配置），即一个带有main函数的python script，在main函数中解析参数，然后执行。另外如果用户提供的是一个完整的Python Program，也方便用户自助调试和执行（不依赖SQLFlow团队提供的EntryPoint File）；

对于用户来讲，语义统一`docker run image_name command_line_parameters`，参数设置语法也统一成command line的风格：
```SQL
SELECT * FROM input_table
TO RUN a_data_scientist/functions:1.0
CMD "abc", "--param_a", "value_a", "--param_b", "value_b", "-switch_on"
INTO out_table_1, out_table_2
```
用户为TO RUN准备的，是一个docker image，其中包含一个完整的可执行的程序 或者 脚本；

##### 屏蔽部署平台细节
如果上述思路成立的话，我们的问题就是，将用户提供的Program或者可执行文件，根据部署平台的不同，执行的方式也不同。以Python Program为例：
- 部署在开源平台上，我们直接在step image中执行用户提供的Python Program：执行`python  -m python_file.py`
- 在MaxCompute中，我们将用户提供的Python Program通过Alisa提交给MaxCompute执行：执行`alisa.submitter python_file.py`

那么剩下的问题就是对于不同的部署平台，对于`docker run image_name python_file.py --param_a value_a --param_b value_b`，应该是执行`python -m python_file.py` 还是 `alisa_submitter python_file.py`呢？

一个候选方案是：TO RUN背后的image；使用统一的entry point，都是SQLFlow提供的一个Module，例如就叫sqlflow.runner.
`docker run image_name python_file.py --param_a value_a --param_b value_b` 表示的含义是，在container中执行`sqlflow.runner  python_file.py --param_a value_a --param_b value_b`
sqlflow.runner这个模块根据部署平台的配置，来决定是执行`python  -m python_file.py` 还是 `alisa.submitter python_file.py`.

### Summary
通过上述方式，目标能够Address开头的原则：
1. TO RUN语义统一：docker run image command_line_parameters;
2. 用户为TO RUN贡献的规范：提供docker image，其中包含一个二进制可执行文件 或者 完整的可执行脚本，以及需要的依赖；
3. 用户使用SQLFlow团队提供的base image（将sqlflow.runner作为entry）来制作自己的function image，只需要关注数据处理的逻辑，不需要关注SQLFlow和其他平台（MaxCompute）的交互协议；

**Comment by brightcoder01** [comment]
Discussion Notes:
- Keep `INTO` clause for `TO RUN`. It means the output of the TO RUN function.
- For parameter configuration for `TO RUN`, we use `CMD` keyword and choose the command line style.
- At the first stage, we don't support high level abstraction for Python function. We support the python program.

Close this issue because we have reached the agreement.
