### ISSUE TITLE
Build process failed with model zoo version

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#2376]
I am building locally using `scripts/travis/build.sh`.  The build process errors:

```
Build model zoo ...
error: pathspec '07a75db' did not match any file(s) known to git.
```

**Comment by typhoonzero** [comment]
According to:

https://github.com/sql-machine-learning/sqlflow/blob/253920e84e364de226dce33b5f23bf63c4f2ede6/docker/dev/build.sh#L68-L74

Please check that if you have a `models` directory under you working directory? if there is, delete it or `cd` into it and run `git pull`.
