### ISSUE TITLE
Bug: Python API for testing customized model 

### ISSUE THREAD

**Issue by Derek-Wds** [sql-machine-learning/sqlflow#2410]
**Description**
Following the instructions [here](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/contribute_models_new.md), I was trying to see if it is easy to design a new model for the SQLFlow model zoo. However, I was unable to run the example test and verification code provided in the doc.

**Reproduction Steps**
Run these codes in ipython from terminal.
```python
import sqlflow
sqlflow.init("mysql://root:root@localhost:3306")
```

**Expected Behavior**
No error occured.

**Screenshots**
However, I got following error messages:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-86766133558c> in <module>
      1 import sqlflow
----> 2 sqlflow.init("mysql://root:root@localhost:3306")

AttributeError: module 'sqlflow' has no attribute 'init'
```

**Environment (Please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version:

**Additional Notes**
* I wonder if I missed some steps in running the codes, and I would appreciate it a lot if someone can help me with this. I installed SQLFlow from pip: `pip install sqlflow`
* Besides, when trying to run the entire SQLFlow following [instructions](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run/docker.md) using docker with: `sudo docker run --rm -it -p 8888:8888 sqlflow/sqlflow`, I have encountered following messages:
```
Couldn't watch /work: No such file or directory
Start SQLFlow server ...
2020-06-03 08:11:45 info msg="Launch server with insecure mode."
2020-06-03 08:11:45 info msg="Server Started at :50051"
```
and I cannot visit the web successfully at `localhost:8888`. Can anyone help me with this?

Thanks in advance!

**Comment by typhoonzero** [comment]
Thanks for your feedback.

In fact, the document here: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/contribute_models_new.md is a design doc, which is something we are designed to do. To contribute models under the current implementation, you should follow this doc instead: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/contribute_models.md.

Yet, we are polishing the Docker images now and the instructions in this doc may not work for now, let me know if you encounter with some blocking issues here.

**Comment by Derek-Wds** [comment]
Hi @typhoonzero, thanks for the information and it really helps! I’m planning to contribute new models to the model zoo during ASoC. I wonder if the new python API would be available by the time I started? (At the beginning of July) 

Thanks.

**Comment by typhoonzero** [comment]
We'll make sure that the new way of contributing models will be ready when 2020 ASoC started. You will be able to start a local environment to do developing and testing and releasing models. It will also be cool if you are contributing models to our models repo directly: https://github.com/sql-machine-learning/models

**Comment by Derek-Wds** [comment]
Thanks for letting me know! I’m excited and ready to make some contributions this summer to the repo! (I will close this issue now.)
