### ISSUE TITLE
Bugfix for fetching query results through multiple rpc call in gohive.

### ISSUE THREAD

**Issue by yuyicg** [sql-machine-learning/sqlflow#249]
for the field `HasMoreRows` in TFetchResultsResponse always return false in hiveserver2, in order to fetch query results data through multiple requests, instead, we check if the value in resultSet is empty to judge if there is more data to be fetched.

**Comment by tonyyang-svail** [comment]
> for the field `HasMoreRows` in TFetchResultsResponse always return false in hiveserver2

@yuyicg  This behavior looks like a bug in hiveserver2, can we file a bug report to Hive via https://issues.apache.org/jira/projects/HIVE/issues/?

**Comment by yuyicg** [comment]
this bug was issued in https://issues.apache.org/jira/browse/HIVE-11631?jql=project%20%3D%20HIVE%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22HasMoreRows%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC three years ago and still open.

**Comment by tonyyang-svail** [comment]
This bug has been fixed in `sql-machine-learning/gohive` repo.
