### ISSUE TITLE
dockerfile cannot run.

### ISSUE THREAD

**Issue by Kelang-Tian** [sql-machine-learning/sqlflow#2519]
**Description**
DNS cannot resolve some URLs.
Users cannot open some links when the user is in China, or the computer is equipped with the Alilang app.

**Reproduction Steps**
https://github.com/sql-machine-learning/sqlflow/tree/develop/docker/dev

Run `docker build -t sqlflow:dev -f docker/dev/Dockerfile . ` failed, because the URL can not be parsed by DNS:

https://github.com/sql-machine-learning/sqlflow/blob/759a018983e0139f0067c7e920f0fbaef0177a36/docker/dev/install.sh#L108

**Comment by Yancey0623** [comment]
Thanks for reporting this issue, maybe the domain `cdn.sqlflow.tech` is blocked by Alilang, we can  contact with the Alilang team to solve this problem.

**Comment by weiguoz** [comment]
Fixed.
Please take a try. @Kelang-Tian

**Comment by Kelang-Tian** [comment]
This problem has been resolved. Thanks for your help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "weiguoz"<notifications@github.com&gt;; 
发送时间: 2020年6月23日(星期二) 下午4:32
收件人: "sql-machine-learning/sqlflow"<sqlflow@noreply.github.com&gt;; 
抄送: "田科烺"<1141180644@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [sql-machine-learning/sqlflow] dockerfile cannot run. (#2519)





 
Fixed.
 Please take a try. @Kelang-Tian
