### ISSUE TITLE
Parse result shouldn't be a global variable

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#2541]
Currently, our parser contains a global variable

https://github.com/sql-machine-learning/sqlflow/blob/36eab7802cff31d862c1983d23407647339fd18a/pkg/parser/extended_syntax_parser.y#L154

And the start grammar rule writes the parsing result (something like an AST) into this global variable

https://github.com/sql-machine-learning/sqlflow/blob/36eab7802cff31d862c1983d23407647339fd18a/pkg/parser/extended_syntax_parser.y#L221-L227

This global variable prevents our parsing code from being thread-safe, and we need a mutex to synchronize concurrent calls to the parser.

https://github.com/sql-machine-learning/sqlflow/blob/36eab7802cff31d862c1983d23407647339fd18a/pkg/parser/extended_syntax_parser.y#L592-L606

We should correct the design by setting the result into a data member of the lexer instance using techniques described in https://about.sourcegraph.com/go/gophercon-2018-how-to-write-a-parser-in-go#using-goyacc.

**Comment by typhoonzero** [comment]
This is a critical issue.

**Comment by typhoonzero** [comment]
A complete example of this: https://gist.github.com/tkrs/23ab96cf84284ec6848c1c0a16611e21
