### ISSUE TITLE
Supports submitting pai/alisa tasks in sqlflow.runtime

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#2590]
As the discussion of #2494 and #2562 , SQLFlow should be a compiler, which generates target code instead of executing the intermediate representation (IR).

We now have a Go function https://github.com/sql-machine-learning/sqlflow/blob/cafd7cc92724a6a162756ebef444832484d578cc/pkg/executor/pai.go#L214 that submits pai/alisa tasks. This prevents us from decoupling codegen and execution, so we have to implement a Python module/function in `sqlflow.runtime` that supports submitting pai/alisa tasks.

**Comment by typhoonzero** [comment]
Maybe dup with https://github.com/sql-machine-learning/sqlflow/issues/2562

**Comment by Yancey0623** [comment]
> Maybe dup with #2562
I think so, @shendiaomo how do you think that we keep only one issue to trace this task?
