### ISSUE TITLE
Standardize SQLFlow's Go import path

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#260]
Because we don't own Github organization SQLFlow, we'd have to put the repo in github.com/sql-machine-learning/sqlflow, which implies that in our source code, we'd have to write Go package import path like

```go
import "github.com/sql-machine-learning/sqlflow/sql"
import "github.com/sql-machine-learning/gohive"
```

which is too lengthy.

Instead, Go provides a [vanity Go import path mechanism](https://blog.bramp.net/post/2017/10/02/vanity-go-import-paths/), which allows us to write

```go
import "sqlflow.dev/sqlflow/sql"
import "sqlflow.dev/gohive"
```

Do you, the SQLFlow Authors, would like to switch to the above shorter import path?

If so, what we need to do are

1. Create a `/sqlflow/index.html` file in the repo github.com/sql-machine-learning/sql-machine-learning.github.io.

1. Make sure that `/sqlflow/index.html` has the following meta tags

   ```
   <meta name=go-import 
      content="sqlflow.dev/sqlflow git https://github.com/sql-machine-learning/sqlflow.git">
   ```

1. Configure and makes the domain name `sqlflow.dev` points to https://sql-machine-learning.github.com/, just like `sqlflow.org` points to the same URL.

Similarly, we need to create `/gohive/index.html` in the repo github.com/sql-machine-learning/sql-machine-learning.github.io and includes a meta tag that points sqlflow.dev/gohive to github.com/sql-machine-learning/gohive.

**Comment by wangkuiyi** [comment]
It seems alright at the moment to use the long import path.

**Comment by joyyoj** [comment]
import "sqlflow.dev/gohive" seems better. 
In case that repo name changes, we  don't need to changes import.

**Comment by wangkuiyi** [comment]
I agree with @joyyoj . Reopen this issue.

**Comment by wangkuiyi** [comment]
Let us use sqlflow.org instead of sqlflow.dev, as people who are interested don't need to remember two domain names.
