### ISSUE TITLE
Hive stage on CI spent too much time

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#2636]
As the following figure, we should improve the performance of Hive test stage on TravisCI, c.f. https://travis-ci.com/github/sql-machine-learning/sqlflow/builds/174539492

![image](https://user-images.githubusercontent.com/1426912/86691883-d5c0b080-c03b-11ea-80b8-672457db223a.png)

**Comment by typhoonzero** [comment]
Closing since we have moved to use github actions.
