### ISSUE TITLE
The playground online

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#2642]
To make SQLFlow fans easier to experience SQLFlow, we should set up an online playground, some immature features are as following:

- User Interface
    - Auth: Github OAuth
    - IDE: Jupyter Notebook

- Client
    - Command-line tool
    - Tutorial online (Jupyter Notebook)

- Model Zoo
    - Build && push the model image on Aliyun cloud.
    - Docker registry: dockerhub.com
    - Website?

**Comment by lhw362950217** [comment]
By mention Command-line tool, do we mean the user connect the cloud with the client binary, or with a web command-line interface? As a playground, I think we don't need to provide the client if Jupyter Notebook can do almost everything.

**Comment by typhoonzero** [comment]
Closing since we have the online playground now at: https://playground.sqlflow.tech/
