### ISSUE TITLE
Make SQLFlow parser work together with Apache Calcite

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#273]
Currently, we use `sql/sql.y`, which, compiles into `sql/parser.go`, to parse a SQL statement. This parser has some limitations:

1. It understands our extended SQL syntax for the SELECT statement, for example,

   ```sql
   SELECT * FROM a_table TRAIN DNNClassifier INTO a_model;
   ```

   but cannot understand any other SQL statements, for example, `USE my_database`;

1. It understands the very basic syntax of standard SELECT, for example, it doesn't allow us to write a nested SELECT with the TRAIN and INTO suffix.

To make a parser that understands SQL completely and the extended SELECT statement, I am considering a hybrid of Calcite and our parser.  The following example might help to explain how the hybrid parser works.

1. Throw the above example statement`SELECT ... TRAIN ...` or even a more complex one like `SELECT ... FROM (SELECT ...) TRAIN ...`,  to Calcite parser.  The Calcite parser should error because it doesn't understand TRAIN.  If it happens that the error message contains information about the location of TRAIN in the input string, then we can split the input string at the location, and the left part is the SELECT or nested-SELECT, and the right part consists of `TRAIN ...`.

1. Throw the left part to Calcite parser again. This time the parser should be OK with it.

1. Throw the right part to our parser (modified to ignore the `SELECT ...` prefix), and it should be able to parse the TRAIN clause and provides information for SQLFlow code generator to create a `submitter.py`, which takes the left part that passed the syntax check of Calcite.  The submitter then sends the left part to the SQL engine (MySQL or Hive) and reads the output for training or prediction.

**Comment by wangkuiyi** [comment]
Sync up with my verification work: In short, Calcite does return the location of TRAIN in the above example and I am optimistic to move forward with this idea. 

## Verification Steps

Because this is my first Java program, I am documenting my verification steps thoroughly.

1. Get Calcite source code

   ```bash
   git clone git://github.com/apache/calcite.git
   ```

1. Build Calcite in a Docker container, because I don't want to bother install Java locally.

   ```bash
   docker run --rm -it -v $PWD:/work -w /work openjdk bash
   ```

1. Now, in the container, we are at `/work` where there is only one subdirectory `calcite`.  To build Calcite following [the official tutorial](https://calcite.apache.org/docs/tutorial.html#download-and-build).  Please do skip tests and style check, which takes too much resource and time.

   ```bash
   cd calcite
   ./mvnw install -DskipTests -Dcheckstyle.skip=true
   ```

1. After the building, we will find `jar` files in `file/target/dependencies`.  To make sure that we can run a simple program that calls Calcite (parser), we need to setup `CLASSPATH` as:

   ```bash
   for i in  file/target/dependencies/*; do CLASSPATH=$CLASSPATH:$i; done
   export CLASSPATH=$CLASSPATH:.
   ```

1. In any directory, create file `HelloCalcite.java` with the following content

   ```java
   import org.apache.calcite.sql.SqlNode;
   import org.apache.calcite.sql.dialect.AnsiSqlDialect;
   import org.apache.calcite.sql.pretty.SqlPrettyWriter;
   import org.apache.calcite.sql.parser.SqlParseException;
   import org.apache.calcite.sql.parser.SqlParser;

   public class HelloCalcite {
       public static void main(String[] args) {
	   String query = "Select a,b,c from d where d.id in (select id from (select id from e)) TRAIN DNNClassifier";

	   try {
	       SqlParser parser = SqlParser.create(query);
	       SqlNode sqlNode = parser.parseQuery();

	       SqlPrettyWriter sqlWriter = new SqlPrettyWriter(AnsiSqlDialect.DEFAULT);
	       System.out.println(sqlWriter.format(sqlNode));

	   } catch (SqlParseException e) {
	       e.printStackTrace();
	   }
       }
   }
   ```   

   Please be aware that the input `query` has the `TRAIN` suffix, which is not part of standard SQL.

1. Build and run the above program. 

   ```bash
   javac HelloCalcite.java && java HelloCalcite
   ```

   We will see that the line `e.printStackTrace();` prints the location of `TRAIN`:

   ```
	at HelloCalcite.main(HelloCalcite.java:13)
        Caused by: org.apache.calcite.sql.parser.impl.ParseException: Encountered "TRAIN" at line 1, column 71.
   ```

**Comment by wangkuiyi** [comment]
OK. I updated the program to be 

```java
import javafx.util.Pair;
import org.apache.calcite.sql.SqlNode;
import org.apache.calcite.sql.parser.SqlParseException;
import org.apache.calcite.sql.parser.SqlParser;
import org.apache.calcite.sql.parser.SqlParserPos;

public class HelloCalcite {

  private static int PosToIndex(String query, SqlParserPos pos) {
    int line = 0, column = 0;

    for (int i = 0; i < query.length(); i++) {
      if (line == pos.getLineNum() - 1 && column == pos.getColumnNum() - 1) {
        return i;
      }

      if (query.charAt(i) == '\n') {
        line++;
        column = 0;
      } else {
        column++;
      }
    }

    return query.length();
  }

  private static Pair<Integer, SqlParseException> parse(String query) {
    try {
      SqlParser parser = SqlParser.create(query);
      SqlNode sqlNode = parser.parseQuery();

    } catch (SqlParseException e) {
      int epos = PosToIndex(query, e.getPos());
      try {
        SqlParser parser = SqlParser.create(query.substring(0, epos));
        SqlNode sqlNode = parser.parseQuery();
      } catch (SqlParseException ee) {
        return new Pair<Integer, SqlParseException>(epos, ee);
      }
      return new Pair<Integer, SqlParseException>(epos, null);
    }

    return new Pair<Integer, SqlParseException>(query.length(), null);
  }

  public static void main(String[] args) {
    String query =
        "Select a,b,c from d where\n d.id in (select id from (select id from e)) TRAIN DNNClassifier";
    System.out.println(parse(query));
  }
}
```

It prints "71=null", which means that it finds a prefix in `query` that is a valid SQL statement ending at the 71-st character of `query`.

**Comment by wangkuiyi** [comment]
I had a rather-complete solution at https://github.com/wangkuiyi/learn-calcite, which verifies that

1. We can write a gRPC server in Java, which
1. calls Calcite's SQL parser to pick the prefix of a SQL statement that is standard SQL.

I am going to 

1. import this gRPC server into SQLFlow: https://github.com/sql-machine-learning/sqlflow/issues/274
1. change SQLFlow's parsing logic to call this gRPC server, and
1. change SQLFlow's parser in goyacc to focus on the TRAIN/PREDICT extension.

At the same time, would @shimingfei please explore another solution -- to change Calcite's SQL parser to completely support the syntax extension of SQLFlow?

**Comment by wangkuiyi** [comment]
Following suggestions from @yuyicg and @tonyyang-svail , I did a survey on other database systems:

1. Alibaba MaxCompute (a.k.a. ODPS)
   - Use ANTLR for parsing
   - [Use Calcite for query optimization](https://calcite.apache.org/docs/powered_by.html#alibaba-maxcompute)
1. Apache Hive uses ANTLR 
   - Use ANTLR for parsing. The grammer file is [here](https://github.com/apache/hive/blob/rel/release-2.3.4/hplsql/src/main/antlr4/org/apache/hive/hplsql/Hplsql.g4).
   - [Use Calcite for query optimization](https://calcite.apache.org/docs/powered_by.html#apache-hive)
1. Apache Flink
   - [Use Calcite for both parsing and query optimization](https://calcite.apache.org/docs/powered_by.html#apache-flink)

To understand more about ANTLR, I created [this issue](https://github.com/sql-machine-learning/sqlflow/issues/279).

**Comment by shimingfei** [comment]
> I had a rather-complete solution at https://github.com/wangkuiyi/learn-calcite, which verifies that
> 
> 1. We can write a gRPC server in Java, which
> 2. calls Calcite's SQL parser to pick the prefix of a SQL statement that is standard SQL.
> 
> I am going to
> 
> 1. import this gRPC server into SQLFlow: #274
> 2. change SQLFlow's parsing logic to call this gRPC server, and
> 3. change SQLFlow's parser in goyacc to focus on the TRAIN/PREDICT extension.
> 
> At the same time, would @shimingfei please explore another solution -- to change Calcite's SQL parser to completely support the syntax extension of SQLFlow?

I am investigating into it about how to extend Calcite's SQL grammar to fully support SQLFlow , and will file a document soon.

**Comment by hungry1526** [comment]
Have we figured a full designed of the SQLFlow parser now? 

Also, if we are going down towards adding more customization of Calcite, should we have an independent repo like model repo?

**Comment by shimingfei** [comment]
@hungry1526 Yes, it should be an independent module repo.  And I filed an initial design doc for it, please take a look if you are interested.
https://docs.google.com/document/d/1juca5AfcLgvsRjC8_WJcmfwPHn2ThvoqOt2bhP0d0-M/edit?usp=sharing

**Comment by wangkuiyi** [comment]
@shimingfei Thank you for the design doc! I think your design is a re-implementation of SQLFlow basing on changing Calcite parser, right? If so, it is out of the scope of this repo and is irrelevant with SQLFlow the project. I think you and Yuan Yao mentioned a new name for it -- SQL Gateway, right?

Here in this issue, we are discussing how to make SQLFlow talk to various SQL parsers, including Calcite parser, which is used by Flink, and TiDB parser which is compatible with MySQL. We focus on integrating with these external parsers, but not on how to change them. We focus on how to extend SQLFlow but not re-implement it.

For @hungry1526 's information -- I agree we need a design doc PR to resolve this issue. The design doc is actually the article on which you have been helping with @weiguoz.

**Comment by tonyyang-svail** [comment]
We have integrated the Calcite parser using the method described at [SQLFlow Parser Design](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/sqlflow_parser.md). So I am closing this issue.
