### ISSUE TITLE
Standard MySQL statement like "SELECT LAG(high, 1) OVER (ORDER BY date) AS high_lag_1 FROM stocks.apple_daily;" will throw syntax error.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/sqlflow#2754]
**Description**
The standard MySQL statement like `SELECT LAG(high, 1) OVER (ORDER BY date) AS high_lag_1 FROM stocks.apple_daily;` will throw syntax error.

**Reproduction Steps**
Setup the SQLFlow playground in Mac book.

The schema and sample data from the table `stocks.apple_daily` is just like follows:

```
date	        open	high	  low    close	  volume
1984-09-07	0.40934	0.41431	0.40439	0.40934	24044444
1984-09-10	0.40934	0.41058	0.39948	0.40689	18662411
1984-09-11	0.41058	0.42172	0.41058	0.41431	44007073
1984-09-12	0.41431	0.41677	0.40191	0.40191	38443931
1984-09-13	0.42422	0.42542	0.42422	0.42422	59875002
1984-09-14	0.42542	0.44025	0.42542	0.43037	71292377
1984-09-17	0.44150	0.44769	0.44150	0.44150	55663813
1984-09-18	0.44150	0.44522	0.42542	0.42542	28100367
1984-09-19	0.42542	0.43037	0.41677	0.41677	30694343
1984-09-20	0.41802	0.42172	0.41802	0.41802	19108770
```

Input the following SQL statement in Jupyter Notebook:

```SQL
SELECT LAG(high, 1) OVER (ORDER BY date) AS high_lag_1 FROM stocks.apple_daily;
```

The syntax error is thrown.

**Expected Behavior**
The SQL statement is executed correctly.

**Screenshots**
<img width="1038" alt="A10DFC20-C4DC-4182-8177-EBFE7CA6B571" src="https://user-images.githubusercontent.com/55301748/88606922-7d1b8b00-d0b0-11ea-9f33-0788df777894.png">

**Environment (Please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional Notes**

**Comment by brightcoder01** [comment]
Discussed with @tonyyang-svail , the potential reason is that the current TiDB parser doesn't support the syntax `SELECT LAG(high, 1) OVER (ORDER BY date) AS high_lag_1`.

The MySQL version is: 10.4.13-MariaDB
The TiDB Parser support `MySQL 5.7`. [link](https://github.com/pingcap/tidb#what-is-tidb)

**Comment by typhoonzero** [comment]
TiDB parser `.y` `LAG` definitions: https://github.com/pingcap/parser/blob/master/parser.y#L7437

**Comment by brightcoder01** [comment]
> TiDB parser `.y` `LAG` definitions: https://github.com/pingcap/parser/blob/master/parser.y#L7437

I have tried to upgrade the module github.com/pingcap/parser to v3.1.2+incompatible, the parser can only parse the sub-statement `SELECT LAG(high, 1) OVER`.

**Comment by brightcoder01** [comment]
> TiDB parser `.y` `LAG` definitions: https://github.com/pingcap/parser/blob/master/parser.y#L7437

Upgraded `github.com/pingcap/tidb` to `v0.0.0-20200701033011-332f2d44e4ed` from tag `v3.0.16` and `github.com/pingcap/parser` to `v3.0.14-0.20200616054854-4e23afb3683c+incompatible`. The parser can only parse the sub statement `SELECT LAG(high, 1) OVER`, the latter part of the statement `OVER (ORDER BY date) AS high_lag_1 FROM stocks.apple_daily;` cannot be parsed.

**Comment by brightcoder01** [comment]
Opened an [issue](https://github.com/pingcap/parser/issues/959#issuecomment-668352774) in Tidb Parser repo to track this.
