### ISSUE TITLE
Unify db api

### ISSUE THREAD

**Issue by lhw362950217** [sql-machine-learning/sqlflow#2781]
**Is your feature request related to a problem? Please describe.**
Current db.py make so many special check and branch to adapt different DB engines. We need to unify the DB api interface according to this [doc](https://www.python.org/dev/peps/pep-0249/). Especially for maxcompute.

**Describe the solution you'd like**
1. Modify maxcompute.py to adapt db api
2. Provide a query interface in the db.py

**Describe alternatives (optional)**

**Additional Notes**

**Comment by sneaxiy** [comment]
@lhw362950217 @typhoonzero @weiguoz I wonder should we make a common base class like this?

```
class Connection:
    def execute(self, sql): # return affected rows 
        raise NotImplementedError()

    def query(self, sql):  # return a generator which yields each row value
        raise NotImplementedError()

class MySQLConnection(Connection):
    def execute(self, sql): ...
    def query(self, sql): ...

class HiveConnection(Connection):
    def execute(self, sql): ...
    def query(self, sql): ...

class MaxComputeConnection(Connection):
    def execute(self, sql): ...
    def query(self, sql): ...

class AlisaConnection(Connection):
    def execute(self, sql): ...
    def query(self, sql): ...
```

In this way, we can remove so many if-else. And it would be easy when we need to support a new DBMS.

**Comment by lhw362950217** [comment]
> @lhw362950217 @typhoonzero @weiguoz I wonder should we make a common base class like this?
> 
> ```
> class Connection:
>     def execute(self, sql): # return affected rows 
>         raise NotImplementedError()
> 
>     def query(self, sql):  # return a generator which yields each row value
>         raise NotImplementedError()
> 
> class MySQLConnection(Connection):
>     def execute(self, sql): ...
>     def query(self, sql): ...
> 
> class HiveConnection(Connection):
>     def execute(self, sql): ...
>     def query(self, sql): ...
> 
> class MaxComputeConnection(Connection):
>     def execute(self, sql): ...
>     def query(self, sql): ...
> 
> class AlisaConnection(Connection):
>     def execute(self, sql): ...
>     def query(self, sql): ...
> ```
> 
> In this way, we can remove so many if-else. And it would be easy when we need to support a new DBMS.

Yes，I intend to do this, as described in point 2. As for hive & mysql, they already support DB-API specification, so they basically can share the same base class. As for `maxcompute`, we need to define a new class and customize some function to do this. Thanks for your advise for the OOP pattern.
