### ISSUE TITLE
Understand ANTLR and Hive's parser

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#279]
Related to https://github.com/sql-machine-learning/sqlflow/issues/273.

**Comment by wangkuiyi** [comment]
ANTLR has two well-used version: [3.x](https://github.com/antlr/antlr3) and [4.x](http://github.com/antlr/antlr4/). Hive 2.3.4 uses ANTLR 3.x, most modern projects use ANTLR 4.x.

The idea behind ANTLR is that

1. Users write a grammar file with extension filename `Hello.g3` or `Hello.g4`, 

1. Users call ANTLR command line tool to convert the grammar file into `HelloLexer.java` and `HelloParser.java`. To install and invoke the command line tool, refer to https://github.com/antlr/antlr4/blob/master/doc/getting-started.md.

1. Users write a Java class derived from class `HelloBaseListener` in `HelloParser.java`.  Users could define methods like `enterTag` and `exitTag`, where `Tag` is a grammar element.

1. In the main program, 
   1. parse the input stream into a grammar element tree, or, AST, and
   1. walk through the AST while doing something.

To quickly understand the above process, we'd refer to an example in the directory `/starter` from the tarball file at https://pragprog.com/titles/tpantlr2/source_code.

**Comment by wangkuiyi** [comment]
I don't want to install the many Java toolchain on my mac, so I created the following Docker image 

```dockerfile
FROM openjdk

ADD https://www.antlr.org/download/antlr-4.7.1-complete.jar /antlr.jar
ENV CLASSPATH=".:/antlr.jar:$CLASSPATH"

RUN echo 'java -Xmx500M -cp "/antlr.jar:$CLASSPATH" org.antlr.v4.Tool $@' > /usr/local/bin/antlr
RUN echo 'java -Xmx500M -cp "/antlr.jar:$CLASSPATH" org.antlr.v4.gui.TestRig $@' > /usr/local/bin/grun
RUN chmod +x /usr/local/bin/antlr /usr/local/bin/grun
```

so I can run ANTLR in a Docker container:

```bash
docker run --rm -it -v $PWD:/work -w /work antlr bash "antlr  Hello.g4"
```

**Comment by typhoonzero** [comment]
Hive parser using `antlr` is already implemented in previous commits.
