### ISSUE TITLE
sqlflow Failed to start via docker

### ISSUE THREAD

**Issue by jixiang-wang** [sql-machine-learning/sqlflow#2837]
**Description**
My operation is as follows:
1、docker pull sqlflow/sqlflow
2、docker run -it -p 8888:8888 sqlflow/sqlflow
![image](https://user-images.githubusercontent.com/31286734/90379882-e68a2a80-e0ad-11ea-8b71-fc98dde7c7be.png)
3、3. Open the link "localhost:8888" on the google browser
![image](https://user-images.githubusercontent.com/31286734/90380477-b000df80-e0ae-11ea-83b4-98e0488d63d2.png)

**Comment by zhaoweihan2017** [comment]
I encounter the same problem，do you know how to solve it？

**Comment by typhoonzero** [comment]
@zhaoweihan2017 please check out the latest "run in docker" document here: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run/docker.md

**Comment by zhaoweihan2017** [comment]
@typhoonzero it works，thanks.
