### ISSUE TITLE
Support SQLFlow drivers for web scripts （such as PHP、Python、Node.js...）

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#285]
The original:
"Through SQL, the training user classification, recommendation, marketing, and other models are more simple, so that more people can be its creative ability and the combination of AI technology, to promote the better development of the Internet."

For example as driver:
```php
<?php
$sqf_conn = new SQLFLOW("
     SQLFlow_host=$SQLFlowServerHost, 
     DB_host=$dbhost;
     $DB_name=myDB", 
     $DB_username, 
     $DB_password
);

$sqlflow_script = "
    SELECT *
    FROM iris.train
    TRAIN DNNClassifier
    WITH n_classes = 3, hidden_units = [10, 20]
    COLUMN sepal_length, sepal_width, petal_length, petal_width
    LABEL class
    INTO sqlflow_models.my_dnn_model;
    ";

$result = $sqf_conn->query($sqlflow_script);

$sqf_conn->close;

```

**Comment by wangkuiyi** [comment]
Thank you for your interests about SQLFlow client libraries.

We do have a client library in Python: https://github.com/sql-machine-learning/pysqlflow, which accesses the SQLFlow gRPC server with protobuf+gRPC interface definition at https://github.com/sql-machine-learning/sqlflow/blob/develop/server/proto/sqlflow.proto.

If you need any more information on the gRPC interface or the Python client library, please feel free to file issues in this repo or in the pysqlflow repo.
