### ISSUE TITLE
训练时报异常

### ISSUE THREAD

**Issue by wakinRen** [sql-machine-learning/sqlflow#2861]
**Description**
执行如下语句时发生异常
```python
%%sqlflow
SELECT * FROM test.ssq  TO TRAIN DNNClassifier WITH
  model.n_classes = 2,
  model.hidden_units = [10, 10],
  train.epoch = 10
COLUMN lan1, hongshun4, hongshun5, hongshun6
LABEL class
INTO sqlflow_models.ssq_lan_model;
```
表结构
```mysql
CREATE TABLE `ssq`  (
  `lan1` float NULL DEFAULT NULL,
  `hongshun4` float NULL DEFAULT NULL,
  `hongshun5` float NULL DEFAULT NULL,
  `hongshun6` float NULL DEFAULT NULL,
  `class` int(11) NULL DEFAULT NULL
)
```
异常信息：
```bash
<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Received RST_STREAM with error code 2"
	debug_error_string = "{"created":"@1597984180.169511538","description":"Error received from peer ipv4:172.17.50.111:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}
```
**Screenshots**

**Environment (Please complete the following information):**
 - OS: CentOS Linux release 7.3.1611
 - Browser: Google Chrome
 - Version: 2020-08-21  执行 docker pull sqlflow/sqlflow  检出的版本

**Additional Notes**

**Comment by typhoonzero** [comment]
您是按照何种方式启动SQLFlow的呢？

**Comment by wakinRen** [comment]
@typhoonzero   docker run --name sqlflowserver  -d -p 50051:50051 sqlflow/sqlflow
运行官方的例子没有异常。

**Comment by wakinRen** [comment]
@typhoonzero docker run --name jupyter -d -p 8888:8888 -e SQLFLOW_SERVER="XX.XX.XX.XX:50051" -e SQLFLOW_DATASOURCE="mysql://root:XXX@tcp(XX.XX.XX.XX:3306)/?maxAllowedPacket=0" sqlflow/sqlflow:jupyter

**Comment by typhoonzero** [comment]
`docker run --name jupyter -d -p 8888:8888 -e SQLFLOW_SERVER="XX.XX.XX.XX:50051" -e SQLFLOW_DATASOURCE="mysql://root:XXX@tcp(XX.XX.XX.XX:3306)/?maxAllowedPacket=0" sqlflow/sqlflow:jupyter` 这个命令在启动 jupyter 容器的时候需要加上`--net=container: sqlflowserver` 使得jupyter 和 sqlflowserver 可以互相连通；或者启动sqlflowserver和jupyter容器时都用`--net=host`暴露端口到容器外面。
