### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by gangliao** [sql-machine-learning/sqlflow#289]
The sqlflow looks very interesting. 

If it can support some distributed database systems like `CockroachDB` and `YugaByte DB`, data or tables can be partitioned and replicated across a shared-nothing cluster of independent servers, that will be great! 

I feel the distributed in-memory DB is the best fit for sql-machine-learning. `VoltDB` is a good option.

**Comment by wangkuiyi** [comment]
Thanks, buddy! We are working on integrating Hive and ODPS aka Alibaba MaxCompute. I agree with you on your points about CoakcorachDB, YugaByte DB, and VoltDB.
