### ISSUE TITLE
some problems about Text Classification Model examples

### ISSUE THREAD

**Issue by zhaoweihan2017** [sql-machine-learning/sqlflow#2904]
execute sql：

%%sqlflow
    SELECT content, class FROM imdb.train
    TO TRAIN DNNClassifier
    WITH
    model.n_classes = 2,
    model.hidden_units = [128, 64]
    LABEL class
    INTO sqlflow_models.my_text_model_en;

error log：

Start predicting using estimator model...

add to example:  content {'feature_name': 'content', 'dtype': 'int64', 'delimiter': ',', 'format': 'csv', 'shape': [256], 'is_sparse': False}

---------------------------------------------------------------------------
_MultiThreadedRendezvous                  Traceback (most recent call last)
<ipython-input-5-8952d3904e54> in <module>
----> 1 get_ipython().run_cell_magic('sqlflow', '', '    SELECT *\n    FROM imdb.test\n    TO PREDICT imdb.predict.class\n    USING sqlflow_models.my_text_model_en;\n')

/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2357             with self.builtin_trap:
   2358                 args = (magic_arg_s, cell)
-> 2359                 result = fn(*args, **kwargs)
   2360             return result
   2361 

<decorator-gen-117> in execute(self, line, cell)

/usr/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/usr/lib/python3.8/site-packages/sqlflow/magic.py in execute(self, line, cell)
     43 
     44         """
---> 45         return self.client.execute('\n'.join([line, cell]))
     46 
     47 def load_ipython_extension(ipython):

/usr/lib/python3.8/site-packages/sqlflow/client.py in execute(self, operation)
    147             # NOTE: raise exception to interrupt notebook execution. Or
    148             # the notebook will continue execute the next block.
--> 149             raise e
    150         except EnvExpanderError as e:
    151             raise e

/usr/lib/python3.8/site-packages/sqlflow/client.py in execute(self, operation)
    143         try:
    144             stream_response = self._stub.Run(self.sql_request(operation), timeout=DEFAULT_TIMEOUT)
--> 145             return self.display(stream_response)
    146         except grpc.RpcError as e:
    147             # NOTE: raise exception to interrupt notebook execution. Or

/usr/lib/python3.8/site-packages/sqlflow/client.py in display(self, stream_response)
    216                 else:
    217                     _LOGGER.info(response.message.message)
--> 218                     for response in reader.read_until_type_changed():
    219                         _LOGGER.info(response.message.message)
    220                     response = reader.last_response

/usr/lib/python3.8/site-packages/sqlflow/client.py in read_until_type_changed(self)
     45         while True:
     46             try:
---> 47                 response = next(self._stream_response)
     48             except StopIteration:
     49                 break

/usr/lib/python3.8/site-packages/grpc/_channel.py in __next__(self)
    414 
    415     def __next__(self):
--> 416         return self._next()
    417 
    418     def _next(self):

/usr/lib/python3.8/site-packages/grpc/_channel.py in _next(self)
    704                     raise StopIteration()
    705                 elif self._state.code is not None:
--> 706                     raise self
    707 
    708 

_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "runSQLProgram error: failed: exit status 1
==========Generated Code:==========

import tensorflow as tf
import runtime
from runtime.tensorflow.predict import pred
from runtime.tensorflow.get_tf_version import tf_is_version2
from tensorflow.estimator import DNNClassifier, DNNRegressor, LinearClassifier, LinearRegressor, BoostedTreesClassifier, BoostedTreesRegressor, DNNLinearCombinedClassifier, DNNLinearCombinedRegressor

**Comment by lhw362950217** [comment]
Thanks, @zhaoweihan2017

We have noticed the problem in issue #2898, and we are working on it now. Please expect our bug fix, thanks!

**Comment by lhw362950217** [comment]
Fixed
