### ISSUE TITLE
some problems about XGBoost regression model to fit the boston housing dataset

### ISSUE THREAD

**Issue by zhaoweihan2017** [sql-machine-learning/sqlflow#2907]
I am trying to train an XGBoost regression model to fit the boston housing dataset using the following statement:

%%sqlflow
SELECT * FROM boston.train
TO TRAIN xgboost.gbtree
WITH
    objective="reg:squarederror",
    train.num_boost_round = 30
COLUMN crim, zn, indus, chas, nox, rm, age, dis, rad, tax, ptratio, b, lstat
LABEL medv
INTO sqlflow_models.my_xgb_regression_model;

It occurs exception , the following log is follows:

File "/usr/local/sqlflow/python/runtime/dbapi/table_writer/protobuf_writer.py", line 16, in <module>
    from runtime.dbapi.table_writer import sqlflow_pb2
ImportError: cannot import name 'sqlflow_pb2'
"
	debug_error_string = "{"created":"@1599621107.684529698","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"runSQLProgram error: failed: exit status 1\n==========Generated Code:========

**Comment by lhw362950217** [comment]
Thanks very much! @zhaoweihan2017

This seems like identical to #2910, and we have fixed it in #2911

**Comment by lhw362950217** [comment]
Fixed
