### ISSUE TITLE
Does this work with mariadb database?

### ISSUE THREAD

**Issue by Amitloh** [sql-machine-learning/sqlflow#2918]
**Is your feature request related to a problem? Please describe.**
A clear description of the problem

**Describe the solution you'd like**
A clear description of what you want to happen

**Describe alternatives (optional)**
A clear description of any alternative solutions or features

**Additional Notes**

**Comment by typhoonzero** [comment]
We haven't tested using MariaDB, yet since MariaDB shares the same protocol as MySQL, you can take a try.

**Comment by lhw362950217** [comment]
@Amitloh Our [playground](https://playground.sqlflow.tech/) is using MariaDB, as far as I see, it works well.

**Comment by typhoonzero** [comment]
Closing due to low activity.
