### ISSUE TITLE
Support key-value list features data cells in the latest refactored code

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#2955]
Support key-value list features data cells in the latest refactored code `python/runtime` and `codegen/experimental`.

https://github.com/sql-machine-learning/sqlflow/pull/2939 made this change to support such kind of input. We need to port it to the refatored code.

**Comment by sneaxiy** [comment]
Fix by https://github.com/sql-machine-learning/sqlflow/pull/2968 .
