### ISSUE TITLE
Remove "modelDir" argument when starting sqlflowserver, we do not need to store models at local dir now

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#3042]
In `go/sqlflowserver/sqlflowserver.go` the argument `modelDir` is not needed currently since we are saving the models into databases. And, the `sqlflowserver` is deployed in a remote server so that saving models to the local filesystem seems not necessary now.

For local development and debugging, the current Python `runtime` package is saving the model files into a local directory and copy it to the database, we can call the `runtime` library and save the model in some dir for debugging purpose only.

**Comment by Yancey0623** [comment]
I agree with that, the way of production environment deployment is Argo mode, the `modelDir` argument of sqlflowserver only work with the local model(deprecated), we should remove it. If we have more scenes to save the model on a filesystem (local/S3/HDFS) we should redesign this feature.

I will finish this issue.
