### ISSUE TITLE
More help/documentation on how to use with Hive?

### ISSUE THREAD

**Issue by romainr** [sql-machine-learning/sqlflow#3112]
Hello,

First, the project is impressive and has a tun of great content, thank you!

One thing though I could not understand (and sorry if it is obvious), what would I need to do to configure sqlflow with Hive?

I am playing with the Quick Start
https://sql-machine-learning.github.io/sqlflow/doc/run/kubernetes/#setup-sqlflow-playground-with-single-user-mode
and read about the DB support
https://sql-machine-learning.github.io/sqlflow/doc/design/database_abstraction_layer/
and I am looking at running some queries from a local HiveServer2

Thanks

**Comment by weiguoz** [comment]
SQLFlow accepts database configuration via the argument `datasource`. The document [How to Connect Hive with SQLFlow](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run_with_hive.md) can help you.

**Comment by romainr** [comment]
Thank you, somehow could not find it.

Next steps it seems:

```
dockerun --rm --net=container:hive sqlflow/sqlflow bash -c "sqlflowserver --datasource='hive://root:root@localhost:10000/' &
SQLFLOW_SERVER=localhost:50051 jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''"

bash: line 1: jupyter: command not found
```

```
docker run -d -p 8888:8888 --name=hive sqlflow/gohive:dev
```

exits shortly after starting

**Comment by weiguoz** [comment]
The article [Run SQLFlow Using Docker](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run/docker.md) introduces a simple way to use SQLFlow with MySQL, which can be extended to Hive:
```bash
docker run --name=sf -d -p 8888:8888 sqlflow/sqlflow:latest sqlflowserver
docker run -it --net=container:sf -d sqlflow/gohive:dev bash
docker run --net=container:sf -d sqlflow/sqlflow:jupyter
```
The 2nd line `sqlflow/gohive:dev` provides a stand-alone server to act as a Hive server.
The 3rd line supplies a jupyter notebook.

Then, open the browser to access [http://localhost:8888/](http://localhost:8888/) and click [iris-dnn.ipynb](http://localhost:8888/notebooks/iris-dnn.ipynb).
To connect to the Hive server, we should specify a **datasource** string. The article [How to Connect Hive with SQLFlow](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run_with_hive.md) talks about the format of the **datasource** string. Here, we use `hive://root:root@localhost:10000/iris`.  Let's set `env` in the jupyter notebook.
![image](https://user-images.githubusercontent.com/6634907/103769945-28693c80-5060-11eb-9518-3be4cbabc419.png)

Also, `sqlflowserver` accepts the argument about **datasource**, like `sqlflowserver --datasource='hive://root:root@localhost:10000/'`. This is usually used when the **datasource** is fixed.

**Comment by romainr** [comment]
Thanks a lot @weiguoz, this works very well! Will play with it!

**Comment by romainr** [comment]
It is working well!
