### ISSUE TITLE
SQLFlow Product Roadmap 2019

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#327]
I am trying to summarize the milestones as follows. @sql-machine-learning/sqlflow team please comment.

Engineering time: 6 fulltime months could mean 3 people spend 2 months full time working on the project.

| Release | ETA   | Features                                               | Engineering Time    |
|---------|-------|--------------------------------------------------------|---------------------|
| Alpha   | 04/20 | ~~Open source SQLFlow Core~~                                    | 10+ fulltime months |
|         | 05/20 | ~~Support customized model with Keras~~                               | 1+ fulltime months  |
|         | 05/20 | ~~Open source Go Hive driver~~                          | 3+ fulltime months  |
|         | 06/20 | ~~Open source Go MaxCompute driver~~                               | 3+ fulltime months  |
| 0.1.0   | 07/01 | Hive: local training & prediction       | 2+ fulltime months  |
|         | 07/20 | Support distributed training & prediction                      | 3+ fulltime months  |
| 0.2.0   | 08/01 | MaxCompute: local training & predicting | 3+ fulltime months  |
| 0.3.0   | 10/15 | Elastic scheduling training & prediction               | 3+ fulltime months  |
| 0.4.0   | 11/20 | SQLFlow cloud release on AliCloud                                    | 2+ fulltime months  |
|         |       |                                                        |                     |
|         | ?     | Support third party submitter                          |                     |
|         | ?     | Support GPU or TensorFlow-GPU                          |                     |
|         | ?     | ML on image/audio/video                                |                     |
|         | ?     | Calcite parser                                         |                     |
|         | ?     | Open source gosparksql                                 |                     |
|         | ?     | SparkSQL as data source: local training & predicting   |                     |
|         | ?     | SQL Server as data source: local training & predicting |                     |

**Comment by hungry1526** [comment]
Is this Roadmap intended for only internal use, as we have engineering time column here, which external contributor won't care much about?

**Comment by xxllp** [comment]
很好奇这个ai 程序运行在数据库里面

**Comment by llxxxll** [comment]
This diagram explains how SQLFlow Server works and how it relates to databases and deep learning engines.
https://sql-machine-learning.github.io/sqlflow/doc/submitter.html
@xxllp

**Comment by xxllp** [comment]
看这个日期要稳定还要很久，现在就开源是准备拉人一起干吗

**Comment by llxxxll** [comment]
Now in the MySQL(database)、TensorFlow(Deep Learning Framework) has a stable version.

This roadmap describes how to serve more scenarios in the future.
@xxllp

**Comment by shanghai-Jerry** [comment]
@llxxxll  没有看到支持的模型的文档说明，就看到例子中的DNNClassifier，其他模型怎么使用？ 可以有更多例子么

**Comment by llxxxll** [comment]
@shanghai-Jerry 
The models currently supported are DNNClassifier. More models will be provided in the future. And each model will have an example. Please pay attention to the repo https://github.com/sql-machine-learning/models .

**Comment by wangkuiyi** [comment]
@xxllp do you mean "production-ready"? I agree that we are still far away from being production-ready. As @llxxxll explain, we have some features done, and we are pushing forward to make many more, including the model base as mentioned by @shanghai-Jerry . So, yes, you are right, we are looking for talents to join us! Your issues, pull requests, or any other form of contribution would be highly appreciated!

**Comment by xxllp** [comment]
yes，I want  to
 know have the sqlflow be used  in alibaba or someplace , or  it be have no one to use  in the future ~~~

**Comment by wangkuiyi** [comment]
Close this issue as the discussion here is running away from keeping technical.

**Comment by wuheyi** [comment]
数据源和模型比较重要，看这进度短期是用不上了
