### ISSUE TITLE
Continuous integration fails

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#330]
**Describe the bug**
CI build [failed](https://travis-ci.org/sql-machine-learning/sqlflow/builds/528104956) at `Step 6/34 : RUN pip3 install --upgrade pip`.

**To Reproduce**
`docker build -t sqlflow:dev -f Dockerfile.dev .`

![Screen Shot 2019-05-04 at 7 36 10 PM](https://user-images.githubusercontent.com/29932814/57178520-12c36d00-6ea4-11e9-98d3-9929ba2499e5.png)

**Comment by tonyyang-svail** [comment]
Per [this suggestion](https://stackoverflow.com/a/4910393), when dealing with multiple `python` and `pip` versions, it is recommended to use `python -m pip`.

**Comment by hungry1526** [comment]
@tonyyang-svail , seems this issue is also related? 
https://github.com/sql-machine-learning/sqlflow/issues/310

**Comment by wangkuiyi** [comment]
> Per this suggestion, when dealing with multiple python and pip versions, it is recommended to use python -m pip.

@tonyyang-svail But in our Docker image, we don't have **multiple** versions of Python, right? The only version we got is Python 3.6.

**Comment by tonyyang-svail** [comment]
In our Docker image, there are two versions of Python. One is Python2 carried by the base image `ubuntu:16.04`, another is Python3.6 installed by Conda. All Python dependencies, like TensorFlow and XGBoost, are installed using Python3.6.
