### ISSUE TITLE
Automatic read columns & columns types.

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#334]
If the data column is huge, it can be frustrating and error-prone to build SQL for SQLFlow.

The solution I want:
> SELECT *
> FROM iris.train
> TRAIN DNNClassifier
> WITH n_classes = 3, hidden_units = [10, 20]
> ~~COLUMN sepal_length, sepal_width, petal_length, petal_width, ...~~
> LABEL class
> INTO sqlflow_models.my_dnn_model;

a new sql for SQLFlow
```sql
SELECT *
FROM iris.train
TRAIN DNNClassifier
WITH n_classes = 3, hidden_units = [10, 20]
LABEL class
INTO sqlflow_models.my_dnn_model;

```

The current alternative is to write a script that automatically reads the table structure :)

**Comment by hungry1526** [comment]
It would be better to further explain what is N_Classes, Hidden_units, and usage related to DNNClassifer, as well as how the model relates to that from Tensorflow. 

Looks like this will be another discussion, will open a new issue to track.

**Comment by tonyyang-svail** [comment]
Hi @llxxxll, thanks for submitting this issue.

As mentioned in #636, we are planning to support this in the near future. Please use #636 to track the progress.
