### ISSUE TITLE
Supports reading data files from URL and training models based on metadata files.

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#337]
**Is your feature request related to a problem? Please describe.**
Sometimes the database stores, not metadata, but the link address of the metadata.
Training requires metadata, not links.

**Describe the solution you'd like**
- The desired solution is to add methods `from_data` that represent real data to be read through the URL.
```sql
COLUMN from_data(imgs_url), sepal, ...
```

- Some models treat different types of data differently(images, videos), and we may also need to specify metadata types `from_data(imgs_url, IMG)`.
```sql
COLUMN from_data(imgs_url, IMG), sepal, ...
```

**Comment by typhoonzero** [comment]
We are focusing on data in the databases, closing this for now.
