### ISSUE TITLE
Wrong statements about SQL joining syntax

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#345]
**Describe the bug**

In our [document](https://github.com/sql-machine-learning/sqlflow/blob/6a0f71d95cf7286bf4232468a3e98cc7ccce9361/doc/database_abstraction_layer.md), we state

> For example, various engines use different syntax for joining.

> MySQL: SELECT pet.name, comment FROM pet, event WHERE pet.name =event.name; with > keyword WHERE .
> Hive: SELECT pet.name, comment FROM pet JOIN event ON (pet.name =event.name) with keyword JOIN and ON.
> ODPS and SQLite use either INNER JOIN or OUTER JOIN.

However, MySQL supports the INNER JOIN .. ON .. syntax too, as documented [here](https://dev.mysql.com/doc/refman/5.7/en/join.html).

**Additional context**

Zhiheng Zhou reported this bug from Alibaba Group. I am the one who wrote it down.

**Comment by tonyyang-svail** [comment]
Thank Zhiheng for pointing out the mistake. I will update the document using the `FULL OUTER JOIN` example: https://stackoverflow.com/questions/4796872/how-to-do-a-full-outer-join-in-mysql .

The goal of this section is to point out there are some syntax differences across different SQL engines.
