### ISSUE TITLE
Improvement ideas for the installation guide.

### ISSUE THREAD

**Issue by helinwang** [sql-machine-learning/sqlflow#347]
1. https://sql-machine-learning.github.io/sqlflow/example/datasets/README.md:
Maybe put the trouble shooting tips inside "Popularize Datasets to MySQL" section. I encountered the same error, retried and it worked. The trouble shooting section perhaps is too far away to be found.

2. Manually building another image for loading data seems a barrier for trying out SQLFlow. Maybe create playground docker image that contains the database, MySQL server, Jupiter notebook file, and everything else? To reduce the steps for trying out the demo.

3. I was going through the second step of "Running your first SQLFlow query" in
https://sql-machine-learning.github.io/sqlflow/doc/installation. Opened http://127.0.0.1:8888, but could not find any Jupiter notebook file. I had to manually copy https://sql-machine-learning.github.io/sqlflow/example/jupyter/example.ipynb into the container.

4. After getting into the notebook, when running `%%sqlflow
show databases;` inside the notebook, I got
`_Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "Connect Failed"`
Seems the py notebook container can not connect to the data container. I tried some solutions but ran out of time in the end. I think putting everything into a same docker image would help in this case.

Keep up the great work!

**Comment by hungry1526** [comment]
1-4 will be addressed in a recent PR , thanks for the feedback.

**Comment by typhoonzero** [comment]
We are moving to the [cloud playground](https://playground.sqlflow.tech/) for quick start.
