### ISSUE TITLE
Browser based quickstart

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#354]
**Is your feature request related to a problem? Please describe.**
The current quickstart requires a user set up Docker container locally. I am afraid it is too complicated.

**Describe the solution you'd like**
Add a [Colab-like quickstart](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/keras/feature_columns.ipynb).

**Comment by typhoonzero** [comment]
We have https://playground.sqlflow.tech/ now closing.
