### ISSUE TITLE
whether support install sqlflow on linux platform not by docker? if suppport then how to?

### ISSUE THREAD

**Issue by vkingnew** [sql-machine-learning/sqlflow#359]
whether support install sqlflow on linux platform not by docker? if suppport then how to?

**Comment by typhoonzero** [comment]
We may need to add a document about how to install on bare linux server.

**Comment by hungry1526** [comment]
What flavor of Linux do you use? @vkingnew

**Comment by vkingnew** [comment]
Desire it！ CentOS 7 is better，and CentOS  is more popular then other Linux distribution like debian ，ubuntu  in production environment。Support Ubuntu also wonderful！

**Comment by hungry1526** [comment]
Wow fast response, we would definitely take it as a high-pri feature. Thanks, @vkingnew !

**Comment by typhoonzero** [comment]
SQLFlow currently compiles a SQL program to an Argo workflow which should be run on Kubernetes. We only support installation on a Kubernetes cluster, for more details: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run/kubernetes.md
