### ISSUE TITLE
Does SQLFlow support MySQL middleware/sharding?

### ISSUE THREAD

**Issue by thomas1984** [sql-machine-learning/sqlflow#365]
您好！sqlflow支持mysql分库分表的中间件么？

**Comment by wangkuiyi** [comment]
SQLFlow currently geneates Python submitter programs that read data from MySQL via a TCP connection to the MySQL server. It doesn't care how MySQL manages the database.

**Comment by hungry1526** [comment]
@thomas1984 

I understand some developers are based in China and prefer using Chinese to create issue, however, we hope SQLFlow to grow into an international open source project with developers coming from all over the world. Could you please create issue in English (As much as possible, and someone from the community will help elaborating the issue somehow. ) in the future to follow the convention in our SQLFlow community? Thanks.
