### ISSUE TITLE
Is SQLFlow related to any ML library? Any Dingding group to join? 

### ISSUE THREAD

**Issue by 383747787** [sql-machine-learning/sqlflow#372]
sqlflow需要安装机器学习包吗？ 有没有相关钉钉群可以加入 3Q

Updating content in English:
Is SQLFlow related to any ML library? Any Dingding group to join?

**Comment by wangkuiyi** [comment]
The only way we release SQLFlow is Docker images. If you want to use pre-built images or if you want to build your own from source code, please follow our documents https://github.com/sql-machine-learning/sqlflow#how-to-use-sqlflow.

We don't have DingTalk group or WeChat group. It is a good idea to have a user community on StackOverflow.com. But we don't have many developers at the right moment and I am afraid no one would have much bandwidth to answer questions out of Github Issues.

**Comment by hungry1526** [comment]
@383747787 Please use English as it's the primary language people use here in the community. For more information, please check out the documents in github as you like.
