### ISSUE TITLE
Unify DriverType name

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#374]
In `sqlflow`,  the following snippet appears in `sql` and `sqlfs` pkg  6 times.
```golang
if driver == "mysql" || driver == "sqlite3" {
    // do stuff a
} else if driver == "hive" {
   // do stuff b
}
```

**Describe the solution you'd like**
We should define these driver types in one place.

**Comment by typhoonzero** [comment]
Related comment: https://github.com/sql-machine-learning/sqlflow/pull/319#discussion_r283170855

**Comment by typhoonzero** [comment]
`sqlfs` package is moving to the python `runtime` package, and we unified the code into `runtime.dbapi` package.
