### ISSUE TITLE
Support Models

### ISSUE THREAD

**Issue by shanghai-Jerry** [sql-machine-learning/sqlflow#375]
I want to know that what models does sqlflow support now, Are there docs about how to use different popular models in tensorflow, such as bilstm and so on.

**Comment by wangkuiyi** [comment]
Thanks for this very good question.

SQLFlow currently converts a SQL statement with a TRAIN or PREDICT clause into a Python program (aka a submitter program). The source code of the code generator is at https://github.com/sql-machine-learning/sqlflow/blob/develop/sql/codegen.go.

The generated submitter program calls TensorFlow API to run a model defined as a TensorFlow Estimator. So, in short, a model should be defined as an Estimator. However, to train a model, we also need the cost and the optimizer and some hyperparameters.  For all these, the current implementation is still a little hacky.

We are working on defining the interface between SQL programmers and Python (model) programmers. We documented some early thoughts in https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/customized+model.md.

If you have any comment, please let us know. I am closing this issue, but you are welcome to file a new one or a pull request about your idea on standardizing model definition for SQLFlow.

**Comment by shanghai-Jerry** [comment]
@wangkuiyi Much thanks about your explantations about customized models, i see this [early thought](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/customized+model.md.) before, it's good,  i think more examples about using different customized models are really important.  i am thinking about for other models we should not be such customized for written the whole training code, it should be a standard and basic supports in sqlflow, we just choose the model we need and adjust the hyper-parameters. Looking forward to running  more and more models with sqlflow.

**Comment by wangkuiyi** [comment]
Hi @shanghai-Jerry, I completely agree with you about the ideas of the model base.

A quick update -- @typhoonzero and @tonyyang-svail have been working on the model base repo https://github.com/sql-machine-learning/models to create a standardized process for adding new models. We are looking forward to model contributions in the form of keras.Model-derived classes and tf.Estimator-derived classes.

Thank you for your attention on SQLFlow.

**Comment by shanghai-Jerry** [comment]
you are doing great works. Keep watching on SQLFlow
