### ISSUE TITLE
Developer experience bug in Notebook

### ISSUE THREAD

**Issue by hungry1526** [sql-machine-learning/sqlflow#383]
1) keyword highlighting is not consistent, only a few of them are highlighted in green.

2) return message from train and predict needs to be formatted. 

3) select statement has output with red text on the left while train and predict does not. 

<img width="1138" alt="Screen Shot 2019-05-14 at 11 26 09 AM" src="https://user-images.githubusercontent.com/1637753/57687512-24f49680-766e-11e9-84ea-bcc9854c98e2.png">

**Comment by tonyyang-svail** [comment]
Jupyter notebook uses Python syntax for its default keyword highlighting. Since `%%sqlflow` is a magic command (you can consider it as a very lightweight plugin), I can't think of a way to change the current behavior. @ktong may know more about Jupyter notebook.

**Comment by ktong** [comment]
1. It seems the highlight is not for SQL. Would you mind just input a SQL and compare the differences of highlight?
2/3. Train and predict has no output. It’s log which shows as stdout in notebook

**Comment by hungry1526** [comment]
#1 A related question is, should we follow the default highlight defined in SQL (In Notebook) to align with the same developer experience? I think we could try to improve it given that we are adding the extended syntax, but would like to hear suggestions from other folks.

**Comment by ktong** [comment]
@tonyyang-svail https://github.com/catherinedevlin/ipython-sql/pull/75

Above is a sample to highlight sql

**Comment by tonyyang-svail** [comment]
@ktong This looks really great. I will try it on `pysqlflow`. Many thanks. :)

**Comment by tonyyang-svail** [comment]
@hungry1526 This issue is related to `pysqlflow`, I will move it there.
