### ISSUE TITLE
Print the prediction accuracy when making the prediction.

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#389]
The solution I want:
- When making a prediction, add a column of "ACCURACY" at the end of the result output table,
update the accuracy rate value.
```
+--------------+-------------+--------------+-------------+-------+----------+
| SEPAL LENGTH | SEPAL WIDTH | PETAL LENGTH | PETAL WIDTH | CLASS | ACCURACY |
+--------------+-------------+--------------+-------------+-------+----------+
|          6.4 |         2.8 |          5.6 |         2.2 |     2 |     0.98 |
|            5 |         2.3 |          3.3 |           1 |     1 |     0.41 |
+--------------+-------------+--------------+-------------+-------+----------+
```
- Or print accuracy logs:
```
Data index_ID - accuracy 0.98;
Data index_ID - accuracy 0.41;
```

I believe you will have a more elegant way！

**Comment by hungry1526** [comment]
Should we also include precision and recall just for reference?

**Comment by tonyyang-svail** [comment]
If we need to implement this feature, we should do it in `EVALUATE` as mentioned in https://github.com/sql-machine-learning/sqlflow/issues/674
