### ISSUE TITLE
Nightly build is failing

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#392]
**Description**
Nightly CI [failed](https://travis-ci.org/sql-machine-learning/sqlflow/builds/533073861) at
```
scripts/test_hive.sh: line 3: /miniconda/etc/profile.d/conda.sh: No such file or directory
```

I would suggest using the following to set default Python venv

https://github.com/sql-machine-learning/sqlflow/blob/b4fce40a27a27baddc891984e6bebf3c69e9667f/Dockerfile.dev#L62-L63

instead of

https://github.com/sql-machine-learning/sqlflow/blob/b4fce40a27a27baddc891984e6bebf3c69e9667f/scripts/test_hive.sh#L3-L4

**Comment by hungry1526** [comment]
I also see other failures, in line 3062 for example: 

2019-05-15 23:44:49,569 INFO namenode.FSImage: Allocated new BlockPoolId: BP-1450180059-172.17.0.2-1557963889505
mkdir: Call From d30e8c1e0674/172.17.0.2 to localhost:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused

**Comment by hungry1526** [comment]
There are also a bunch of failed to rename failures.

**Comment by typhoonzero** [comment]
> `scripts/test_hive.sh: line 3: /miniconda/etc/profile.d/conda.sh: No such file or directory`

This error was because we didn't merge https://github.com/sql-machine-learning/gohive/pull/38 yesterday causing the gohive image is not updated.

I've reran the nightly job, it fails at `deploy` stage now. https://travis-ci.org/sql-machine-learning/sqlflow/builds/533073861 Will check it out.

**Comment by typhoonzero** [comment]
Seems `impyla` needs `bitarray` and `bitarray` need gcc to build when running `pip install`
