### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by ghost** [sql-machine-learning/sqlflow#398]
I really like this project but can you add an architecture document so I can see how it works please

**Comment by typhoonzero** [comment]
Thanks, can you please check out [this article](https://medium.com/@SQLFlow/sqlflow-motivations-and-the-design-e11bb6aa122c) to see if it helps?

**Comment by hungry1526** [comment]
@gedw99 we will update blogs with product announcement and tech discussion going forward, please follow closely, and leave some feedback to help do better.

**Comment by ghost** [comment]
That helps !! Will close ...
