### ISSUE TITLE
Remove duplicated churn.sql and iris.sql in folder sql/testdata

### ISSUE THREAD

**Issue by hungry1526** [sql-machine-learning/sqlflow#404]
Currently the sql scripts in this folder are pretty much the same as example. 

Fix:
Update the link to the file in db_test.go with sql scripts in example folder. 

```
assertNoErr(popularize(testDB, "testdata/iris.sql"))
assertNoErr(popularize(testDB, "testdata/churn.sql"))
```

Thanks.

**Comment by typhoonzero** [comment]
These duplicated files are already removed by previous commits.
