### ISSUE TITLE
SQLFlow SQLLite feature is currently incomplete

### ISSUE THREAD

**Issue by hungry1526** [sql-machine-learning/sqlflow#405]
SQLFlow currently has code that deals with sqlite database, but it seems incomplete as we don't plan to use it officially. We need to figure out a plan to either complete the development or discontinue or even clean up. 

Logging this issue for the record.

**Comment by wangkuiyi** [comment]
We used to use SQLite in unit testing. However, it is simplified too many features of a SQL database, including the retrieval of the data schema of tables, that makes it less valuable in testing and production.

**Comment by typhoonzero** [comment]
Removed sqllite support, it's quite rare that users are using sqlite to store production data for training. Can reopen this issue when we have real use cases.
