### ISSUE TITLE
CI go cover failed on go get

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#407]
**Description**
CI deployment [failed](https://travis-ci.org/sql-machine-learning/sqlflow/jobs/534701710#L6828) on
https://github.com/sql-machine-learning/sqlflow/blob/58b447c56fd4ebea1b171715df101f41d4fd6c58/scripts/deploy.sh#L17

With no permission error.
```
fatal: could not create work tree dir '/home/travis/gopath/src/golang.org/x/tools': Permission denied
package golang.org/x/tools/cmd/cover: exit status 128
scripts/deploy.sh: line 19: /go/bin/goveralls: No such file or directory
Script failed with status 1
```

**Comment by typhoonzero** [comment]
That's weird, I'm looking for a way to test that out.

**Comment by hungry1526** [comment]
Builds are failing on and off. I am wonder 1) what is causing the instability of the build system, do we have a clean baseline at the first place?  2) Any checkin broke the build by accident or some bug hangs around never got fixed.
