### ISSUE TITLE
Jupyter Notebook prints logs twice

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#416]
**Description**
![Screen Shot 2019-05-21 at 4 29 02 PM](https://user-images.githubusercontent.com/29932814/58080458-dc952580-7be5-11e9-97a6-085d281651d1.png)

**Comment by tonyyang-svail** [comment]
The issue disappeared after rerunning the container. Close for now.

![Screen Shot 2019-05-21 at 6 33 07 PM](https://user-images.githubusercontent.com/29932814/58089265-e8d5ae80-7bf6-11e9-844b-ae05177eaa50.png)

**Comment by llxxxll** [comment]
![image](https://user-images.githubusercontent.com/1908992/58395327-282e5000-807a-11e9-899a-06ff3f463791.png)
In this mirror image `sqlflow/sqlflow:latest`, the problem arises again.

**Comment by Yancey0623** [comment]
I can reproduce this bug by re-executing cell `%reload_ext sqlflow.magic`: print the log one more times per executing the cell.

**Comment by tonyyang-svail** [comment]
> I can reproduce this bug by re-executing cell `%reload_ext sqlflow.magic`: print the log one more times per executing the cell.

Excellent observation!
