### ISSUE TITLE
save model in a directory if training using custom keras model

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#432]
As mentioned in https://github.com/sql-machine-learning/sqlflow/pull/424#discussion_r287204826, we should support saving models to a directory if using a custom keras model, it could be helpful if we are going to save training logs, ploting learning curves etc.

**Comment by tonyyang-svail** [comment]
@typhoonzero Actually we don't need to save the model to a directory. SQLFlow runs a training job in a temporary directory then serializes the **whole** directory to a database table.
