### ISSUE TITLE
Add maxcompute CI

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#440]
**Is your feature request related to a problem? Please describe.**
Notice:
[Aliyun](https://workbench.data.aliyun.com/consolenew#/) provides no more than one maxcompute `project` for the user for free.
The `project` in maxcompute is just like the `database` in MySQL.
If we don't want to pay, the `train/pred` statement presented [here](https://github.com/sql-machine-learning/sqlflow#quick-overview) should be wrotten to:
``` sql
SELECT *
FROM theOnlyFreeProject.iris_train
TRAIN DNNClassifier
WITH n_classes = 3, hidden_units = [10, 20]
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class
INTO theOnlyFreeProject.my_dnn_model
```
to deal with different datasets.

**Comment by wangkuiyi** [comment]
Do you mean currently we write `FROM iris.iris_train` and `INTO my_models.my_dnn_model`, where `iris` and `my_models` differ from each other?

I agree that we unify them into one for demonstration and for testing.
