### ISSUE TITLE
Use batch reading from dataset instead of read all into memory

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#442]
Current [implementation](https://github.com/sql-machine-learning/sqlflow/blob/develop/sql/codegen.go#L228) use `fetchall()` to get all data in the table into memory which maybe too big, should support a general high-performance `dataset` reader todo batch reading.

**Comment by typhoonzero** [comment]
https://github.com/sql-machine-learning/sqlflow/pull/461 fixes this. Still part of the predict data read generator is reverted due to a bug, need to let predict use generator too.

**Comment by tonyyang-svail** [comment]
I believe all ML jobs are using the generator API.
