### ISSUE TITLE
Optimizing the content of the dockerfile

### ISSUE THREAD

**Issue by uuleon** [sql-machine-learning/sqlflow#443]
To make the docker image of `sqlflow`  reusing already existed layers as much as possible, maybe we should change the order of `RUN` commands and combining some `COPY` commands, etc.

**Comment by wangkuiyi** [comment]
Sounds a good idea. Can you provide more information?

**Comment by tonyyang-svail** [comment]
I feel our current Dockerfile setup is hard to optimize. In our Dockerfile, we pull the latest develop branch and build the binaries in `/go`. This step alone generates 400M+.
```
docker run --rm sqlflow/sqlflow:latest bash -c "du -sh /go/*"
37M	/go/bin
1.1M	/go/pkg
372M	/go/src
```

**Comment by wangkuiyi** [comment]
@tonyyang-svail Why do we git clone the develop branch in the Dockerfile? If the Dockerfile is for CI, it seems that we should git clone the branch under testing. If the Dockerfile (the development image) is for building a release, we can bind $GOPATH on the host into `/go` in the container, then we COPY $GOPATH/bin/sqlflow_server into the release Docker image.

**Comment by typhoonzero** [comment]
I added this when I was trying to put all three docker images into one: `latest`, `dev` and `quickstart`, this docker image is useful for building binaries, running CI tests and running the "quick start" demo.

> we can bind $GOPATH on the host into /go in the container, then we COPY $GOPATH/bin/sqlflow_server into the release Docker image.

This can be done actually, to reduce the image size, I'll try to optimize this in this week. Thanks!

**Comment by hungry1526** [comment]
> I added this when I was trying to put all three docker images into one: `latest`, `dev` and `quickstart`, this docker image is useful for building binaries, running CI tests and running the "quick start" demo.
> 
> > we can bind $GOPATH on the host into /go in the container, then we COPY $GOPATH/bin/sqlflow_server into the release Docker image.
> 
> This can be done actually, to reduce the image size, I'll try to optimize this in this week. Thanks!

Agree that the current dockerfile is for quickstart, dev/test, and ci. However, when developers, say from didi, want to use it in production, guess they need to build his own dockerfile for notebook, sqlflow server, or maybe database. Do we expect them to make the change or better providing with our instructions?

**Comment by typhoonzero** [comment]
@hungry1526 Well, for production use, they can specify the actual start-up command if they want to start only one service like only start `sqlflowserver` in the container and access from remote anywhere. Image size may not be a problem because we always have large enough disks on the server.

If sometime in the future we really need to separate these images for faster overall cluster zero-downtime upgrading, we should add documents on how to build images.
