### ISSUE TITLE
docker pull sqlflow/sqlflow:latest time out

### ISSUE THREAD

**Issue by liuyiyuan8888** [sql-machine-learning/sqlflow#452]
When run "docker pull sqlflow/sqlflow:latest" always timeout, I have wait it for finished 3 hours timeout!

**Comment by weiguoz** [comment]
It looks like the network problem. Maybe the [mirror](https://www.daocloud.io/mirror) gives some help.

**Comment by wangkuiyi** [comment]
It is a common problem to pull Docker images behind the great firewall. Mirrors are very necessary.
