### ISSUE TITLE
Add integration test with pysqlflow

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#455]
SQLFlow repo is responsible for releasing the final image. So its CI should contain integration tests with other repositories at `sql-machine-learning`. Recent bug https://github.com/sql-machine-learning/sqlflow/issues/453 exposes the lack of these type of tests.

At the time of writing, our tests include integration with gohive and models. We should add the integration test with pysqlflow.

**Proposed Solution**

1. Fix pysqlflow version in Dockerfile
1. Add test cases in `cmd/sqlflowserver/main_test.go`. e.g. `cmd.Run("python", "-c", "import sqlfow ...")`

**Comment by typhoonzero** [comment]
~~It's wired that the tests in https://github.com/sql-machine-learning/sqlflow/pull/446 is not passing because of the change introduced in: https://github.com/sql-machine-learning/sqlflow/pull/448, but in https://github.com/sql-machine-learning/sqlflow/pull/448 the tests passed.~~

Update: CI passed after merging the develop branch.

**Comment by tonyyang-svail** [comment]
Another potential bug https://github.com/sql-machine-learning/sqlflow/pull/446#discussion_r287748545 can be caught by the integration test.

**Comment by typhoonzero** [comment]
> Another potential bug [#446 (comment)](https://github.com/sql-machine-learning/sqlflow/pull/446#discussion_r287748545) can be caught by the integration test.

We need a test to verify the `sqlflow/sqlflow:latest` docker image and jupyter notebook works as expected.

**Comment by tonyyang-svail** [comment]
Another bug https://github.com/sql-machine-learning/sqlflow/issues/487 should be caught by CI.

**Comment by tonyyang-svail** [comment]
Hi @Yancey1989 , would you mind taking a look like this issue before upgrading the service protocol? :)

**Comment by Yancey0623** [comment]
Sure, will do that, the integration test is necessary.
