### ISSUE TITLE
Saving model to hive is slow

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#464]
At the end of a training job, `sqlfs` will save the model file by running tens or hundreds of insertion statements. Saving a several megabytes model typically takes about seconds for MySQL, while it takes minutes for Hive. :(

The reason boils down to the fact that the Hive server translates a SQL statement to a MapReduce job and runs it on the Hadoop, so every SQL statement has very high latency, e.g. several seconds (the bigger the cluster the worse). When running tens of insertion statements, they accumulated up to minutes.

**Comment by weiguoz** [comment]
After test saving models to `maxcompute`, I found it took **7** minutes to insert 37 records, which is difficult for users to accept.
It looks issue #377 (`Use independent storage media to save models`) is becoming increasingly urgent.

**Comment by typhoonzero** [comment]
We have `python/runtime/db_writer` package to do buffered writing to solve this: https://github.com/sql-machine-learning/sqlflow/tree/develop/python/runtime/db_writer
