### ISSUE TITLE
SQL syntax on multiple feature columns as model inputs

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#467]
SQLFlow syntax considers all fields in `COLUMN` as one feature column list. For example
```sql
SELECT ...
TRAIN DNNClassifier
COLUMN col1, col2, col3, col4
INTO ...
```
all columns in `COLUMN` will be translated to `feature_list` and passed as `feature_columns` to `DNNClassifier`.
```python
model = DNNClassifier(feature_columns=feature_list, ...)
```

However, some models may have multiple feature columns as inputs. Consider [the wide and deep model written in TensorFlow estimator](https://www.tensorflow.org/api_docs/python/tf/estimator/DNNLinearCombinedClassifier), whose constructor looks like the following
```python
model = DNNLinearCombinedClassifier(
    linear_feature_columns=linear_feature_list,
    dnn_feature_columns=deep_feature_list, ...)
```
Notice the `linear_feature_columns` and `dnn_feature_columns` are separate arguments. 

So we may need to propose a new SQL notation. Here I listed some proposals that @uuleon and I came up with. In all proposals, column `col1` and`col2` will passed as `linear_feature_columns`, and column `col3` and`col4` will be passed as `dnn_feature_columns`.

**Proposal 1**

Use `AS` keyword to denote different feature columns.
```sql
SELECT ...
TRAIN DNNLinearCombinedClassifier
COLUMN col1, col2 AS linear_feature_columns, col3, col4 AS dnn_feature_columns
INTO ...
```

**Proposal 2**

Use multiple `COLUMN` s to denote there are multiple feature columns and use `AS` to name the corresponding parameter names.
```sql
SELECT ...
TRAIN DNNLinearCombinedClassifier
COLUMN col1, col2 AS linear_feature_columns
COLUMN col3, col4 AS dnn_feature_columns
INTO ...
```

**Proposal 3**

Use special function `feature_column("parameter_name", ...)` to denote multiple feature columns.
```sql
SELECT ...
TRAIN DNNLinearCombinedClassifier
COLUMN
    feature_column("linear_feature_columns", col1, col2),
    feature_column("dnn_feature_columns", col1, col2)
INTO ...
```

The above proposals are still at a very early stage. Any comments are welcomed. :)

**Comment by typhoonzero** [comment]
How about:

```sql
SELECT ...
TRAIN DNNLinearCombinedClassifier
COLUMN_LINEAR col1,col2
COLUMN_DNN col3,col4
INTO ...
```

If the input feature need to go through embedding or padding, it should like:

```sql
SELECT ...
TRAIN DNNLinearCombinedClassifier
COLUMN_LINEAR col1,col2
COLUMN_DNN embedding(padding(col3), 64),col4
INTO ...
`
```

**Comment by wangkuiyi** [comment]
I am afraid that adding keywords like COLUMN_LINEAR is too much work.

**Comment by tonyyang-svail** [comment]
**Proposal 4**
Mentioned by @wangkuiyi. Similar to proposal 2, we use the keyword `FOR` instead of `AS`.
```sql
SELECT ...
TRAIN DNNLinearCombinedClassifier
COLUMN col1, col2 FOR linear_feature_columns
COLUMN col3, col4 FOR dnn_feature_columns
INTO ...
```

**Comment by typhoonzero** [comment]
Proposal 2 and 4 seems natural, vote for proposal 2 and 4.
