### ISSUE TITLE
Rename sql/db_test.go

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#468]
Per @hungry1526's suggestion, the file names `sql/database_test.go` and `sql/db_test.go` look confusing. Since `sql/db_test.go` mostly contains `TestMain`, shall we name it to something else. What is the convention of Go in naming the test entrance?

**Comment by wangkuiyi** [comment]
Maybe `sql/db_test.go` => `sql/sql_test.go`?

**Comment by Yancey0623** [comment]
`sql/sql_test.go` is a good idea, we can add more integration tests for the `sql` package in the future.
