### ISSUE TITLE
Change SQLFlow extended SQL syntax from TRAIN into TO TRAIN

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#473]
As mentioned in https://github.com/sql-machine-learning/sqlflow/pull/450#discussion_r287923105, SQL syntax allows aliases of table names. (Thank to Jian Zhang from PingCap helped me realized this.)

The following SQL statements are all legal:

```sql
SELECT * FROM t1
SELECT * FROM t1 t2 // t2 is an alias of t1
SELECT * FROM t1, t2 // t1 and t2 are table names
SELECT * FROM t1 t2, t3 // t1 and t3 are table names, t2 is an alias of t1
SELECT * FROM t1, t2, t3 t4 // t2 is an alias of t1, t4 is an alias of t3
```

So, if SQLFlow extends SQL SELECT statements by allowing users to append a TRAIN clause, we would see that the external parser (Calcite parser, TiDB parser, or Hive SQL parser) accepts the following statement until they meet the token "DNNClassifier", because they would think TRAIN is an alias of table t1.

```sql
SELECT * FROM t1 TRAIN DNNClassifier
                       ^
```

The above behavior is not what we want; we want the external parsers err on TRAIN instead of DNNClassifier.

A possible solution is to change the way SQLFlow extends SELECT statements from appending TRAIN to appending TO TRAIN.

```sql
SELECT * FROM t1 TO TRAIN DNNClassifier
```

**Comment by hungry1526** [comment]
“A possible solution is to change the way SQLFlow extends SELECT statements from appending TRAIN to appending TO TRAIN.” @wangkuiyi , should we also update the documents on Github?
