### ISSUE TITLE
[Failed] TestStandardDropTable

### ISSUE THREAD

**Issue by guiyang882** [sql-machine-learning/sqlflow#505]
![image](https://user-images.githubusercontent.com/5275638/59260307-f0282f00-8c6d-11e9-9abd-48d44092d475.png)

**Comment by tonyyang-svail** [comment]
@liuguiyangnwpu Thanks for mentioning this. This is not a test failure. So you are safe to move on and explore the code. :)

A failure in go test usually looks like

```
=== RUN ...
--- FAIL ...
```

While our log only shows `---SKIP ...`.

To be specific, we are testing the recovering from panic during parsing. So you are seeing the log message `level=panic msg= ... syntax error ...`. The skip message `[FIXME] ...` is misleading though, I will file a PR polish it.
