### ISSUE TITLE
Wrong error message while executing  a standard SQL

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#506]
**Description**
![image](https://user-images.githubusercontent.com/6634907/59270449-10fb7f00-8c84-11e9-99d3-3c3d24c59a9c.png)

More SQL(s):
- `SELECT count(*) FROM iris_train;`
Got `PANI[0047] start=13, pos=13 : syntax error near "*) from ir"  package=sql`

datasource: MySQL, Maxcompute

**Comment by tonyyang-svail** [comment]
I believe this error has been fixed. 

The cause: in the past, we use `strings.Contain(sql, "train")` to determine whether a SQL statement should be parsed by our parser. So `SELECT count(*) FROM iris_train;` is feed to our parser which raises the mentioned error.

We now use Lexer tokens to distinguish between standard SQL and extended SQL.
