### ISSUE TITLE
Do we need miniconda in Dockerfile

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#517]
Is the only purpose to introduce miniconda is to install Python 3?

If so, it seems that we can easily install Python 3.6 on Ubuntu 16.04 by following http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/, and could save many lines of code as follows:

https://github.com/sql-machine-learning/sqlflow/blob/1a46d471e36484e9421e533755b0c1bc9aaef381/scripts/image_build.sh#L19-L40

**Comment by typhoonzero** [comment]
> Is the only purpose to introduce miniconda is to install Python 3?

I think so. And from https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get I think we can install `Python3.6` directly by:  `sudo apt-get install python3.6`

**Comment by tonyyang-svail** [comment]
Similar to `sudo apt-get install python3.6`, our initial solution is to install Python via 
https://github.com/sql-machine-learning/sqlflow/blob/54e69554a1f8be8860b12d26e0fba17715ac79ed/Dockerfile#L4

It requires the user to invoke Python interpreter through `python3` and `pip3`, which is not ideal. Directly set `python3` as default Python interpreter cause random failure on CI https://github.com/sql-machine-learning/sqlflow/issues/330.

Following the suggestion of @zou000, we leverage `conda` to multiple Python versions. There is a discussion at https://github.com/sql-machine-learning/sqlflow/pull/331#discussion_r280989612.

**Comment by wangkuiyi** [comment]
We don't have **multiple** versions of Python in our Docker image.

Also, `pip3 install --upgrade pip` creates `/usr/local/bin/pip` in addition to `/usr/bin/pip3`. After that, it is safe to call `pip` other than `pip3`.

Similarly, we can do `ln -s /usr/bin/python3 /usr/local/bin/python` so we can use `python` instead of `python3`.  

I am not worried by the above concerns. Let me try to remove Miniconda and see if there will be other problems.
