### ISSUE TITLE
How to deal with table field named label

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#520]
Say we have the following table. Note the last column is named "label".

<table>
  <tr>
    <th colspan="5">my_table</th>
  </tr>
  <tr>
    <td>c1</td>
    <td>c2</td>
    <td>c3</td>
    <td>c4</td>
    <td>label</td>
  </tr>
  <tr>
    <td>&lt;data&gt;</td>
    <td>&lt;data&gt;</td>
    <td>&lt;data&gt;</td>
    <td>&lt;data&gt;</td>
    <td>&lt;data&gt;</td>
  </tr>
  <tr>
    <td>...</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

We want to train a model using c1, c2, c3, c4 as COLUMN, and label as LABEL. How do we write the SQLFlow statement?

The straight forward way doesn't work because the lexer considers the `label label` as two keywords, not keyword and identifier.

```SQL
select * from my_table
train model
column c1, c2, c3, c4
label label
into some_table;
```

**Comment by uuleon** [comment]
It's indeed a problem, I will try to modify `sql.y` to supporting the syntax like `... label "label" into ...`.

**Comment by tonyyang-svail** [comment]
@weiguoz  also suggested `label mytable.label`, which looks very promising. I feel this method doesn't require modifying `sql.y`.

**Comment by uuleon** [comment]
@weiguoz Great idea!

**Comment by tonyyang-svail** [comment]
I feel `mytable.label` may not be a good idea, because it involves parsing the information in the standard select. This is against our design philosophy to treat standard select and extended select separately and connect them with Unix-like pipe.

For simple select from a single table, `mytable.label` works. However, for more complicated statements like `select b.label from (select * from a) b`, it is unclear whether we should write `a.label` or `b.label`. More importantly, the column name of the statement result is `label` instead of `a.label` or `b.label`.

So let's try to implement `label "label"` as suggested by @uuleon.
