### ISSUE TITLE
removeLastSemicolon should be part of gohive

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#521]
https://github.com/sql-machine-learning/sqlflow/blob/95cc60823f5f5ee70aaaf5ba500775e7d592247f/sql/codegen.go#L168-L174

**Comment by weiguoz** [comment]
We access hive by `gohive` and `impala`.
In fact, gohive already supports this([ref](https://github.com/sql-machine-learning/gohive/blob/df8dfe248e52344576cefdfaa8bdf80a3397fa95/connection.go#L73-L80)) but `impala` not, so sqlflow implements `removeLastSemicolon` function to satisfy `impala`.

**Comment by tonyyang-svail** [comment]
I see. Thanks for pointing this out.
