### ISSUE TITLE
Support multiple feature columns in codegen.go

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#522]
**Describe the solution you'd like**
Following https://github.com/sql-machine-learning/sqlflow/pull/490, add support for multiple feature columns in codegen.go.

**Comment by typhoonzero** [comment]
WIP in https://github.com/sql-machine-learning/sqlflow/pull/519. And I'm sorry that this work will be finished next week.

**Comment by typhoonzero** [comment]
Done and close.
