### ISSUE TITLE
note:No local TensorFlow or Docker.  No way to run TensorFlow programs

### ISSUE THREAD

**Issue by cybend** [sql-machine-learning/sqlflow#542]
I run this demo  command,but note that "No local TensorFlow or Docker.  No way to run TensorFlow programs  ",  what wrong with my configration?
----------------------------------------------------------------------
sqlflow>  SELECT *
FROM iris.train
TRAIN DNNClassifier
WITH n_classes = 3, hidden_units = [10, 20]
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class
INTO sqlflow_models.my_dnn_model;

FATA[0466] No local TensorFlow or Docker.  No way to run TensorFlow programs  package=sql

**Comment by cybend** [comment]
I run with docker(sqlflow) and my mysql

**Comment by wangkuiyi** [comment]
Please follow the tutorial https://sql-machine-learning.github.io/sqlflow/doc/installation.html to install and run SQLFlow.
