### ISSUE TITLE
Need an integration test for the maxcompute

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#544]

**Comment by tonyyang-svail** [comment]
@Yancey1989 @weiguoz Any concrete plans on adding this CI?

**Comment by Yancey0623** [comment]
@tonyyang-svail @weiguoz As the discussion in the morning, I configurated the maxcompute AK/SK as the Travis CI environment variables. And because  
> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository

ref. https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

The maxcompute test only works in the cronJob and the PRs from the sqlflow branch.
