### ISSUE TITLE
Update to tensorflow version 2.0.0b1

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#573]
As described here: https://github.com/sql-machine-learning/sqlflow/pull/555#discussion_r301812503 , using `tensorflow==2.0.0b1` will cause keras models predict hang at the end of the script, should find out why and fix this.

**Comment by tonyyang-svail** [comment]
Models repo currently is using ['tensorflow==2.0.0-alpha0'](https://github.com/sql-machine-learning/models/blob/develop/setup.py#L25). Would this be the reason?

**Comment by typhoonzero** [comment]
Fixed in https://github.com/sql-machine-learning/sqlflow/pull/574
