### ISSUE TITLE
make SQL statement simple if column name is label

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#581]
A solution is described in https://github.com/sql-machine-learning/sqlflow/issues/520, which require users to write SQL statements like `SELECT mytable.col, mytable.label from mytable train xxx LABEL "label"`.

It's working now but for simple cases, it's not easy to use for people must specify `tablename.colname` in `SELECT` and quote `"label"` in `LABEL` clause. It's better if we can be able to parse the simple SQL like `select label from mytable train xxx label "label"`

**Comment by tonyyang-svail** [comment]
@typhoonzero Thanks for reporting this issue. One solution could be letting the SQL engine parser parse the select clause.

**Comment by typhoonzero** [comment]
Done by https://github.com/sql-machine-learning/sqlflow/issues/620
