### ISSUE TITLE
Does sqlflow support elasticsearch?

### ISSUE THREAD

**Issue by echohlne** [sql-machine-learning/sqlflow#586]
I am very interested in sqlflow, but I have a question. Can I ask whether sqlflow supports elasticsearch? Looking forward to your reply.

**Comment by Yancey0623** [comment]
Hi @echohlne , thanks for your attention, do you want to fetch data from the Elasticsearch and then train/predict a model, that means using the Elasticsearch as a Database?

**Comment by echohlne** [comment]
@Yancey1989 We have a large number of data in es,can we get data from es directly ?

**Comment by Yancey0623** [comment]
Hi @echohlne , SQLFlow doesn't support the Elasticsearch as the DB service, so you can not fetch data from es directly. SQLFlow supports the MaxCompute/Hive/MySQL/Sqlite3 as the DB service, for the current, you can extend the SQLFlow to support the Elasticsearch as the following steps:
- Implement an Elasticsearch Database driver, maybe you can reference [gomaxcompute](https://github.com/sql-machine-learning/gomaxcompute) and using it in [database.go](https://github.com/sql-machine-learning/sqlflow/blob/develop/sql/database.go#L51)
- Implement a generator in the Python submitter program, reference [maxcompute.py](https://github.com/sql-machine-learning/sqlflow/blob/develop/sql/python/sqlflow_submitter/maxcompute.py)
- Add some unit tests

**Comment by echohlne** [comment]
@Yancey1989  Thank you very much for your patience. I'll take a closer look at how the driver you mentioned is implemented.
