### ISSUE TITLE
[Feature Derivition] Thoughts about simpler column clause

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#589]
For discussion, We intend to let `COLUMN` clause to define:

- how to decode the data of the column
- how to define feature_columns as inputs of the model

The definition is:

```
column_clause
: COLUMN columns
| COLUMN columns FOR IDENT
| COLUMN columns AS IDENT
| column_clause COLUMN columns FOR IDENT
;
```

columns with `FOR IDENT` are used as `feature_columns` for the model, else it stands for the column processors, e.g.

```
COLUMN numeric(col1, dtype) FOR features,
                category_id(csv(col2, size, dtype, delim, sparse), bucket_size) AS col2_multi_hot,
                embedding(col2_multi_hot, 128) FOR features,
                cross(col2_multi_hot, col1) FOR features,
                embedding(category_id(csv(col3, size, dtype, delm, dense), 1000), 32)
```

`col1` is a scalar input tensor and it will be fed into the model as a `feature_column`; `col2` is a `SparseTensor` and will be fed into the model using embedding feature column; `col3` is a dense tensor and will be fed into the model using embedding column.

Rules:

1. `FOR IDENT`, `IDENT` is the parameter that the model takes, like `tf.estimator.DNNLinearCombinedClassifier` takes `linear_feature_columns` and `dnn_feature_columns`
2. `AS IDENT` will declare an alias of the current column.
3. you can define multiple "feature processors` but only the last one will be used.

Supported processors:

- `numeric(col, dtype)` scalar column
- `csv(col, size, dtype, delim, [sparse/dense])`
- `enum(col, size)`

User customized processors:

You can define your own processor and use it in SQLFlow, to do that you must define the process using the SQLFlow processor register API:

```python
@register_sqlfow_processor(name="json")
def json_processor(cell_input):
    return json.loads(cell_input)
```

The above lines of code should appear in your custom model defination files, so that SQLFlow could run it.

**Comment by tonyyang-svail** [comment]
Hi @typhoonzero, I am curious why not combining `category_id(csv(col2, size, dtype, delim, sparse), bucket_size) AS col2_multi_hot` and `embedding(col2_multi_hot, 128) FOR features` as
```
embedding(category_id(csv(col2, size, dtype, delim, sparse), bucket_size), 128)
```
So that we can avoid introducing keyword `AS`.

**Comment by typhoonzero** [comment]
@tonyyang-svail people may use `category_id(csv(col2))`, `embedding(category_id(csv(col2)))` or any level of feature to `cross()`, to avoid rewrite that one more time, we need `AS`
