### ISSUE TITLE
Label type in SQLFlow should be derived by the type of table column 

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#593]
**Description**
codegen.go hard code the type of label column to `int64`, it should be derived by the type of table column:

https://github.com/sql-machine-learning/sqlflow/blob/937329a498b4a20294414dc125c749ce1b14b982/sql/codegen.go#L355-L358

**Comment by typhoonzero** [comment]
This is resolved by https://github.com/sql-machine-learning/sqlflow/pull/609
