### ISSUE TITLE
Support other types of train/evaluate splitting strategies

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/sqlflow#655]
Currently it looks like sqlflow only supports random splitting strategy for splitting training and evaluation data (according to [this doc](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/training_and_validation.md)). However, in many problems, the splitting strategies may vary. For example, in time series problems, we cannot build a model that learns from future data to predict the past (considered cheating). suppose you have a dataset from day 1 to day 8, users can only use the data from day 1 to day 5 as training data and day 6 to day 8 as evaluation data since . Once the model is evaluated using day 6 to day 8, it can be used in production to predict the future.

As a reference, scikit-learn provides many [splitter classes](https://scikit-learn.org/stable/modules/classes.html#splitter-classes), including [one that can be used for time-series splitting](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html#sklearn.model_selection.TimeSeriesSplit).

**Comment by terrytangyuan** [comment]
We may also want to allow users to provide their own training and evaluation data instead of letting SQLFlow handle this since sometimes users may want to customize the splitting strategy.

**Comment by typhoonzero** [comment]
Users should split there dataset using pure SQL, or write custom `TO RUN` statement.
