### ISSUE TITLE
Support evaluation-only jobs

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/sqlflow#656]
Currently SQLFlow only supports training and evaluation in the same time. However, sometimes users may want to evaluate a previously trained model on new data so that they can compare different versions of models to see if the new model is more performant than the previous model on the same evaluation data (a common use case for model retraining).

**Comment by typhoonzero** [comment]
Implemented, check out the latest document here: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/language_guide.md#evaluation-syntax
