### ISSUE TITLE
Make SQLFlow server support concurrent jobs

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#666]
It has been reported that two SQLFlow clients can't access the server at the same time. One long-running job submitted by one client is blocking the other client. I will try to reproduce this situation and update the description later.

**Comment by wangkuiyi** [comment]
Do you mean to assign an ID to each job and to track job status given its ID?

**Comment by tonyyang-svail** [comment]
> Do you mean to assign an ID to each job and to track job status given its ID?

@wangkuiyi Not really. Sorry for the confusion. I have updated the description and will fill out the details on the cause.

**Comment by tonyyang-svail** [comment]
Unable to reproduce at https://github.com/sql-machine-learning/sqlflow/pull/668. Close for now.

**Comment by typhoonzero** [comment]
I've also tested #668 seems gRPC can handle concurrent client requests using go routine.
