### ISSUE TITLE
Import database drivers in codegen*.go

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#667]
This might not be a bug, but need to confirm.

In `codegen.go`, we imported the following three database drivers

https://github.com/sql-machine-learning/sqlflow/blob/2e62e3ebfd55b37fd6cdc463faa404a4037d7786/sql/codegen.go#L22-L24

However, the code seems related to SQLite3

https://github.com/sql-machine-learning/sqlflow/blob/2e62e3ebfd55b37fd6cdc463faa404a4037d7786/sql/codegen.go#L235-L236

Do we need to add the following code snippet?

```go
import _ "github.com/mattn/go-sqlite3"
```

**Comment by wangkuiyi** [comment]
The same case in codegen_xgboost.go.

Is that we don't need to import the SQLite3 driver because the codegen*.go files don't access the databases, but simply parse database names etc.?

**Comment by weiguoz** [comment]
> The same case in codegen_xgboost.go.
> 
> Is that we don't need to import the SQLite3 driver because the codegen*.go files don't access the databases, but simply parse database names etc.?

Right!
In codegen*.go, SQLFlow parses a datasource by `PasrseDSN()` defined in the database driver.
SQLite3 is so simple that SQLFlow uses database name directly.
https://github.com/sql-machine-learning/sqlflow/blob/2e62e3ebfd55b37fd6cdc463faa404a4037d7786/sql/python/sqlflow_submitter/db.py#L27-L29

**Comment by tonyyang-svail** [comment]
@weiguoz The support of SQLite3 is not on the roadmap, shall we delete SQLite3 related code since its causing some confusions here.

**Comment by typhoonzero** [comment]
SQLite3 related code is deleted in previous commits.
