### ISSUE TITLE
Keep with statement attributes use the same paradigm

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#669]
As described here in https://github.com/sql-machine-learning/sqlflow/issues/664#issuecomment-521489061, we need to 

About the `WITH` attributes, I'd like to first define some overall rules in the parser, like attribute names should all follow: 

- `model.[attr]` define attributes passed to the model initialization phase.
- `train.[attr]` define attributes when calling `estimator.train` ( or maybe `trainspec` ) or `model.fit` for keras.
- `eval.[attr]` attributes for evaluation.
- `engine.[attr]` for distributed submission attributes like `num_workers`.

All submitters should follow these rules and attributes will first go through a "validator", to keep the user experience the same.

**Comment by terrytangyuan** [comment]
What’s the expected timeline for this? We probably need this soon as we are trying to integrate now.

**Comment by typhoonzero** [comment]
I'll try to finish this work this week.

**Comment by terrytangyuan** [comment]
Also need attributes for prediction.

**Comment by terrytangyuan** [comment]
@typhoonzero Could you hold off on changing this yet? I am adding parameters for ElasticDL (following this convention). Once it's done, we can then consolidate them all.

**Comment by terrytangyuan** [comment]
@typhoonzero Just added them in https://github.com/sql-machine-learning/sqlflow/pull/670.
