### ISSUE TITLE
Add EVALUATE keyword

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#674]
This issue inherits from https://github.com/sql-machine-learning/sqlflow/issues/660#issue-480569126.

Let us add a new clause EVALUATE in addition to TRAIN and PREDICT.

```sql
SELECT ... EVALUATE metric1, metric2, ...
```

where `metric`*i* could be a set of predefined metrics, for example, loss and AUC.

**Comment by typhoonzero** [comment]
As discussed, a possible solution of running validation during training:

```sql
SELECT …
TRAIN model
INTO my_model
[VALIDATE ( SELECT …)];
```

**Comment by weiguoz** [comment]
> As discussed, a possible solution of running validation during training:
> 
> ```sql
> SELECT …
> TRAIN model
> INTO my_model
> [VALIDATE ( SELECT …)];
> ```

VALIDATE -> EVALUATE
How about adding an `ON` behind ~~VALIDATE~~(EVALUATE)?

```SQL
SELECT …
TO TRAIN model
INTO my_model
[EVALUATE ON ( SELECT …)];
```

**Comment by wangkuiyi** [comment]
The evaluate keyword has been added.

https://github.com/sql-machine-learning/sqlflow/blob/39a9701d99aa1e989cccc7dc3d17056f6848f85f/go/parser/extended_syntax_parser.y#L317-L320
