### ISSUE TITLE
Support process multiple SQL statements in one RPC call

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#695]
To avoid writing `%%sqlflow` in each notebook block to create a full workflow of data processing and training, we need to support writing multiple SQL statements in the notebook like:

```sql
%%sqlflow
CREATE TABLE copied_table AS SELECT * FROM origin_table where random > 0.8;
-- NOTE: this comment line is not going to run.
SELECT * FROM copied_table limit 100;
```

**Comment by weiguoz** [comment]
What's the motivation of supporting multiple SQL statements?

**Comment by typhoonzero** [comment]
> What's the motive of supporting multiple SQL statements.

Added in the issue description.
