### ISSUE TITLE
Support model explanation using SHAP

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#701]
Using SHAP: https://github.com/slundberg/shap

```sql
SELECT * FROM train_table
TRAIN DNNClassifier
COLUMN *
INTO my_model
EXPLAIN DNN(force|dependency|summary|image)
```

for xgboost sql

```sql
SELECT * FROM train_table
TRAIN xboost.estimator
COLUMN *
INTO my_model
EXPLAIN TREE(force|dependency|summary|image)
```

**Comment by Yancey0623** [comment]
Another possible syntax design
``` sql
SELECT * FROM train_table
EXPLAIN TREE
WITH
    plot_type=summary
USING my_model;
```

**Comment by tonyyang-svail** [comment]
@Yancey1989 I think `TREE` is redundant since `my_model` has the model type. How about
```sql
SELECT * FROM train_table
EXPLAIN my_model
WITH plot_type=summary;
```

**Comment by weiguoz** [comment]
> Another possible syntax design
> 
> ```sql
> SELECT * FROM train_table
> EXPLAIN TREE
> WITH
>     plot_type=summary
> USING my_model;
> ```

We are going to split the SQL into 2 parts(standard and extended SQL) by `TRAIN/PREDICT`.
In this case, I don't think it is easy to split the SQL by `EXPLAIN`(a reserved word). Should we use another word?

**Comment by Yancey0623** [comment]
> @Yancey1989 I think TREE is redundant since my_model has the model type. How about

@tonyyang-svail , maybe`TREE` is not redundant, as [shap](https://github.com/slundberg/shap) includes many differences type like `TreeExplainer` for XGBOOST, `DeepExplainer ` for `Tensorflow`, do you mean we can infer this type by the AI engine backend?

**Comment by wangkuiyi** [comment]
How about we support the following syntax

```sql
SELECT * FROM table 
ANALYZE my_image_classifier 
WITH plots=[image, force]
USING DeepExplainer
```

where

- `my_image_classifier` is a trained model, 
- `image` and `force` name some SHAP plot types, e.g., https://github.com/slundberg/shap#documentation-notebooks
- `DeepExplainer` names a SHAP [explainer type](https://github.com/slundberg/shap#sample-notebooks).

After typing the above SQLFlow in Jupyter Notebook, users expect to see the following two pictures displayed below the input cell, one of type `image` and the other of type `force`.

![](https://raw.githubusercontent.com/slundberg/shap/master/docs/artwork/gradient_imagenet_plot.png)
![](https://raw.githubusercontent.com/slundberg/shap/master/docs/artwork/iris_instance.png)

**Comment by tonyyang-svail** [comment]
Closing this issue as #707 is used for tracking the progress of this feature.
