### ISSUE TITLE
Consolidate how submitters are registered in executor

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/sqlflow#714]
Currently the way to switch to use different submitters is a little messy:
1. ALPS submitter does this via checking for `os.Getenv("SQLFLOW_submitter") == "alps"` in `executor.runExtendedSQL`.
2. XGBoost submitter does this via checking whether estimator's name contains `XGBOOST.` inside `executor.train()` and `executor.predict()`.

Since ElasticDL submitter will be registered in a similar fashion to ALPS submitter, could we change XGBoost to follow how ALPS submitter does it?

**Comment by typhoonzero** [comment]
Some backgrounds of why we use the model name to distinguish xgboost training using the model name but not the environment variable of the current deployment: https://github.com/sql-machine-learning/sqlflow/issues/539

**Comment by tonyyang-svail** [comment]
Hi @terrytangyuan, as explained in #539.

> We use the model name to determine TF and XgBoost. And we use env `SQLFlow_submiiter` to determine different runtime engine of TF (native, ALPS, EDL etc).
