### ISSUE TITLE
Split Dockerfile into multiple Dockerfiles for different submitters

### ISSUE THREAD

**Issue by terrytangyuan** [sql-machine-learning/sqlflow#715]
Currently all submitters use [one single shared Dockerfile](https://github.com/sql-machine-learning/sqlflow/blob/develop/Dockerfile), which makes the dependency heavy and could easily cause conflicts among the dependencies for different submitters. It would be better if it's splitted into multiple Dockerfiles for different submitters. 

@wangkuiyi suggested that we could split it into `Dockerfile.alps`, `Dockerfile.xgboost`, and `Dockerfile.elasticdl` where they all inherit from a base `Dockerfile` that contains the core dependencies for SQLFlow.

**Comment by wangkuiyi** [comment]
@terrytangyuan Are you talking about cases like noted in https://github.com/sql-machine-learning/sqlflow/issues/747?

**Comment by typhoonzero** [comment]
To make CI and releasing process easy, we keep only one Docker image to run the SQLFlow workflow steps: `sqlflow/sqlflow:step`, it includes all dependencies currently. And, for the user's who are developing models, they should publish the models using this image as base image.
