### ISSUE TITLE
Verify the model trained by AntXgBoost can be explained by SHAP

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#727]
A native XgBoost model can be explained by SHAP using the following code snippet.
```python
import shap
shap.initjs()
X,y = shap.datasets.boston()

import xgboost
model = xgboost.train({"learning_rate": 0.01}, xgboost.DMatrix(X, label=y), 100)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)

# summarize the effects of all the features
shap.summary_plot(shap_values, X, plot_type="dot")
```

**Comment by weiguoz** [comment]
After
1. train [xgboost.Estimator](https://github.com/sql-machine-learning/sqlflow/blob/95a6d900c275e9aea7afe92c298896fb0bf463f0/sql/codegen_xgboost_test.go#L26-L37) then save the model
1. decompress the `{model_file}.tar.gz` the choose the file `sqlflow_booster`
1. run `shap` to explain
``` python
import shap
import xgboost

shap.initjs()
X, y = shap.datasets.boston()

m = xgboost.XGBModel(nthread=4)
m.load_model(fname='models/sqlflow_booster') # load the saved model

explainer = shap.TreeExplainer(m)
shap_values = explainer.shap_values(X)

shap.summary_plot(shap_values, X, plot_type="dot")
```
I got an error:
```
Traceback (most recent call last):
  File "play_shap.py", line 10, in <module>
    explainer = shap.TreeExplainer(m)
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/tree.py", line 96, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing)
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/tree.py", line 610, in __init__
    raise Exception("Model type not yet supported by TreeExplainer: " + str(type(model)))
Exception: Model type not yet supported by TreeExplainer: <class 'xgboost.sklearn.XGBModel'>
```

It looks `shap` complains `sqlflow_booster` is not a `sklearn.XGBModel`.
@sperlingxx would you please check it out?

**Comment by tonyyang-svail** [comment]
Hi @weiguoz, thanks for testing out this issue. I also attempted to load the trained model with
```python
import xgboost as xgb
m = xgb.Booster({'nthread': 4})
m.load_model('sqlflow_models.my_xgboost_model/sqlflow_booster')
```
I am wondering the following:
1. What is the difference between `xgboost.XGBModel` and `xgboost.Booster`?
2. `load_model` doesn't recover the feature names. [ref](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L1458-L1459). It seems that mapping the analysis data to the model input needs special boilerplate code.

**Comment by sperlingxx** [comment]
@tonyyang-svail @weiguoz 

Following code snippet is working.

```python
import shap
import xgboost

shap.initjs()
X, y = shap.datasets.iris()

bst = xgboost.Booster()
bst. load_model(fname='models/sqlflow_booster') # load the saved model

explainer = shap.TreeExplainer(bst)
shap_values = explainer.shap_values(X)

shap.summary_plot(shap_values, X)
```

`xgboost.Booster` is identifiable format for xgboost kernel, which can be loaded from/dumped to a binary file.
`xgboost.XGBModel` is the base class of xgboost sklearn wrapper, which contains `xgboost.Booster` and some additional meta data.

I think maybe feature names can be held by `X` if it is `pandas.DataFrame`?

**Comment by tonyyang-svail** [comment]
We have verified on XGBoost.
