### ISSUE TITLE
Do not rely on tcp connection for long running SQL statements

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#736]
For high availability reasons, we deploy multiple sqlflowserver instances on several servers and use some kind of load balancer to direct user requests to these backend servers. However, if one of the servers fails and restarts, the TCP connection for the current RPC call will definitely fail, causing the whole job to fail.

A better way to avoid keeping a long time TCP connection is to let the client fetch the SQL result periodically using the RPC call. So async SQL submission and result fetching is still needed to improve high availability of sqlflowserver.

**Comment by weiguoz** [comment]
I agree we need a short connection to check the SQL task status, for:
1. high availability: During deployment, the server needs to be restarted.
1. a new feature: Once a SQL job submitted, we can check the status regularly.

**Comment by typhoonzero** [comment]
We use workflow to manage long-running jobs. Status is fetched periodically and output to the client, see: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/high_available_sqlflow_server.md
