### ISSUE TITLE
Two versions of TensorFlow are installed on the Docker image

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#747]
The SQLFlow docker image is currently about 2GB and the Python packages make up ~1.5GB. And there are two versions of TensorFlow, each takes 300MB+.
```bash
(sqlflow-dev) root@621f11d98588:/miniconda/envs/sqlflow-dev/lib/python3.6/site-packages# du -sh * | sort -hr | head -n 5
398M	tensorflow
344M	tensorflow-2.0.0a0-py3.6-linux-x86_64.egg
88M	scipy
70M	numpy
57M	pandas
```
After digging into the code, we found our model repo is [using `'tensorflow==2.0.0-alpha0'`](https://github.com/sql-machine-learning/models/blob/develop/setup.py#L25), while SQLFlow [uses `TENSORFLOW_VERSION="2.0.0b1"`](https://github.com/sql-machine-learning/sqlflow/blob/36d822c69a195056c754fcb5d466d773226b6e2d/Dockerfile#L13).

Shall we unify them?

@typhoonzero I vaguely remember there is a reason for models repo to stick with the alpha version, but I couldn't recall.

**Comment by terrytangyuan** [comment]
BTW there's v2.0.0-rc0 now which should be more stable than those: https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0-rc0

**Comment by tonyyang-svail** [comment]
As models repo's TF has been updated to `2.0.0b1`, which is same as the SQLFlow repo, so I am closing this issue.
