### ISSUE TITLE
To support xgboost and ant-xgboost in SQLFlow

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#758]
**Is your feature request related to a problem? Please describe.**
We prefer to support ant-xgboost and xgboost in SQLFlow, we can keep the SQL syntax consistent and  distinguish the difference xgboost branch with env `SQLFLOW_WITH_ANTXGBOOST=ON`,

- [x] rename code from the exsiting xgboost to ant-xgboost #754 
- [ ] Refine Dockerfile to install xgboost or ant-xgboost by build arg `SQLFLOW_WITH_ANTXGBOOST`
- [ ] Enable test ant-xgboost and xgboost on CI system.

**Comment by typhoonzero** [comment]
XGBoost support is already implemented in previous commits.
