### ISSUE TITLE
Issue about the format of PREDICT clause

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#766]
**Is your feature request related to a problem? Please describe.**
When using local model to make prediction based on iris database, 
```
%%sqlflow 
SELECT *
FROM datamap_test.iris_test
PREDICT datamap_test.iris_xgb_predict.class
WITH
	pred.append_columns = [sepal_length, sepal_width, petal_length, petal_width],
	pred.prob_column = prob,
	pred.detail_column = detail,
	pred.encoding_column = encoding
USING datamap_test.iris_xgb_model;
```

it throw exception like :
```
sqlflow_submitter.xgboost.common.XGBoostError: XGBoost prediction task failed: column: class should be in table columns:{'iris_xgb_predict': 0}
```
This problem can be solved by remove the name of database in `PREDICT` clause.

**Describe the solution you'd like**
It should be better to provide more detail about the format of `PREDICT` clause. Or maybe it can throw another exception which is more convenient to find out the problem rather than only about the column.
 
**Additional Notes**
![1](https://user-images.githubusercontent.com/4661989/64148414-e0c41680-ce55-11e9-999b-b304298c4a04.jpeg)

![image](https://user-images.githubusercontent.com/4661989/64148864-00a80a00-ce57-11e9-936d-d986e4ed6074.png)

**Comment by tonyyang-svail** [comment]
I am closing this PR since it is related to AntXGBoost, while the SQLFlow now switches to XGBoost.
