### ISSUE TITLE
Support ODPS Query settings in SQLFlow SQL

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#769]
**Is your feature request related to a problem? Please describe.**
In some scenarios, The MaxCompute can set runtime settings while executing the query, ref [here](https://github.com/aliyun/aliyun-odps-python-sdk/blob/master/docs/source/base-sql.rst#%E8%AE%BE%E7%BD%AE%E8%BF%90%E8%A1%8C%E5%8F%82%E6%95%B0)

**Describe the solution you'd like**
In my opinion, SQLFLow can allow users to specify the query settings on the client-side like:
  
``` sql
odps.sql.type.system.odps2=true;
CREATE TABLE xxxx
```

**Comment by tonyyang-svail** [comment]
The server splits multiple SQL statements according to `;` token. Adding support for query settings will break this splitting strategy.

I suggest putting this feature on hold.
