### ISSUE TITLE
Throw Exception "converting driver.Value type float64 ("-0.034224987") to a int64 " when select data from predictions in notebook

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#770]
**Description**
Throw Exception "converting driver.Value type float64 ("-0.034224987") to a int64 " when select data from predictions in notebook.

**Reproduction Steps**
Train Step
```
%%sqlflow
SELECT *
FROM datamap_test.ds_xgboost_train
TRAIN xgboost.REGRESSOR
WITH
    train.verbosity = 2,
    train.num_round = 50,
    train.subsample = 1
COLUMN COL_1, COL_2, COL_3
LABEL GOAL_1
INTO datamap_test.ds_xgboost_model ;
```

Predict
```
%%sqlflow 
SELECT *
FROM datamap_test.ds_xgboost_test
PREDICT ds_xgboost_predict.GOAL_1
WITH
	pred.append_columns = [COL_1, COL_2, COL_3]
USING datamap_test.ds_xgboost_model;
```

Select  Prediction
```
%%sqlflow
SELECT *
FROM datamap_test.ds_xgboost_predict
LIMIT 5 ;
```

This SELECT works in HiveCLI. However when running it in notebook, it thrown exception like following .

```
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "sql: Scan error on column index 57, name "ds_xgboost_predict.duration": converting driver.Value type float64 ("-0.034224987") to a int64: invalid syntax"
	debug_error_string = "{"created":"@1567508579.253829853","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"sql: Scan error on column index 57, name "ds_xgboost_predict.GOAL_1": converting driver.Value type float64 ("-0.034224987") to a int64: invalid syntax","grpc_status":2}"
```

**Expected Behavior**

**Screenshots**

**Environment (Please complete the following information):**
 - OS:
 - Browser:
 - Version: based on commit  `9a0dc86 refine code structure for expression resolver (#760)`

**Additional Notes**

**Comment by Yancey0623** [comment]
Maybe you can show the result of `desc  datamap_test.ds_xgboost_predict ` and `select * from datamap_test.ds_xgboost_predict` in beeline CLI?

**Comment by BlackPoint-CX** [comment]
> Maybe you can show the result of `desc datamap_test.ds_xgboost_predict ` and `select * from datamap_test.ds_xgboost_predict` in beeline CLI?

![1](https://user-images.githubusercontent.com/4661989/64170031-a7a19b80-ce81-11e9-8d7f-135fb296669c.png)
![2](https://user-images.githubusercontent.com/4661989/64170033-a8d2c880-ce81-11e9-8ae4-5a70ac9d2dd9.png)

**Comment by Yancey0623** [comment]
It seems a bug of gohive package, I fixed it by https://github.com/sql-machine-learning/gohive/pull/54 .

**Comment by tonyyang-svail** [comment]
@Yancey1989 @BlackPoint-CX Has this issue been fixed? If so, please close it.
