### ISSUE TITLE
Speed up the CI build

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#773]
**Is your feature request related to a problem? Please describe.**

The duration of travis-ci build has been more than [45mins](https://travis-ci.com/sql-machine-learning/sqlflow/builds/125837707),  maybe we can do something to speed up it:

- don't need to build the dev Docker image for each PR, except the `Dockerfile` or `build_image.sh` has been chanaged.
- parallel run the tests for difference DB engine(MySQL/Hive/Maxcompute), https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines

**Comment by tonyyang-svail** [comment]
Related https://github.com/sql-machine-learning/sqlflow/pull/921

**Comment by tonyyang-svail** [comment]
Fixed by https://github.com/sql-machine-learning/sqlflow/pull/1089.
