### ISSUE TITLE
commit 2041069 cause select data problem

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#796]
**Description**
2041069 support multiple sql statements in one rpc call (#740) # wrong
9edd805 [Design] Support multiple SQL statements (#779) # work
57b084d Grammatical improvement on design doc (#778) # work

**Reproduction Steps**
```
%%sqlflow
SELECT *
FROM datamap_test.ds_dnn_predict
LIMIT 10 ; 
```
**Expected Behavior**
What you expected to happen.

**Screenshots**
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/sqlflow/client.py in __repr__(self)
     58         table = PrettyTable(self._column_names)
     59         for row in self.rows():
---> 60             table.add_row(row)
     61         return table.__str__()
     62 

~/miniconda/envs/sqlflow-dev/lib/python3.5/site-packages/prettytable.py in add_row(self, row)
    816 
    817         if self._field_names and len(row) != len(self._field_names):
--> 818             raise Exception("Row has incorrect number of values, (actual) %d!=%d (expected)" %(len(row),len(self._field_names)))
    819         if not self._field_names:
    820             self.field_names = [("Field %d" % (n+1)) for n in range(0,len(row))]

Exception: Row has incorrect number of values, (actual) 0!=54 (expected)
```

**Comment by Yancey0623** [comment]
I cannot reproduce this error using the standard Hive Docker image, here is my operation list:

1. Launcher the Hive Docker container and SQLFlow Docker container
    ``` bash
    > docker run -d -p 8888:8888 --name=hive sqlflow/gohive:dev python3 -m http.server 8899
    > docker run -it --rm -v $GOPATH:/go --net=container:hive --entrypoint bash -w 
    /go/src/github.com/sql-machine-learning/sqlflow sqlflow/sqlflow 
    ``` 
1. launch notebook and sqlflowserver process
    ``` bash
    docker exec -it <sqlflow-container-id> bash 
    > bash /start.sh sqlflow-notebook &
    > sqlflowserver --datasrouce="hive://root:root@localhost:10000/iris"
    ```

1. Notebook logs:

![image](https://user-images.githubusercontent.com/1426912/64521226-3acb4d00-d32a-11e9-83e9-ce3dc09afd8a.png)

Did I miss anything?

**Comment by BlackPoint-CX** [comment]
> I cannot reproduce this error using the standard Hive Docker image, here is my operation list:
> 
> 1. Launcher the Hive Docker container and SQLFlow Docker container
>    ```shell
>    > docker run -d -p 8888:8888 --name=hive sqlflow/gohive:dev python3 -m http.server 8899
>    > docker run -it --rm -v $GOPATH:/go --net=container:hive --entrypoint bash -w 
>    /go/src/github.com/sql-machine-learning/sqlflow sqlflow/sqlflow 
>    ```
> 2. launch notebook and sqlflowserver process
>    ```shell
>    docker exec -it <sqlflow-container-id> bash 
>    > bash /start.sh sqlflow-notebook &
>    > sqlflowserver --datasrouce="hive://root:root@localhost:10000/iris"
>    ```
> 3. Notebook logs:
> 
> ![image](https://user-images.githubusercontent.com/1426912/64521226-3acb4d00-d32a-11e9-83e9-ce3dc09afd8a.png)
> 
> Did I miss anything?

Solved. Unnecessary blank following the select clause cause this problem.
![image](https://user-images.githubusercontent.com/4661989/64530130-fbf3c200-d33e-11e9-8869-6cdde27e0b2a.png)
