### ISSUE TITLE
Unify featurecolumn and column spec

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#799]
@typhoonzero Should feature column and column spec be put in the same struct?

https://github.com/sql-machine-learning/sqlflow/blob/ced5708d42e42630f992ec131c2406a0b116c013/sql/columns/feature_column.go#L38-L39

**Comment by typhoonzero** [comment]
I'm sure we can put all the information in one struct for each column, and that's a lot of work to do.

**Comment by typhoonzero** [comment]
I'll do this first before https://github.com/sql-machine-learning/sqlflow/issues/705 so that it will be more easier to finishi feature derivation.

**Comment by tonyyang-svail** [comment]
@typhoonzero As my effort in https://github.com/sql-machine-learning/sqlflow/issues/800#issuecomment-530087600, I find it hard to directly modify the feature column and column spec because various code generators are depending on it.

![Alt text](https://g.gravizo.com/svg?digraph%20G%20{TensorFlowCodegen->resolveTrainColumn;%20TensorFlowCodegen%20-%3E%20resolveAttribute;%20XgBoostCodegen%20-%3E%20resolveTrainColumn;%20XgBoostCodegen%20-%3E%20resolveAttribute;%20EDLCodegen%20-%3E%20resolveTrainColumn;%20EDLCodegen%20-%3E%20resolveAttribute;%20})

Since all the code generators are going to be depend on the intermediate representation, We may want to implement the generation of IR first. By implementing functions `resolveTrainColumnForIR`, `resolveAttributeForIR` and `FeatureDerivationForIR`, we can build IR independently. `resolveTrainColumnForIR` and `resolveTrainColumn` may contain share some duplicated code, but it is fine.

![Alt text](https://g.gravizo.com/svg?digraph%20G%20{%20TensorFlowCodegen%20-%3E%20resolveTrainColumn;%20TensorFlowCodegen%20-%3E%20resolveAttribute;%20XgBoostCodegen%20-%3E%20resolveTrainColumn;%20XgBoostCodegen%20-%3E%20resolveAttribute;%20EDLCodegen%20-%3E%20resolveTrainColumn;%20EDLCodegen%20-%3E%20resolveAttribute;%20IR%20-%3E%20resolveAttributeForIR;%20IR%20-%3E%20resolveTrainColumnForIR;%20IR%20-%3E%20featureDerivation;%20})

Then we let all the code generators depend on IR and delete the old resolvers.

![Alt text](https://g.gravizo.com/svg?digraph%20G%20{%20TensorFlowCodegen%20-%3E%20IR;%20XgBoostCodegen%20-%3E%20IR;%20EDLCodegen%20-%3E%20IR;%20IR%20-%3E%20resolveAttributeForIR;%20IR%20-%3E%20resolveTrainColumnForIR;%20IR%20-%3E%20featureDerivation;%20}).

**Comment by typhoonzero** [comment]
@tonyyang-svail You are right! I closed #808, and the feature derivation work should also depend on this. I can help finish the IR work first.

**Comment by tonyyang-svail** [comment]
I am closing this PR because we are no longer attempting to unify feature column and column spec. Please refer to codegen package for IR.
