### ISSUE TITLE
resolveExpression should distinguish string, integer and float

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#800]
As the intermediate representation defines the attribute as `map[string]interface{}`, the `sql` package should resolve the following SQLFlow statement
```
SELECT ...
TRAIN ... 
WITH
    model.objective="multi:softprob",
    train.num_boost_round = 30,
    model.eta = 3.1,
    model.num_class = 3
```
as string, int, float, int respectively. However, our expression resolver return all these attribute as type string.

**Comment by weiguoz** [comment]
Shall the resolver consider `bool`?

**Comment by tonyyang-svail** [comment]
@weiguoz good question. I think the resolver should consider bool. So `train.early_stop = False` should be resolved as `bool`.

**Comment by tonyyang-svail** [comment]
I wasn't able to modify the `resolveExpression` because many code-generators are depending on it. So I will add this distinguish functionality as a separate function. After we have migrated all code-generators to the intermediate representation, I will update `resolveExpression`.

**Comment by tonyyang-svail** [comment]
Fixed by https://github.com/sql-machine-learning/sqlflow/pull/865
