### ISSUE TITLE
Update design for parser on how to split multiple sql statements and how to split standard SQL from extended SQL

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#802]
The current design https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/syntax.md only describe the design choice of how to split multiple SQL statements, but the following functions are all parts of the SQL parser, and it's quite related to each other:

- split multiple SQL statements by `;`
- split "standard SQL" and "TRAIN/PREDICT" SQL
- whether we need to embed external parsers like tidb parser for different database implementations.

We need an overall design doc to describe how to implement them all.

**Comment by tonyyang-svail** [comment]
@typhoonzero Please feel free to reuse the design doc at https://github.com/sql-machine-learning/sqlflow/pull/591

**Comment by typhoonzero** [comment]
The latest design doc is at https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/sqlflow_parser.md
