### ISSUE TITLE
[Intermediate Representation] XGBoost codegen refactor TODO list

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#805]
As discussed in the design doc #785, we will generate the Python submitter program from the intermediate representation.
 
1. Transfer the training logic to `TrainIR`.
	1. Generate the training program from mocked `TrainIR`. #827 
		1. Create a Python database connector from the data source string. #806
	1. Generate `TrainIR` from SQL
		1. Unify feature column and column spec. #799 
		1. Make expression resolver realize type. #800 
	1. Enable SQLFlow to execute the XGB train code generated by IR. #980 
        1. Use pkg/sql/codegen/attribute in XGBoost TrainIR. #1002
        1. Add XGBoost training documentation. #1003
1. Transfer Analysis to `AnalyzeIR`. #978
1. Transfer the predict logic to `PredictIR`. #1051

**Comment by typhoonzero** [comment]
After we finish above work, we should add a validator to validate attributes and generate documents for each codegen models: https://github.com/sql-machine-learning/sqlflow/issues/774
