### ISSUE TITLE
[Python] Generate Python database connector from data source string

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#806]
To avoid all the code generator having the same database connection logic, we may have a Python function like
```python
def connect_with_data_source(data_source):
    driver, source = data_source.split("://")
    if driver != "mysql":
        raise ValueError("connect_with_data_source doesn't support driver type {}".format(driver))

    if driver == "mysql":
        user, passwd, _, host, port = re.findall("^(\w*):(\w*)@(\w*)\((.*):(.*)\)/?.*$", source)[0]
        from MySQLdb import connect
        conn = connect(user=user,
                       passwd=passwd,
                       host=host,
                       port=int(port))
    conn.driver = driver
    return conn
```
@weiguoz @Yancey1989 What do you think?

**Comment by Yancey0623** [comment]
Hi @tonyyang-svail, I'm not sure we would implement parsing `datasource` logic in Python, each DBdriver has `ParseDSN` function to parse the `datasource` string, such as  [gohive.ParseDSN](https://github.com/sql-machine-learning/gohive/blob/develop/dsn.go#L28) would parse datasource string to  fields `username, password, session_cfg` etc... . re-implement this logic may easy to cause a bug.

**Comment by tonyyang-svail** [comment]
> Hi @tonyyang-svail, I'm not sure we would implement parsing datasource logic in Python, each DBdriver has ParseDSN function to parse the datasource string, such as gohive.ParseDSN would parse datasource string to fields username, password, session_cfg etc... . re-implement this logic may easy to cause a bug.

@Yancey1989 Sure

**Comment by weiguoz** [comment]
I agree that making a connection with `Datasource` in python. And this my opinions:

- the format of `Datasource` needs to be standard, whether in go or in python
I think  [sqlalchemy](https://docs.sqlalchemy.org/en/13/core/engines.html) can give some reference.

~~- SQLFlow splits the training dataset to train&val, reads schema, does verify and runs the standard SQL in `go`. Can SQLFlow do these just in python, replace the driver `database/sql` in go?~~
