### ISSUE TITLE
Add prediction and analyzing syntax to the user guide

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#826]
Currently, the syntax section in the [user guide](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/user_guide.md#syntax) only contains the training syntax.

**Comment by Yancey0623** [comment]
Hi @tonyyang-svail maybe we can separate the user guide into the following 4 sections :
1. Train/Predict a Deep Learning Model 
1. Train/Predict a Tree Model
1. Analyze the machine learning model
1. Train/Using an unsupervised learning model

**Comment by tonyyang-svail** [comment]
Hi @Yancey1989, thanks for the suggestion.

I have renamed the user guide to the language guide. The language guide contains the specification of the all extended syntax.

And I believe all the tutorials will serve as the four sections you mentioned.
