### ISSUE TITLE
We don't need LABEL while training a clustering mode

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#839]
Related to #838 

```SQL
SELECT *
FROM iris.train
TRAIN sqlflow_models.DeepEmbeddingClusterModel
WITH
    model.n_clusters = 5,
    model.run_pretrain = false,
    model.pretrain_dims = [4,500,500,2000,10]
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class   -- useless
INTO sqlflow_models.clustering_model;
```

`LABEL` here in the `TRAIN` SQL is unnecessary.

**Comment by tonyyang-svail** [comment]
@weiguoz In the current release, shall we use `LABEL ""` as a workaround?

**Comment by wangkuiyi** [comment]
@tonyyang-svail Why should we have this walkaround? Can we simply remove the LABEL clause in the case of unsupervised learning?

Before the coming release, I think it is clear that we need to remove LABEL when unsupervised learning.

**Comment by wangkuiyi** [comment]
This is related to https://github.com/sql-machine-learning/sqlflow/issues/826

**Comment by Yancey0623** [comment]
Agree with removing the LABEL clause for the unsupervised learning model, I will try to fix it today.
