### ISSUE TITLE
Add test with the auth hiveserver2  

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#841]
`sqlflow/gohive:dev` can enable auth by `WITH_HS2_PAM_AUTH=ON`, we can add this unit test in SQLFlow

**Comment by typhoonzero** [comment]
Supported auth type settings using DB connection strings: https://github.com/sql-machine-learning/sqlflow/blob/develop/python/runtime/dbapi/hive.py
