### ISSUE TITLE
[unsupervised learning]Don't need to split train/evaluate dataset if no label clause

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#875]
For most cases of the unsupervised learning models, users don't need to specify `LABEL clause` in SQLFlow, sqlflow server also doesn't need to split train/validation dataset.

**Comment by Yancey0623** [comment]
I am reopening this issue because #883  need a unit test as commented here: https://github.com/sql-machine-learning/sqlflow/pull/883#discussion_r326504094 .

**Comment by typhoonzero** [comment]
We don't split the training/validation dataset automatically now. Closing.
