### ISSUE TITLE
Add e2e test to run IPython tutorials

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#890]
All the tutorials under `/doc/examples` would be converted into iPython notebook scripts, we need to update the `test_e2e.sh` to make sure all the tutorials can work properly.

**Comment by wangkuiyi** [comment]
Agree. 

I renamed `/doc/examples` into `/doc/tutorial`. 

@shendiaomo renamed `test_e2e.sh` into `test_ipython.sh`, which calls `ipython` to run [`sql/python/test_magic.py`](https://github.com/sql-machine-learning/sqlflow/blob/develop/sql/python/test_magic.py).

I think what we need is a `test_jupyter.sh`, which calls Jupyter to run the converted notebooks. This approach might work https://stackoverflow.com/a/35545497.

**Comment by tonyyang-svail** [comment]
I found there is no end to end test for `ANALYZE` SQL, which makes this issue more important.
