### ISSUE TITLE
Attribute supports more type derivation

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#910]
This issue comes from  PR: https://github.com/sql-machine-learning/models/pull/19/files, the WITH clause: `WITH model. pretrain_lr =0.01` should be converted to FLOAT type instead of STRING type, that we don't need to cast the type in the model constructor.

**Comment by typhoonzero** [comment]
The IR work in https://github.com/sql-machine-learning/sqlflow/pull/865 already supported this.
