### ISSUE TITLE
A question: can I use sqlflow together with kubeflow?

### ISSUE THREAD

**Issue by liufuyang** [sql-machine-learning/sqlflow#911]
I have seen a good development on the kubeflow project. Is it possible that I can try out sqlflow together with kubeflow?  Thank you :)

**Comment by ywskycn** [comment]
@liufuyang SQLFlow can be easily integrated with Kubeflow. SQLFlow has different codegens (https://github.com/sql-machine-learning/sqlflow/tree/develop/pkg/sql/codegen) for generating and submitting different types of jobs. For running Kubeflow jobs (tf/pytorch/mpi/..), we need to add corresponding codegens in SQLFlow and use k8s APIs to submit to the cluster. Also, we can general a pipeline and submit it to kfp/argo.

@liufuyang it would be nice to have more information about how you use Kubeflow now.

**Comment by liufuyang** [comment]
@ywskycn Oh sounds pretty cool. I am very new to kubeflow as well. In the coming weeks I have some hackweek at the office, perhaps by then I can give you more info and ask some more detailed questions. At the company I am working at, we recently started letting people try out the kubeflow solutions. The data infra team has done some work so our official kubeflow is somehow integrated into our infrastructure. However perhaps I can firstly just make a GKE cluster of my own and have kubeflow running on it so I can have a full control of it while trying out stuff :)

I am also thinking about using TiDB as the datasource with sqlflow. I guess sqlflow now can already work with Tidb seamlessly or I still need to hack a bit here and there to make it work?

**Comment by typhoonzero** [comment]
> I am also thinking about using TiDB as the datasource with sqlflow. I guess sqlflow now can already work with Tidb seamlessly or I still need to hack a bit here and there to make it work?

We have tried that SQLFlow already works with TiDB. And TiDB claims that it is fully compatible with MySQL, it's easy to connect SQLFlow with it.

**Comment by liufuyang** [comment]
Thank you @typhoonzero :)
