### ISSUE TITLE
Index column should be included in the Clustering model's prediction result

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#932]
In the application scenario of the clustering model, the index column is usually meaningful to the users. So the index should be included in the prediction result. However, the current clustering model only includes columns for modeling and class columns in the prediction table.

**Comment by tonyyang-svail** [comment]
Related https://github.com/sql-machine-learning/sqlflow/issues/133.

**Comment by Echo9573** [comment]
After discussing with @Yancey1989   and  @BlackPoint-CX, we have come up with two solutions. One is to copy the original form directly and then concatenating the predicted category. Another method is to add a keyword to the prediction clause to mark the primary key.
Which method is better, do you have any suggestions?

**Comment by typhoonzero** [comment]
Close due to inactivity, please feel free to reopen this.
