### ISSUE TITLE
Use Binder.org to demonstrate Jupyter notebooks

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#948]
In SHAP's README.md file, there is a badge pointing to Binder.org, which, once clicked, opens a Jupyter Notebook page and presents all .pynb files in the repo.

https://github.com/slundberg/shap/blob/master/README.md

We can use Binder.org to demonstrate SQLFlow as well.

According to https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html#when-you-re-using-a-language-that-is-not-directly-supported, Binder.org supports building from a Dockerfile, which we already had.

**Comment by tonyyang-svail** [comment]
Hi @wangkuiyi, thanks for the suggestion. I will try it out this week.

**Comment by tonyyang-svail** [comment]
Hi @wangkuiyi, I have tried in the last couple of days but wasn't able to set it up. I wasn't able to move on due to limited information on the error log. I have filed the issue I found at https://github.com/jupyterhub/binder/issues/172 and will try again once I receive a reply.

**Comment by typhoonzero** [comment]
We can use either aliyun DSW or our playground https://playground.sqlflow.tech/ now.
