### ISSUE TITLE
Use Coverage to stat test coverage

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#954]
In https://github.com/kubeflow/katib, they have a badge of coverage. How about we add one as well?

<img width="81" alt="overage" src="https://user-images.githubusercontent.com/1548775/66147315-7a045b00-e5c3-11e9-9856-e433fcb6615b.png">

**Comment by typhoonzero** [comment]
Due to https://github.com/sql-machine-learning/sqlflow/issues/435 I did not add the badge, I'll try it again.
