### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#968]
```
2019/10/09 10:08:03 Server Started at :50051
[TerminalIPythonApp] WARNING | Unknown error in handling startup files:
UsageError: Line magic function `%autoreload` not found.
[TerminalIPythonApp] WARNING | File not found: 'sql/python/test_magic.py'
```
1. `%autoreload not found`. I am not sure about the cause.
2. `File not found: 'sql/python/test_magic.py`  due to the directory `sql/python` is outdated.

**Comment by tonyyang-svail** [comment]
For 1, the `UsageError` went away after I load `%autoreloat` manually as suggested [here](https://stackoverflow.com/a/36573286).

For 2, you are right. The directory is outdated.

After fixing them, we have
```
(sqlflow-dev) root@linuxkit-025000000001:/go/src/sqlflow.org/sqlflow# bash scripts/test_ipython.sh
2019/10/09 17:32:38 Launch server with insecure mode.
2019/10/09 17:32:38 failed to listen: listen tcp :50051: bind: address already in use
1 row affected
0 row affected
2 rows affected
   features  label
0       1.0      0
.
----------------------------------------------------------------------
Ran 1 test in 0.564s

OK
```

**Comment by tonyyang-svail** [comment]
However, it is weird that the program `ipython file_doesnt_exist.py` exits with code 0. As a consequence, our CI still shows a success.

I haven't found a solution to make it return 1.
