### ISSUE TITLE
Add a check in `Train` to make sure `ValidationSelect` in `TrainIR` is always empty

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#988]
Sure. Maybe add a check in `Train` to make sure `ValidationSelect` in `TrainIR` is always empty.

_Originally posted by @tonyyang-svail in https://github.com/sql-machine-learning/sqlflow/pull/982_

**Comment by typhoonzero** [comment]
Training using XGBoost can pass `WITH validation.select` in the latest release now.
