### ISSUE TITLE
Add pylint to check Python code style

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#989]
Hi guys, do we need to add pylint to check our Python code style?

**Comment by terrytangyuan** [comment]
ElasticDL uses flake8 to check code style and use black to automatically format the code. Here’s the config you can probably borrow: https://github.com/sql-machine-learning/elasticdl/blob/develop/.pre-commit-config.yaml

**Comment by typhoonzero** [comment]
Done by @sneaxiy 's work.
