### ISSUE TITLE
repl supports -e -f 

### ISSUE THREAD

**Issue by zwqjsj0404** [sql-machine-learning/sqlflow#993]
**Is your feature request related to a problem? Please describe.**
A clear description of the problem

**Describe the solution you'd like**
sqlflow -e "sql"
sqlflow -f filename

**Describe alternatives (optional)**
A clear description of any alternative solutions or features

**Additional Notes**

**Comment by tonyyang-svail** [comment]
Hi @zwqjsj0404, thank you for supporting this issue. Could you please describe
- what is `-e` and `-f`?
- what should the `repl -e` and `repl -f` return/print?

**Comment by zwqjsj0404** [comment]
> Hi @zwqjsj0404, thank you for supporting this issue. Could you please describe
> 
> * what is `-e` and `-f`?
> * what should the `repl -e` and `repl -f` return/print?
The log information is output to the standard error stream, and the result information is output to the standard output stream

**Comment by shendiaomo** [comment]
> > Hi @zwqjsj0404, thank you for supporting this issue. Could you please describe
> > 
> > * what is `-e` and `-f`?
> > * what should the `repl -e` and `repl -f` return/print?
> >   The log information is output to the standard error stream, and the result information is output to the standard output stream

IMO the `-f` requirement can be satisfied by shell redirection. The current version of repl doesn't do this because it didn't process EOF properly. We'll fix this later.
