### ISSUE TITLE
String type label cause sqlflowserver process failed

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#996]
**Description**
Wrongly defined `string` type of label will cause sqlflowserver crush down and throws error.
```
FATA[0549] Unsupported label data type: STRING_TYPE      package=sql 
```

**Comment by tonyyang-svail** [comment]
@BlackPoint-CX Thanks for submitting this PR. You are right. The server should return an error instead of crushing down.
