### ISSUE TITLE
Rethink syntax extension

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#998]
During our efforts to deploy SQLFlow in some real cases, we tried to extend the syntax of some SQL dialects, including MySQL and Hive. In these efforts, we learned an art: 

**Try reusing existing SQL [reserved words](https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words) in the extended syntax.**

Why this art? Let us look at an example in https://github.com/sql-machine-learning/sqlflow/issues/473.  Because `TRAIN` isn't a reserved word, users could name a field by `TRAIN`, and this might confuse our parser. The solution is to either replace `TRAIN` by a reserved word, where we couldn't find one that expresses the meaning of "train", or, extend `TRAIN` into `TO TRAIN`, where, please be aware that `TO` is a reserved word.

It seems that other [clause extensions](https://github.com/sql-machine-learning/sqlflow/blob/develop/pkg/sql/sql.y#L208) after `TO TRAIN`, `TO PREDICT`, and `TO EXPLAIN` can use arbitrary words, as they are not going to be parsed by a SQL (dialect) parser, but the SQLFlow parser. However, it is not that simple.  Consider that a table might have a field named `label`, and this field happens to be a label when we train a model. The SQL statement would look like

```sql
SELECT a, b, label FROM tbl
TO TRAIN Model
LABEL label
```

This would confuse the parser. Our current workaround is [this](https://github.com/sql-machine-learning/sqlflow/blob/d3ec581b1000644479652b74b0df6b0c8608fd9a/pkg/sql/sql.y#L265). However, a complete solutions seems that we don't use `OUTPUT` to replace `LABEL`. `OUTPUT` is a SQL keyword, so users are not supposed to name a field by `OUTPUT`. (This might not be true always, but, at least, it seems that the probability of `OUTPUT output` is smaller than that of `LABEL label`.)

Please vote for the following syntax changes:

**Comment by wangkuiyi** [comment]
`TRAIN` to `TO TRAIN`, as marked in https://github.com/sql-machine-learning/sqlflow/issues/473

**Comment by wangkuiyi** [comment]
`PREDICT` to `TO PREDICT`

**Comment by wangkuiyi** [comment]
`ANALYSE` to `TO EXPLAIN`. Both `ANALYZE` and `EXPLAIN` are SQL reserved words. It seems that `EXPLAIN` is more comprehensive when we do the model explanation. And the use of `TO` is to keep consistent style with `TO TRAIN` and `TO PREDICT`.

**Comment by wangkuiyi** [comment]
`LABEL` to `OUTPUT`, which is a SQL reserved word, or other SQL reserved word, which is listed in https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words.

**Comment by wangkuiyi** [comment]
`USING` to `USE`, which is a SQL reserved word.

---------

Updated: Thanks to @typhoonzero to point this out -- both `USING` and `USE` are SQL reserved words. So, it seems no need to change here.

**Comment by typhoonzero** [comment]
Seems `USING` is a reserved word: https://www.geeksforgeeks.org/sql-using-clause/

**Comment by shendiaomo** [comment]
> `LABEL` to `OUTPUT`, which is a SQL reserved word, or other SQL reserved word, which is listed in https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words.

It seems `OUTPUT` is only a SQL Server keyword: https://stackoverflow.com/questions/5817414/output-clause-in-mysql
If this is true, changing `LABEL`  to `OUTPUT` may not improve the situation.

To leverage existing parsers of SQL dialects to avoid the problem, it seems that we should choose a keyword that is used by most of SQL dialects.  As a counter example, MySQL will not utter a word when executing the following statement:
```SQL
CREATE TABLE OUTPUT (OUTPUT int);
```
though `OUTPUT` **is** a reserved keyword.

Can we consider a  preposition rather than nouns or verbs? For instance:
```SQL
SELECT a, b, label FROM tbl TO TRAIN Model ON label;
```
This comes to me when I saw a paper using the same expression: [Using trusted data to train deep networks on labels corrupted by severe noise](http://papers.nips.cc/paper/8246-using-trusted-data-to-train-deep-networks-on-labels-corrupted-by-severe-noise)

**Comment by weiguoz** [comment]
> `LABEL` to `OUTPUT`, which is a SQL reserved word, or other SQL reserved word, which is listed in https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words.

How about using the `MATCH`?

**Comment by tonyyang-svail** [comment]
@wangkuiyi How about LABEL => OUT.

All MySQL, MaxCompute, and Hive consider `OUT` as a reversed keyword.
1. [MaxCompute reserved keyword list](https://www.alibabacloud.com/help/doc-detail/27872.htm?spm=a2c63.p38356.879954.6.631c5095hrjubf#concept-zxk-v5f-vdb)
1. [Hive reserved keyword list](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL)
1. [MySQL reserved keyword list](https://dev.mysql.com/doc/refman/5.5/en/keywords.html)

**Comment by tonyyang-svail** [comment]
Here are my thoughts on the following art:

> **Try reusing existing SQL [reserved words](https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words) in the extended syntax.**

SQLFlow should not add any keyword to the SQL standard. For example, if SQLFlow adds `TRAIN` as a keyword, the user needs to rewrite `select * from train;` to `select * from 'train';`, which hurts the user experience.

**Comment by typhoonzero** [comment]
Thanks @tonyyang-svail, we should definitely use `TO TRAIN` to keep the user experience the same.

**Comment by typhoonzero** [comment]
We moved to use `TO TRAIN` now, closing.
